import test from 'node:test';import assert from 'node:assert/strict';
import {BigQuery} from '@google-cloud/bigquery';
import {CATALOGUE_QUERY_TYPES,CATALOGUE_TABLE_SCHEMAS,catalogueMergeSql,fetchShopifyCatalogue,inspectSerializedRows,persistShopifyCatalogue,syncShopifyCatalogue,validateCatalogueRows,catalogueDdl} from '../shopify/catalogue.js';
import {metadataStructSql,quoteBigQueryIdentifier} from '../product-classifications/sync.js';
import {validateCollectionDecision} from '../oracle/collection-classification.js';
import {validateShopifyCatalogueWriteContract} from '../diagnostics/shopify-catalogue-write-contract-production.js';

const schemaRows=()=>Object.entries(CATALOGUE_TABLE_SCHEMAS).flatMap(([table_name,columns])=>Object.entries(columns).map(([column_name,[data_type,is_nullable]])=>({table_name,column_name,data_type,is_nullable})));
const recordingBigQuery=calls=>({query:async options=>{calls.push(options);return [options.query.includes('INFORMATION_SCHEMA.COLUMNS')?schemaRows():[]]}});

test('dynamic metadata SQL uses AS, commas, quoting, and supports no fields',()=>{assert.equal(metadataStructSql([]),"'{}'");assert.match(metadataStructSql(['product_type']),/TO_JSON_STRING\(`product_type`\) AS `product_type`/);const sql=metadataStructSql(['product_type','vendor','tags']);assert.match(sql,/`, TO_JSON_STRING/);assert.equal(quoteBigQueryIdentifier('odd`name'),'`odd``name`')});
test('Shopify catalogue follows product, collection, and membership pagination',async()=>{let products=0,memberships=0;const graphql=async(query,{cursor})=>{if(query.includes('CatalogueProducts')){products++;return {products:{nodes:[{id:`gid://shopify/Product/${products}`,title:'Display only',productType:'Ring',vendor:'TGF',tags:['x'],status:'ACTIVE',createdAt:'2020-01-01',updatedAt:'2020-01-02'}],pageInfo:{hasNextPage:products===1,endCursor:'p2'}}}}if(query.includes('CatalogueCollections'))return {collections:{nodes:[{id:'gid://shopify/Collection/10',title:'Human review',handle:'review',updatedAt:'2020-01-01',productsCount:{count:2}}],pageInfo:{hasNextPage:false}}};memberships++;return {collection:{products:{nodes:[{id:`gid://shopify/Product/${memberships}`}],pageInfo:{hasNextPage:memberships===1,endCursor:'m2'}}}}};const result=await fetchShopifyCatalogue(graphql);assert.equal(result.products.length,2);assert.equal(result.collections.length,1);assert.deepEqual(result.memberships,[{product_id:'1',collection_id:'10'},{product_id:'2',collection_id:'10'}]);assert.equal(result.products[0].status,'active')});
test('catalogue persistence uses MERGE and authoritative membership replacement',async()=>{const calls=[],bigquery=recordingBigQuery(calls);await persistShopifyCatalogue(bigquery,'p',{products:[{product_id:'1',title:'x',product_type:'Ring',vendor:'v',tags:[],status:'archived',created_at:null,updated_at:null}],collections:[{collection_id:'2',title:'c',handle:'c',product_count:1,updated_at:null}],memberships:[]},{now:'2026-01-01T00:00:00Z'});assert.ok(calls.some(x=>x.query.includes('MERGE `p.shopify_catalogue.products`')));assert.ok(calls.some(x=>x.query.includes('WHEN NOT MATCHED BY SOURCE THEN DELETE')));assert.equal(catalogueDdl('p').length,4)});
test('catalogue materializes one ingestion timestamp independently of nullable Shopify timestamps',async()=>{const calls=[],bigquery=recordingBigQuery(calls);await persistShopifyCatalogue(bigquery,'p',{products:[{product_id:'1',title:'x',product_type:null,vendor:null,tags:[],status:'active',created_at:null,updated_at:null}],collections:[{collection_id:'2',title:'c',handle:'c',product_count:1,updated_at:null}],memberships:[{product_id:'1',collection_id:'2'}]},{catalogueSyncedAt:'2026-02-03T04:05:06.000Z'});const writes=calls.filter(call=>call.params);assert.equal(writes.length,3);assert.ok(writes.flatMap(call=>call.params.rows).every(row=>row.catalogue_synced_at.constructor.name==='BigQueryTimestamp'));assert.equal(writes[0].params.rows[0].created_at,null);assert.equal(writes[0].params.rows[0].updated_at,null);assert.match(writes[0].query,/INSERT \(product_id,title,product_type,vendor,tags,status,created_at,updated_at,catalogue_synced_at\)/)});
test('required catalogue fields fail locally before any BigQuery query',async()=>{const bigquery={query:async()=>assert.fail('BigQuery must not be called')};await assert.rejects(()=>persistShopifyCatalogue(bigquery,'p',{products:[{product_id:'',tags:[]}],collections:[],memberships:[]},{catalogueSyncedAt:'2026-01-01T00:00:00Z'}),/Invalid Shopify catalogue product row: product_id is required/);assert.throws(()=>validateCatalogueRows({products:[],collections:[{collection_id:'2',catalogue_synced_at:null}],memberships:[]}),/Invalid Shopify catalogue collection row: catalogue_synced_at is required/);assert.throws(()=>validateCatalogueRows({products:[],collections:[],memberships:[{product_id:'1',collection_id:'',catalogue_synced_at:'2026-01-01'}]}),/Invalid Shopify catalogue membership row: collection_id is required/)});
test('incomplete membership retrieval performs no writes or stale cleanup',async()=>{let calls=0;const bigquery={query:async()=>{calls++}},graphql=async query=>{if(query.includes('CatalogueProducts'))return {products:{nodes:[],pageInfo:{hasNextPage:false}}};if(query.includes('CatalogueCollections'))return {collections:{nodes:[{id:'gid://shopify/Collection/2',productsCount:{count:1}}],pageInfo:{hasNextPage:false}}};throw new Error('membership fetch failed')};await assert.rejects(()=>syncShopifyCatalogue({bigquery,project:'p',graphql,now:()=> '2026-01-01T00:00:00Z'}),/membership fetch failed/);assert.equal(calls,0)});
test('catalogue writes declare types for empty and populated repeated values',async()=>{const calls=[],bigquery=recordingBigQuery(calls);const catalogue={products:[
  {product_id:'1',title:'empty',product_type:null,vendor:null,tags:[],status:'active',created_at:null,updated_at:null},
  {product_id:'2',title:'one',product_type:'Ring',vendor:'TGF',tags:['gold'],status:'active',created_at:'2020-01-01',updated_at:'2020-01-02'},
  {product_id:'3',title:'many',product_type:'Ring',vendor:'TGF',tags:['gold','gift'],status:'draft',created_at:'2020-01-01',updated_at:'2020-01-02'}
],collections:[{collection_id:'10',title:'Collection',handle:'collection',product_count:0,updated_at:null}],memberships:[]};
  await persistShopifyCatalogue(bigquery,'p',catalogue,{now:'2026-01-01T00:00:00Z'});
  await persistShopifyCatalogue(bigquery,'p',catalogue,{now:'2026-01-01T00:00:00Z'});
  const parameterized=calls.filter(call=>call.params);
  assert.equal(parameterized.length,6);
  for(const call of parameterized)assert.ok(call.types,'every parameterized catalogue query supplies types');
  const productWrites=parameterized.filter(call=>call.query.includes('.products`'));
  assert.equal(productWrites.length,2);
  assert.deepEqual(productWrites[0].params.rows.map(row=>row.tags),[[],['gold'],['gold','gift']]);
  assert.ok(productWrites[0].params.rows.every(row=>row.catalogue_synced_at.constructor.name==='BigQueryTimestamp'));
  assert.deepEqual(productWrites[0].types,CATALOGUE_QUERY_TYPES.products);
  assert.deepEqual(productWrites[0].types.rows[0].tags,['STRING']);
  const membershipWrites=parameterized.filter(call=>call.query.includes('.product_collections`'));
  assert.equal(membershipWrites.length,2);
  assert.deepEqual(membershipWrites[0].params.rows,[]);
  assert.deepEqual(membershipWrites[0].types,CATALOGUE_QUERY_TYPES.memberships);
  assert.doesNotThrow(()=>BigQuery.valueToQueryParameter_(productWrites[0].params.rows,productWrites[0].types.rows));
  assert.doesNotThrow(()=>BigQuery.valueToQueryParameter_(membershipWrites[0].params.rows,membershipWrites[0].types.rows));
});
test('real BigQuery converter proves why validated timestamp strings became NULL inside ARRAY STRUCT',()=>{const stringRows=[{product_id:'1',catalogue_synced_at:'2026-01-01T00:00:00Z'}];validateCatalogueRows({products:stringRows,collections:[],memberships:[]});const broken=BigQuery.valueToQueryParameter_(stringRows,[{product_id:'STRING',catalogue_synced_at:'TIMESTAMP'}]);assert.equal(broken.parameterValue.arrayValues[0].structValues.catalogue_synced_at.value,undefined);const fixed=inspectSerializedRows([{product_id:'1',catalogue_synced_at:BigQuery.timestamp('2026-01-01T00:00:00Z')}],{rows:[{product_id:'STRING',catalogue_synced_at:'TIMESTAMP'}]});assert.notEqual(fixed[0].catalogue_synced_at.value,undefined)});
test('all catalogue SQL projects and assigns catalogue_synced_at explicitly on update and insert',()=>{for(const kind of ['products','collections','memberships']){const sql=catalogueMergeSql[kind]('p','d');assert.match(sql,/USING \(SELECT [^)]+catalogue_synced_at FROM UNNEST\(@rows\)\) s/);assert.match(sql,/UPDATE SET [^;]*catalogue_synced_at=s\.catalogue_synced_at/);assert.match(sql,/INSERT \([^)]+catalogue_synced_at\) VALUES \([^)]+s\.catalogue_synced_at\)/)}});
test('catalogue write failures identify the exact operation',async()=>{const calls=[];const bigquery={query:async options=>{calls.push(options);if(options.query.includes('INFORMATION_SCHEMA.COLUMNS'))return [schemaRows()];if(options.query.includes('.collections` t USING'))throw new Error('required field');return [[]]}};await assert.rejects(()=>persistShopifyCatalogue(bigquery,'p',{products:[],collections:[{collection_id:'2',title:null,handle:null,product_count:0,updated_at:null}],memberships:[]},{now:'2026-01-01T00:00:00Z'}),/^Error: shopify_catalogue_collections_merge: required field/) });
test('production write-contract validator is read-only and checks server binding for every nested struct',async()=>{const calls=[];const bigquery={query:async options=>{calls.push(options);return [options.query.includes('INFORMATION_SCHEMA.COLUMNS')?schemaRows():[{survives:true}]]}};const result=await validateShopifyCatalogueWriteContract({bigquery,project:'p'});assert.equal(result.valid,true);assert.deepEqual(Object.keys(result.binding),['products','collections','memberships']);assert.ok(calls.every(call=>/^SELECT\b/.test(call.query)));assert.equal(calls.filter(call=>call.query.includes('UNNEST(@rows)')).length,3)});
test('collection governance is explicit, normalized, auditable and rejects invalid groups',()=>{const row=validateCollectionDecision({platform:'shopify',collection_id:'10',collection_title:'Collab',classification_type:'collaboration_name',classification_value:'Artist Name'},'reviewer','2026-01-01T00:00:00Z');assert.equal(row.classification_value,'artist_name');assert.equal(row.reviewed_by,'reviewer');assert.throws(()=>validateCollectionDecision({platform:'shopify',collection_id:'10',classification_type:'collection_group',classification_value:'maybe'},'r'),/collaboration or other/)});
