import test from 'node:test';import assert from 'node:assert/strict';
import {BigQuery} from '@google-cloud/bigquery';
import {CATALOGUE_QUERY_TYPES,CATALOGUE_TABLE_SCHEMAS,catalogueMergeSql,catalogueSourceProjectionSql,catalogueTransportRows,fetchShopifyCatalogue,inspectSerializedRows,persistShopifyCatalogue,syncShopifyCatalogue,validateCatalogueRows,catalogueDdl} from '../shopify/catalogue.js';
import {metadataStructSql,quoteBigQueryIdentifier} from '../product-classifications/sync.js';
import {validateCollectionDecision} from '../oracle/collection-classification.js';
import {validateShopifyCatalogueWriteContract} from '../diagnostics/shopify-catalogue-write-contract-production.js';

const schemaRows=()=>Object.entries(CATALOGUE_TABLE_SCHEMAS).flatMap(([table_name,columns])=>Object.entries(columns).map(([column_name,[data_type,is_nullable]])=>({table_name,column_name,data_type,is_nullable})));
const recordingBigQuery=calls=>({query:async options=>{calls.push(options);return [options.query.includes('INFORMATION_SCHEMA.COLUMNS')?schemaRows():[]]}});

test('dynamic metadata SQL uses AS, commas, quoting, and supports no fields',()=>{assert.equal(metadataStructSql([]),"'{}'");assert.match(metadataStructSql(['product_type']),/TO_JSON_STRING\(`product_type`\) AS `product_type`/);const sql=metadataStructSql(['product_type','vendor','tags']);assert.match(sql,/`, TO_JSON_STRING/);assert.equal(quoteBigQueryIdentifier('odd`name'),'`odd``name`')});
test('Shopify catalogue follows product, collection, and membership pagination',async()=>{let products=0,memberships=0;const graphql=async(query,{cursor})=>{if(query.includes('CatalogueProducts')){products++;return {products:{nodes:[{id:`gid://shopify/Product/${products}`,title:'Display only',productType:'Ring',vendor:'TGF',tags:['x'],status:'ACTIVE',createdAt:'2020-01-01',updatedAt:'2020-01-02'}],pageInfo:{hasNextPage:products===1,endCursor:'p2'}}}}if(query.includes('CatalogueCollections'))return {collections:{nodes:[{id:'gid://shopify/Collection/10',title:'Human review',handle:'review',updatedAt:'2020-01-01',productsCount:{count:2}}],pageInfo:{hasNextPage:false}}};memberships++;return {collection:{products:{nodes:[{id:`gid://shopify/Product/${memberships}`}],pageInfo:{hasNextPage:memberships===1,endCursor:'m2'}}}}};const result=await fetchShopifyCatalogue(graphql);assert.equal(result.products.length,2);assert.equal(result.collections.length,1);assert.deepEqual(result.memberships,[{product_id:'1',collection_id:'10'},{product_id:'2',collection_id:'10'}]);assert.equal(result.products[0].status,'active')});
test('absent and explicit-null Shopify tags normalize to empty arrays',async()=>{let call=0;const graphql=async query=>{if(query.includes('CatalogueProducts'))return {products:{nodes:[{id:'gid://shopify/Product/1'},{id:'gid://shopify/Product/2',tags:null},{id:'gid://shopify/Product/3',tags:['gold']}],pageInfo:{hasNextPage:false}}};if(query.includes('CatalogueCollections'))return {collections:{nodes:[],pageInfo:{hasNextPage:false}}};call++;};const result=await fetchShopifyCatalogue(graphql);assert.deepEqual(result.products.map(row=>row.tags),[[],[],['gold']]);assert.equal(call,0)});
test('catalogue DDL represents repeated tags without an unsupported NOT NULL constraint',()=>{const [,products,collections,memberships]=catalogueDdl('p');assert.deepEqual(CATALOGUE_TABLE_SCHEMAS.products.tags,['ARRAY<STRING>','NO'],'repeated fields remain logically non-null in BigQuery metadata');assert.match(products,/tags ARRAY<STRING>(?:,|\))/);assert.doesNotMatch(products,/tags ARRAY<STRING> NOT NULL/);assert.match(products,/product_id STRING NOT NULL/);assert.match(products,/catalogue_synced_at TIMESTAMP NOT NULL/);assert.match(products,/created_at TIMESTAMP,/);assert.match(products,/updated_at TIMESTAMP,/);assert.doesNotMatch(products,/(?:created_at|updated_at) TIMESTAMP NOT NULL/);for(const ddl of [products,collections,memberships])assert.doesNotMatch(ddl,/ARRAY<[^>]+> NOT NULL/);assert.match(collections,/collection_id STRING NOT NULL/);assert.match(collections,/catalogue_synced_at TIMESTAMP NOT NULL/);assert.match(collections,/updated_at TIMESTAMP,/);assert.doesNotMatch(collections,/updated_at TIMESTAMP NOT NULL/);assert.match(memberships,/product_id STRING NOT NULL/);assert.match(memberships,/collection_id STRING NOT NULL/);assert.match(memberships,/catalogue_synced_at TIMESTAMP NOT NULL/)});
test('catalogue persistence uses MERGE and authoritative membership replacement',async()=>{const calls=[],bigquery=recordingBigQuery(calls);await persistShopifyCatalogue(bigquery,'p',{products:[{product_id:'1',title:'x',product_type:'Ring',vendor:'v',tags:[],status:'archived',created_at:null,updated_at:null}],collections:[{collection_id:'2',title:'c',handle:'c',product_count:1,updated_at:null}],memberships:[]},{now:'2026-01-01T00:00:00Z'});assert.ok(calls.some(x=>x.query.includes('MERGE `p.shopify_catalogue.products`')));assert.ok(calls.some(x=>x.query.includes('WHEN NOT MATCHED BY SOURCE THEN DELETE')));assert.equal(catalogueDdl('p').length,4)});
test('catalogue materializes one ISO ingestion timestamp independently of nullable Shopify timestamps',async()=>{const calls=[],bigquery=recordingBigQuery(calls);await persistShopifyCatalogue(bigquery,'p',{products:[{product_id:'1',title:'x',product_type:null,vendor:null,tags:[],status:'active',created_at:null,updated_at:null}],collections:[{collection_id:'2',title:'c',handle:'c',product_count:1,updated_at:null}],memberships:[{product_id:'1',collection_id:'2'}]},{catalogueSyncedAt:'2026-02-03T04:05:06.000Z'});const writes=calls.filter(call=>call.params);assert.equal(writes.length,3);assert.ok(writes.flatMap(call=>call.params.rows).every(row=>row.catalogue_synced_at==='2026-02-03T04:05:06.000Z'));assert.equal(writes[0].params.rows[0].created_at,null);assert.equal(writes[0].params.rows[0].updated_at,null);assert.match(writes[0].query,/INSERT \(product_id,title,product_type,vendor,tags,status,created_at,updated_at,catalogue_synced_at\)/)});
test('required catalogue fields fail locally before any BigQuery query',async()=>{const bigquery={query:async()=>assert.fail('BigQuery must not be called')};await assert.rejects(()=>persistShopifyCatalogue(bigquery,'p',{products:[{product_id:'',tags:[]}],collections:[],memberships:[]},{catalogueSyncedAt:'2026-01-01T00:00:00Z'}),/Invalid Shopify catalogue product row: product_id is required/);assert.throws(()=>validateCatalogueRows({products:[],collections:[{collection_id:'2',catalogue_synced_at:null}],memberships:[]}),/Invalid Shopify catalogue collection row: catalogue_synced_at is required/);assert.throws(()=>validateCatalogueRows({products:[],collections:[],memberships:[{product_id:'1',collection_id:'',catalogue_synced_at:'2026-01-01'}]}),/Invalid Shopify catalogue membership row: collection_id is required/)});
test('pre-write validation rejects missing, null, and invalid normalized tags',()=>{for(const tags of [undefined,null,'gold',['gold',null]]){const row={product_id:'1',catalogue_synced_at:'2026-01-01'};if(tags!==undefined)row.tags=tags;assert.throws(()=>validateCatalogueRows({products:[row],collections:[],memberships:[]}),/tags must be an array of strings/)}});
test('incomplete membership retrieval performs no writes or stale cleanup',async()=>{let calls=0;const bigquery={query:async()=>{calls++}},graphql=async query=>{if(query.includes('CatalogueProducts'))return {products:{nodes:[],pageInfo:{hasNextPage:false}}};if(query.includes('CatalogueCollections'))return {collections:{nodes:[{id:'gid://shopify/Collection/2',productsCount:{count:1}}],pageInfo:{hasNextPage:false}}};throw new Error('membership fetch failed')};await assert.rejects(()=>syncShopifyCatalogue({bigquery,project:'p',graphql,now:()=> '2026-01-01T00:00:00Z'}),/membership fetch failed/);assert.equal(calls,0)});
test('catalogue writes serialize validated tags as JSON strings and remain idempotent',async()=>{const calls=[],bigquery=recordingBigQuery(calls);const catalogue={products:[
  {product_id:'1',title:'empty',product_type:null,vendor:null,tags:[],status:'active',created_at:null,updated_at:null},
  {product_id:'2',title:'one',product_type:'Ring',vendor:'TGF',tags:['gold'],status:'active',created_at:'2020-01-01',updated_at:'2020-01-02'},
  {product_id:'3',title:'many',product_type:'Ring',vendor:'TGF',tags:['gold','gift'],status:'draft',created_at:'2020-01-01',updated_at:'2020-01-02'}
],collections:[{collection_id:'10',title:'Collection',handle:'collection',product_count:0,updated_at:null}],memberships:[]};
  await persistShopifyCatalogue(bigquery,'p',catalogue,{now:'2026-01-01T00:00:00Z'});
  await persistShopifyCatalogue(bigquery,'p',catalogue,{now:'2026-01-01T00:00:00Z'});
  const parameterized=calls.filter(call=>call.params);
  assert.equal(parameterized.length,6);
  for(const call of parameterized)assert.ok(call.types,'every parameterized catalogue query supplies types');
  const productWrites=parameterized.filter(call=>call.query.includes('.products`'));
  assert.equal(productWrites.length,2);
  assert.deepEqual(productWrites[0].params.rows.map(row=>row.tags_json),['[]','["gold"]','["gold","gift"]']);
  assert.ok(productWrites[0].params.rows.every(row=>typeof row.catalogue_synced_at==='string'));
  assert.deepEqual(productWrites[0].types,CATALOGUE_QUERY_TYPES.products);
  assert.equal(productWrites[0].types.rows[0].tags_json,'STRING');
  assert.equal(inspectSerializedRows([productWrites[0].params.rows[0]],CATALOGUE_QUERY_TYPES.products)[0].tags_json.value,'[]');
  const membershipWrites=parameterized.filter(call=>call.query.includes('.product_collections`'));
  assert.equal(membershipWrites.length,2);
  assert.deepEqual(membershipWrites[0].params.rows,[]);
  assert.deepEqual(membershipWrites[0].types,CATALOGUE_QUERY_TYPES.memberships);
  assert.doesNotThrow(()=>BigQuery.valueToQueryParameter_(productWrites[0].params.rows,productWrites[0].types.rows));
  assert.doesNotThrow(()=>BigQuery.valueToQueryParameter_(membershipWrites[0].params.rows,membershipWrites[0].types.rows));
});
test('tag JSON transport round-trips empty, one, punctuation, quotes, and Unicode values',()=>{const tagsCases=[[],['one'],['one','comma, tag','quote " tag',"apostrophe's tag",'Café & 東京']];const transported=catalogueTransportRows({products:tagsCases.map((tags,index)=>({product_id:String(index),tags})),collections:[],memberships:[]});assert.deepEqual(transported.products.map(row=>JSON.parse(row.tags_json)),tagsCases);assert.ok(transported.products.every(row=>!('tags' in row)));assert.ok(transported.products.every(row=>typeof row.tags_json==='string'))});
test('nested catalogue timestamps use STRING parameters and survive the real converter',()=>{for(const kind of ['products','collections','memberships'])assert.equal(CATALOGUE_QUERY_TYPES[kind].rows[0].catalogue_synced_at,'STRING');assert.equal(CATALOGUE_QUERY_TYPES.products.rows[0].created_at,'STRING');assert.equal(CATALOGUE_QUERY_TYPES.products.rows[0].updated_at,'STRING');assert.equal(CATALOGUE_QUERY_TYPES.collections.rows[0].updated_at,'STRING');const fixed=inspectSerializedRows([{product_id:'1',catalogue_synced_at:'2026-01-01T00:00:00.000Z'}],{rows:[{product_id:'STRING',catalogue_synced_at:'STRING'}]});assert.equal(fixed[0].catalogue_synced_at.value,'2026-01-01T00:00:00.000Z')});
test('all catalogue SQL shares tag reconstruction and explicit safe timestamp projections',()=>{for(const kind of ['products','collections','memberships']){const projection=catalogueSourceProjectionSql(kind);const sql=catalogueMergeSql[kind]('p','d');assert.ok(sql.includes(`USING (${projection}) s`));assert.match(projection,/TIMESTAMP\(catalogue_synced_at\) AS catalogue_synced_at/);assert.match(sql,/UPDATE SET [^;]*catalogue_synced_at=s\.catalogue_synced_at/);assert.match(sql,/INSERT \([^)]+catalogue_synced_at\) VALUES \([^)]+s\.catalogue_synced_at\)/)}const products=catalogueSourceProjectionSql('products');assert.match(products,/COALESCE\(JSON_VALUE_ARRAY\(tags_json\),ARRAY<STRING>\[\]\) AS tags/);assert.match(products,/SAFE_CAST\(created_at AS TIMESTAMP\).*SAFE_CAST\(updated_at AS TIMESTAMP\)/);assert.match(catalogueSourceProjectionSql('collections'),/SAFE_CAST\(updated_at AS TIMESTAMP\)/)});
test('catalogue write failures identify the exact operation',async()=>{const calls=[];const bigquery={query:async options=>{calls.push(options);if(options.query.includes('INFORMATION_SCHEMA.COLUMNS'))return [schemaRows()];if(options.query.includes('.collections` t USING'))throw new Error('required field');return [[]]}};await assert.rejects(()=>persistShopifyCatalogue(bigquery,'p',{products:[],collections:[{collection_id:'2',title:null,handle:null,product_count:0,updated_at:null}],memberships:[]},{now:'2026-01-01T00:00:00Z'}),/^Error: shopify_catalogue_collections_merge: required field/) });
test('production write-contract validator is read-only and tests empty and populated tags through production projections',async()=>{const calls=[];const bigquery={query:async options=>{calls.push(options);if(options.query.includes('INFORMATION_SCHEMA.COLUMNS'))return [schemaRows()];const row=Object.fromEntries([...options.query.matchAll(/ AS ([a-z_]+)/g)].map(match=>[match[1],true]));return [[row]]}};const result=await validateShopifyCatalogueWriteContract({bigquery,project:'p'});assert.equal(result.valid,true);assert.deepEqual(Object.keys(result.binding),['products','collections','memberships']);assert.ok(calls.every(call=>!/^\s*(MERGE|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER)\b/i.test(call.query)));assert.equal(calls.filter(call=>call.query.includes('UNNEST(@rows)')).length,3);const productCall=calls.find(call=>call.query.includes("contract-product-empty-tags"));assert.deepEqual(productCall.params.rows.map(row=>JSON.parse(row.tags_json)),[[],['Collaboration','Ready, "Set"','Café & 東京']]);assert.match(productCall.query,/tags IS NOT NULL AND ARRAY_LENGTH\(tags\)=0/);assert.match(productCall.query,/ARRAY_LENGTH\(tags\)=3/);for(const kind of ['products','collections','memberships']){assert.equal(result.binding[kind].parameter_type,'STRING');assert.equal(result.binding[kind].target_type,'TIMESTAMP');assert.ok(calls.some(call=>call.query.includes(catalogueSourceProjectionSql(kind,'bound'))))}});
test('write-contract validation skips DDL while catalogue persistence executes CREATE TABLE IF NOT EXISTS',async()=>{const validationCalls=[];const validatingBigQuery={query:async options=>{validationCalls.push(options);if(options.query.includes('INFORMATION_SCHEMA.COLUMNS'))return [schemaRows()];const row=Object.fromEntries([...options.query.matchAll(/ AS ([a-z_]+)/g)].map(match=>[match[1],true]));return [[row]]}};await validateShopifyCatalogueWriteContract({bigquery:validatingBigQuery,project:'p'});assert.equal(validationCalls.some(call=>/^CREATE TABLE IF NOT EXISTS/.test(call.query)),false);const syncCalls=[],syncBigQuery=recordingBigQuery(syncCalls);await persistShopifyCatalogue(syncBigQuery,'p',{products:[],collections:[],memberships:[]},{now:'2026-01-01T00:00:00Z'});assert.deepEqual(syncCalls.slice(0,4).map(call=>call.query),catalogueDdl('p'));assert.equal(syncCalls.filter(call=>/^CREATE TABLE IF NOT EXISTS/.test(call.query)).length,3)});
test('collection governance is explicit, normalized, auditable and rejects invalid groups',()=>{const row=validateCollectionDecision({platform:'shopify',collection_id:'10',collection_title:'Collab',classification_type:'collaboration_name',classification_value:'Artist Name'},'reviewer','2026-01-01T00:00:00Z');assert.equal(row.classification_value,'artist_name');assert.equal(row.reviewed_by,'reviewer');assert.throws(()=>validateCollectionDecision({platform:'shopify',collection_id:'10',classification_type:'collection_group',classification_value:'maybe'},'r'),/collaboration or other/)});
