import test from 'node:test';
import assert from 'node:assert/strict';
import { aggregateJourneyEvents, createCustomerJourneyService, customerJourneySql, CUSTOMER_JOURNEY_TOOL_DEFINITION, executeCustomerJourneyToolCall, validateJourneyDefinition } from '../oracle/customer-journey.js';
import { productClassificationDdl, validateProductClassification } from '../oracle/product-classification.js';
import { transitionAnalysisContext } from '../oracle/analysis-context.js';

const line=(customer_ref,order_ref,timestamp,product_title,extra={})=>({customer_ref,order_ref,timestamp,source:'woo:ww',product_ref:product_title.toLowerCase(),product_title,units:1,currency:'GBP',net_sales:10,classifications:[],...extra});
test('journey definition is bounded, serializable, and rejects arbitrary SQL-shaped fields',()=>{const d=validateJourneyDefinition({start_date:'2023-01-01',end_date:'2026-09-15',cohort:{entry_product_classification:'collaboration'},subsequent:{within_days:90},metrics:['cohort_customers'],group_by:['downstream_product'],sort:'returning_customers_desc',limit:10});assert.equal(d.cohort.entry_sequence,'first_observed_order');assert.equal(d.subsequent.minimum_order_sequence,2);assert.equal(JSON.parse(JSON.stringify(d)).subsequent.within_days,90);assert.throws(()=>validateJourneyDefinition({...d,sql:'SELECT *'}),/invalid journey field/)});
test('first observed order has a deterministic timestamp/source/order tie-break and nth order works',()=>{const events=[line('a','2','2024-01-01T00:00:00Z','Later tie',{source:'woo:ww',classifications:['collaboration']}),line('a','1','2024-01-01T00:00:00Z','Entry',{source:'shopify:shopify',classifications:['collaboration']}),line('a','3','2024-01-03T00:00:00Z','Third')];const all=aggregateJourneyEvents(events,{start_date:'2024-01-01',end_date:'2024-12-31',entryClassification:'collaboration'});assert.equal(all.downstream_orders,2);const third=aggregateJourneyEvents(events,{start_date:'2024-01-01',end_date:'2024-12-31',entryClassification:'collaboration',minimumSequence:3,maximumSequence:3});assert.equal(third.products[0].product,'Third')});
test('multi-product entry qualifies while original order is excluded downstream',()=>{const events=[line('a','1','2024-01-01T00:00:00Z','Collab',{classifications:['collaboration']}),line('a','1','2024-01-01T00:00:00Z','Plain'),line('a','2','2024-02-01T00:00:00Z','Ring')];const r=aggregateJourneyEvents(events,{start_date:'2024-01-01',end_date:'2024-12-31',entryClassification:'collaboration'});assert.equal(r.cohort_customers,1);assert.deepEqual(r.products.map(x=>x.product),['Ring'])});
test('repeat definition, 30/60/90 windows, ranking, distinct counts, units and separated currencies',()=>{const events=[line('a','1','2024-01-01T00:00:00Z','Entry',{classifications:['collaboration']}),line('a','2','2024-01-31T00:00:00Z','Ring',{units:2,net_sales:20}),line('a','3','2024-03-01T00:00:00Z','Chain',{currency:'USD'}),line('b','4','2024-01-01T00:00:00Z','Entry',{classifications:['collaboration']}),line('b','5','2024-03-31T00:00:00Z','Ring',{currency:'USD',net_sales:30}),line(null,'guest','2024-01-01T00:00:00Z','Entry',{classifications:['collaboration']})];assert.equal(aggregateJourneyEvents(events,{start_date:'2024-01-01',end_date:'2024-12-31',entryClassification:'collaboration',withinDays:30}).returning_customers,1);assert.equal(aggregateJourneyEvents(events,{start_date:'2024-01-01',end_date:'2024-12-31',entryClassification:'collaboration',withinDays:60}).downstream_orders,2);const r=aggregateJourneyEvents(events,{start_date:'2024-01-01',end_date:'2024-12-31',entryClassification:'collaboration',withinDays:90});assert.equal(r.cohort_customers,2);assert.equal(r.returning_customers,2);assert.equal(r.products[0].product,'Ring');assert.equal(r.products[0].returning_customers,2);assert.equal(r.products[0].units,3);assert.deepEqual(r.products[0].net_sales_by_currency,[{currency:'GBP',net_sales:20},{currency:'USD',net_sales:30}])});
test('SQL governs source identities, migration, Square limitation, finance isolation, mappings and classifications',()=>{const sql=customerJourneySql('p');assert.match(sql,/ROW_NUMBER\(\) OVER\(PARTITION BY governed_customer_ref ORDER BY order_timestamp,source_platform,source_store,order_ref\)/);assert.match(sql,/source_customer_id NOT IN \('','0'\)/);assert.match(sql,/source_app_id=@matrixify_app_id/);assert.doesNotMatch(sql,/square_data/);assert.match(sql,/map_active/);assert.match(sql,/status='approved'/);assert.match(sql,/product_classifications/);assert.doesNotMatch(sql,/suggested|similarity|canonical.finance|accountant_transactions/i);assert.match(sql,/r\.order_timestamp>c\.entry_timestamp/);assert.match(sql,/TIMESTAMP_DIFF/)});
test('classification records require governed provenance and source product grain',()=>{const row={classification_id:'pc_12345678',subject_ref:'woo:ww:42',subject_grain:'source_product',classification_type:'product_group',classification_value:'collaboration',provenance:'business_governed',confidence:'high',status:'active',recorded_at:'2026-01-01T00:00:00Z',recorded_by:'admin'};assert.equal(validateProductClassification(row).classification_value,'collaboration');assert.throws(()=>validateProductClassification({...row,provenance:'title_guess'}),/provenance/);assert.match(productClassificationDdl('p'),/CLUSTER BY classification_type,classification_value,status/)});
test('tool is aggregate, parameterized, PII-free and routed',async()=>{const calls=[];const service=createCustomerJourneyService({project:'p',bigquery:{query:async job=>{calls.push(job);return [[{product:'Ring',cohort_customers:2,returning_customers:1,repeat_rate_percentage:50}]]}}});const args={start_date:'2024-01-01',end_date:'2024-12-31',cohort:{entry_product_classification:'ring'},subsequent:{},group_by:['downstream_product'],sort:'returning_customers_desc',limit:5};const call=await executeCustomerJourneyToolCall(service,'analyze_customer_journey',args);assert.equal(call.handled,true);assert.equal(call.result.cohort.customers,2);assert.ok(calls[0].params);assert.equal(calls[0].labels.component,'customer_journey');const fields=Object.keys(CUSTOMER_JOURNEY_TOOL_DEFINITION.parameters.properties).join(' ');assert.doesNotMatch(fields,/email|phone|address|customer_ref|customer_id/i)});
test('conversation retains journey intent across date and sequence/window follow-ups',()=>{let x=transitionAnalysisContext(null,'what do customers buy after their first collaboration product?').context;assert.equal(x.analysis_type,'customer_journey');assert.equal(x.entry_product_classification,'collaboration');assert.deepEqual(x.unresolved_required_fields,['start_date','end_date']);x=transitionAnalysisContext(x,'01/01/2023 - 15/09/2026').context;assert.equal(x.start_date,'2023-01-01');assert.equal(x.entry_product_classification,'collaboration');x=transitionAnalysisContext(x,'what do those customers buy on their second order specifically?').context;assert.equal(x.minimum_order_sequence,2);assert.equal(x.maximum_order_sequence,2);x=transitionAnalysisContext(x,'within 90 days').context;assert.equal(x.within_days,90);assert.equal(x.journey_group_by,'downstream_product')});
