import test from 'node:test';
import assert from 'node:assert/strict';
import {createKlaviyoClient,redactKlaviyo} from '../klaviyo/client.js';
import {metricCatalogue,reportBody} from '../klaviyo/discovery.js';
import {requireGate,normalizeReport} from '../klaviyo/sync.js';
import {classifyKlaviyoQuestion,KLAVIYO_TOOL_DEFINITIONS,createKlaviyoEmailService} from '../oracle/klaviyo-email.js';

const response=(body,status=200,headers={get:()=>null})=>({ok:status<300,status,headers,json:async()=>body});
test('pagination follows next links and enforces its bound',async()=>{let n=0;const fetchImpl=async()=>response(n++?{data:[],links:{next:null}}:{data:[{id:'one'}],links:{next:'/api/metrics?page=2'}}),client=createKlaviyoClient({apiKey:'pk_secretsecret',revision:'2026-01-15',fetchImpl,sleep:async()=>{}});assert.equal((await client.paginate('/api/metrics')).pages,2);n=0;await assert.rejects(client.paginate('/api/metrics',{maxPages:1}),/pagination bound/);});
test('429 retries are bounded and credentials are redacted',async()=>{let calls=0;const client=createKlaviyoClient({apiKey:'pk_secretsecret',revision:'2026-01-15',fetchImpl:async()=>{calls++;return response({},429)},maxRetries:2,sleep:async()=>{}});await assert.rejects(client.request('/api/metrics'),/HTTP 429/);assert.equal(calls,3);assert.equal(redactKlaviyo('Authorization: Klaviyo-API-Key pk_secretsecret'),'Authorization: Klaviyo-API-Key [REDACTED]');});
test('metric provenance distinguishes integrations and report requires account settings',()=>{assert.deepEqual(metricCatalogue([{id:'s',attributes:{name:'Placed Order',integration:{name:'Shopify'}}},{id:'w',attributes:{name:'Placed Order - WooCommerce'}}]).map(x=>x.integration),['shopify','woocommerce']);assert.throws(()=>reportBody('campaign','s',{}),/timezone/);});
test('production gate blocks collection until explicit matching approval',()=>{const manifest={gate_version:1,approved_for_pilot:true,timezone:'Europe/London',currency:'GBP',attribution_settings:'dashboard recorded',probes:[{metric_id:'s',status:'available'}]};assert.equal(requireGate(manifest,{timezone:'Europe/London',currency:'GBP',metricIds:['s']}),true);assert.throws(()=>requireGate({...manifest,approved_for_pilot:false},{timezone:'Europe/London',currency:'GBP',metricIds:['s']}),/blocked/);assert.throws(()=>requireGate(manifest,{timezone:'Europe/London',currency:'USD',metricIds:['s']}),/do not match/);});
test('normalization preserves period semantics, currencies, and separate metric IDs',()=>{const payload={data:{attributes:{results:[{id:'c1',statistics:{delivered:10,clicks_unique:4,conversions:1,conversion_value:12}}]}}};const row=normalizeReport(payload,{kind:'campaign',metricId:'shopify-id',currency:'GBP',timezone:'Europe/London',revision:'2026-01-15',retrievedAt:'2026-09-02T00:00:00Z'})[0];assert.equal(row.currency,'GBP');assert.equal(row.conversion_metric_id,'shopify-id');assert.match(row.report_period_semantics,/not asserted/);});
test('exact Oracle routes cover all requested questions',()=>{assert.equal(classifyKlaviyoQuestion('How did email campaigns and automated flows perform in August 2026?'),'get_klaviyo_email_performance');assert.equal(classifyKlaviyoQuestion('Which campaigns had strong clicks but weak attributed purchases?'),'get_klaviyo_click_purchase_opportunities');assert.equal(classifyKlaviyoQuestion('Compare Klaviyo with Shopify email-referrer traffic'),'compare_klaviyo_email_with_shopify_referrer');assert.equal(KLAVIYO_TOOL_DEFINITIONS.length,3);});
test('Oracle retrieval failure remains an error and never fallback zero figures',async()=>{const service=createKlaviyoEmailService({project:'p',bigquery:{query:async()=>{throw new Error('missing')},getDatasets:async()=>[]}});await assert.rejects(service('get_klaviyo_email_performance',{start_date:'2026-08-01',end_date:'2026-08-31'}),e=>e.code==='KLAVIYO_RETRIEVAL_FAILED'&&!/zero performance$/.test(e.message));});
