import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { createOracleUiRouter } from '../oracle/ui-router.js';
import { proposeFromMessage } from '../oracle/proposals.js';
import { redactError } from '../oracle/ui-security.js';

const env={ORACLE_UI_PASSWORD:'test-password',ORACLE_UI_SESSION_SECRET:'12345678901234567890123456789012',ORACLE_UI_ADMIN_NAME:'test-admin'};
async function fixture(){
  const writes=[];
  const bigquery={dataset:()=>({table:()=>({insert:async rows=>writes.push(...rows)})}),query:async()=>[[]]};
  const browse=[];const knowledgeService={searchKnowledge:async input=>{browse.push({tool:'knowledge',input});return {items:[{id:'ev_existing',title:'Black Friday 2025',content:'Existing governed event',status:'confirmed'}],input}},getKnowledgeItem:async()=>({found:false,item:null}),searchMemory:async input=>{browse.push({tool:'memory',input});return {items:[],input}},getMemoryItem:async()=>({found:false,item:null})};
  const app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService,bigquery,project:'test',chat:async message=>({answer:`answer:${message}`,tools:['search_knowledge']}),env}));
  const server=await new Promise(resolve=>{const value=app.listen(0,()=>resolve(value))});const base=`http://127.0.0.1:${server.address().port}/api/oracle`;
  const request=(path,options={})=>fetch(base+path,options);return {server,request,writes,browse,base};
}
async function login(request,base){const response=await request('/auth/login',{method:'POST',headers:{'content-type':'application/json',origin:new URL(base).origin},body:JSON.stringify({password:env.ORACLE_UI_PASSWORD})});const data=await response.json();const cookie=response.headers.getSetCookie().map(value=>value.split(';')[0]).join('; ');return {cookie,csrf:data.csrf};}
test('proposal creation is non-persistent, parses dates, and uncertainty stays working',()=>{const confirmed=proposeFromMessage('Remember that the campaign ran from 28 November 2024 to 1 December 2024.');assert.equal(confirmed.kind,'event');assert.equal(confirmed.proposal.effective_from,'2024-11-28');assert.equal(confirmed.proposal.effective_to,'2024-12-01');assert.equal(confirmed.persisted,false);const uncertain=proposeFromMessage('I think the campaign started 28 November 2024 but I am not certain.');assert.equal(uncertain.proposal.status,'working')});
test('definitions and human assertions are schema validated without treating tools as proposal evidence',()=>{assert.equal(proposeFromMessage('Remember that Net sales means sales after discounts.').kind,'definition');const memory=proposeFromMessage('Remember this finding: conversion improved.',{tools:['finance','ga4']});assert.equal(memory.kind,'memory');assert.equal(memory.proposal.status,'working');assert.equal(memory.proposal.source_type,'human_entered');assert.equal(memory.proposal.evidence.length,1);assert.equal(memory.proposal.memory_type,'hypothesis')});
test('redacts Google bearer tokens and credential-shaped fields',()=>{const output=redactError({headers:{authorization:'Bearer ya29.secret-token'},private_key:'abc'});assert.doesNotMatch(output,/ya29|abc/);assert.match(output,/REDACTED/)});
test('UI APIs require a session, CSRF and same origin while chat reuses injected agent',async t=>{const f=await fixture();t.after(()=>f.server.close());assert.equal((await f.request('/knowledge')).status,401);assert.equal((await f.request('/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:'{"password":"test-password"}'})).status,403);const auth=await login(f.request,f.base);const headers={cookie:auth.cookie,origin:new URL(f.base).origin,'content-type':'application/json','x-csrf-token':auth.csrf};assert.equal((await f.request('/chat',{method:'POST',headers:{...headers,'x-csrf-token':'bad'},body:'{"message":"hello"}'})).status,403);const response=await f.request('/chat',{method:'POST',headers,body:'{"message":"hello"}'});assert.equal(response.status,200);assert.equal((await response.json()).answer,'answer:hello');assert.equal(f.writes.length,0)});
test('explicit approval writes only a whitelisted validated schema',async t=>{const f=await fixture();t.after(()=>f.server.close());const auth=await login(f.request,f.base);const headers={cookie:auth.cookie,origin:new URL(f.base).origin,'content-type':'application/json','x-csrf-token':auth.csrf};const bad=await f.request('/knowledge/approve',{method:'POST',headers,body:JSON.stringify({kind:'arbitrary_table',proposal:{}})});assert.equal(bad.status,400);const proposal=proposeFromMessage('Remember that the site launched on 2026-01-02.');const saved=await f.request('/knowledge/approve',{method:'POST',headers,body:JSON.stringify({kind:proposal.kind,proposal:proposal.proposal})});assert.equal(saved.status,201);assert.equal(f.writes.length,1)});
test('UI knowledge and memory browsing normalize absent filters as inactive',async t=>{const f=await fixture();t.after(()=>f.server.close());const auth=await login(f.request,f.base);const headers={cookie:auth.cookie};assert.equal((await f.request('/knowledge',{headers})).status,200);assert.equal((await f.request('/memory',{headers})).status,200);assert.deepEqual(f.browse,[{tool:'knowledge',input:{text:null,start_date:null,end_date:null,status:null,tags:[],limit:20,knowledge_type:null}},{tool:'memory',input:{text:null,start_date:null,end_date:null,status:null,tags:[],limit:20,memory_type:null}}])});

test('information, definition, analysis and comparison questions never propose',()=>{
  for(const message of ['What do you know about Black Friday 2025?','When was the Black Friday 2025 campaign?','Compare Black Friday 2024 and 2025.','Why did November sales increase?','What is our definition of repeat customer?','Did the stores participate in Black Friday?']) assert.equal(proposeFromMessage(message),null,message);
});
test('declarative and explicit persistence assertions propose without persisting',()=>{
  for(const message of ['Remember that the stores were using Square.','Save this as business knowledge: Our Shopify site launched on 5 September 2025.','The stores were still using Square during Black Friday 2025.','Black Friday 2024 ran from 8 to 10 November 2024 and offered 20% off silver.']) {const result=proposeFromMessage(message);assert.ok(result,message);assert.equal(result.persisted,false);assert.equal(result.approval_required,true);}
});
test('mixed input extracts only durable assertion and produces a concise title',()=>{
  const result=proposeFromMessage('Black Friday 2024 ran 8–10 November 2024. How did sales compare with 2025?');
  assert.equal(result.proposal.description,'Black Friday 2024 ran 8–10 November 2024.');assert.doesNotMatch(result.proposal.title,/how|\?/i);assert.equal(result.proposal.effective_from,'2024-11-08');assert.equal(result.proposal.effective_to,'2024-11-10');
});
test('equivalent governed knowledge suppresses a proposal and deterministic title match supersedes',()=>{
  const message='Our Shopify site launched on 5 September 2025.';const first=proposeFromMessage(message);assert.equal(proposeFromMessage(message,{existing:[{status:'confirmed',content:first.proposal.description}]}),null);
  const updated=proposeFromMessage(message,{existing:[{id:'ev_1234567890abcdef',status:'confirmed',title:first.proposal.title,content:'An older description'}]});assert.equal(updated.proposal.supersedes,'ev_1234567890abcdef');
});
test('retrieved answer text and tool references cannot independently become proposals',()=>{assert.equal(proposeFromMessage('What was the campaign?',{tools:['search_knowledge'],existing:[{content:'The campaign ran in November.'}]}),null);const finding=proposeFromMessage('Remember this finding: conversion increased.',{tools:['search_knowledge']});assert.equal(finding.proposal.status,'working');assert.equal(finding.proposal.source_type,'human_entered');});
