import test from 'node:test';
import assert from 'node:assert/strict';
import { renderMarkdown } from '../public/oracle/markdown.js';
class Node { constructor(tag=null,text=''){this.tag=tag;this.children=[];this.value=text;this.attrs={};} append(...nodes){this.children.push(...nodes);} set textContent(value){this.children=[];this.value=String(value);} get textContent(){return this.value+this.children.map(x=>x.textContent).join('');} set className(v){this.attrs.class=v;} set href(v){this.attrs.href=v;} set rel(v){this.attrs.rel=v;} set target(v){this.attrs.target=v;} html(){if(!this.tag)return esc(this.value);const attrs=Object.entries(this.attrs).map(([k,v])=>` ${k}="${esc(v)}"`).join('');return `<${this.tag}${attrs}>${esc(this.value)}${this.children.map(x=>x.html()).join('')}</${this.tag}>`;}}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
globalThis.document={baseURI:'https://oracle.example/',createElement:tag=>new Node(tag),createTextNode:text=>new Node(null,text)};
const render=value=>{const target=new Node('section');renderMarkdown(target,value);return target.html();};
test('Markdown renderer supports formatting, lists, tables, code and entities',()=>{const html=render('# Heading\n\n\\*\\*Bold\\*\\* and *italics*&#x20;`inline`\n\n- one\n- two\n\n1. first\n2. second\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\n```js\nalert(1)\n```');for(const tag of ['<h1>','<strong>Bold</strong>','<em>italics</em>','<ul>','<ol>','<table>','<code>inline</code>','<pre>'])assert.match(html,new RegExp(tag.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(html,/&#x20;/);});
test('Markdown renderer treats HTML as text and rejects executable link schemes',()=>{const html=render('<script>alert(1)</script>\n\n<img src=x onerror=alert(1)>\n\n[bad](javascript:alert(1)) [good](https://example.com)');assert.doesNotMatch(html,/<script|<img|javascript:/i);assert.match(html,/&lt;script&gt;/);assert.match(html,/href="https:\/\/example.com\/?"/);});
