import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { createOracleUiRouter } from '../oracle/ui-router.js';
import { proposeFromMessage } from '../oracle/proposals.js';
import { redactError } from '../oracle/ui-security.js';

const env={ORACLE_UI_PASSWORD:'test-password',ORACLE_UI_SESSION_SECRET:'12345678901234567890123456789012',ORACLE_UI_ADMIN_NAME:'test-admin'};
async function fixture(){
  const writes=[];
  const bigquery={dataset:()=>({table:()=>({insert:async rows=>writes.push(...rows)})}),query:async()=>[[]]};
  const knowledgeService={searchKnowledge:async input=>({items:[{id:'ev_existing',title:'Black Friday 2025',content:'Existing governed event',status:'confirmed'}],input}),getKnowledgeItem:async()=>({found:false,item:null}),searchMemory:async()=>({items:[]}),getMemoryItem:async()=>({found:false,item:null})};
  const app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService,bigquery,project:'test',chat:async message=>({answer:`answer:${message}`,tools:['search_knowledge']}),env}));
  const server=await new Promise(resolve=>{const value=app.listen(0,()=>resolve(value))});const base=`http://127.0.0.1:${server.address().port}/api/oracle`;
  const request=(path,options={})=>fetch(base+path,options);return {server,request,writes,base};
}
async function login(request,base){const response=await request('/auth/login',{method:'POST',headers:{'content-type':'application/json',origin:new URL(base).origin},body:JSON.stringify({password:env.ORACLE_UI_PASSWORD})});const data=await response.json();const cookie=response.headers.getSetCookie().map(value=>value.split(';')[0]).join('; ');return {cookie,csrf:data.csrf};}
test('proposal creation is non-persistent, parses dates, and uncertainty stays working',()=>{const confirmed=proposeFromMessage('Remember that the campaign ran from 28 November 2024 to 1 December 2024.');assert.equal(confirmed.kind,'event');assert.equal(confirmed.proposal.effective_from,'2024-11-28');assert.equal(confirmed.proposal.effective_to,'2024-12-01');assert.equal(confirmed.persisted,false);const uncertain=proposeFromMessage('I think the campaign started 28 November 2024 but I am not certain.');assert.equal(uncertain.proposal.status,'working')});
test('definitions and evidence-backed memory are schema validated',()=>{assert.equal(proposeFromMessage('Remember that Net sales means sales after discounts.').kind,'definition');const memory=proposeFromMessage('Remember this finding: conversion improved.',{tools:['finance','ga4']});assert.equal(memory.kind,'memory');assert.equal(memory.proposal.status,'confirmed');assert.equal(memory.proposal.evidence.length,2);const weak=proposeFromMessage('Remember this finding: conversion improved.');assert.equal(weak.proposal.status,'working');assert.equal(weak.proposal.memory_type,'hypothesis')});
test('redacts Google bearer tokens and credential-shaped fields',()=>{const output=redactError({headers:{authorization:'Bearer ya29.secret-token'},private_key:'abc'});assert.doesNotMatch(output,/ya29|abc/);assert.match(output,/REDACTED/)});
test('UI APIs require a session, CSRF and same origin while chat reuses injected agent',async t=>{const f=await fixture();t.after(()=>f.server.close());assert.equal((await f.request('/knowledge')).status,401);assert.equal((await f.request('/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:'{"password":"test-password"}'})).status,403);const auth=await login(f.request,f.base);const headers={cookie:auth.cookie,origin:new URL(f.base).origin,'content-type':'application/json','x-csrf-token':auth.csrf};assert.equal((await f.request('/chat',{method:'POST',headers:{...headers,'x-csrf-token':'bad'},body:'{"message":"hello"}'})).status,403);const response=await f.request('/chat',{method:'POST',headers,body:'{"message":"hello"}'});assert.equal(response.status,200);assert.equal((await response.json()).answer,'answer:hello');assert.equal(f.writes.length,0)});
test('explicit approval writes only a whitelisted validated schema',async t=>{const f=await fixture();t.after(()=>f.server.close());const auth=await login(f.request,f.base);const headers={cookie:auth.cookie,origin:new URL(f.base).origin,'content-type':'application/json','x-csrf-token':auth.csrf};const bad=await f.request('/knowledge/approve',{method:'POST',headers,body:JSON.stringify({kind:'arbitrary_table',proposal:{}})});assert.equal(bad.status,400);const proposal=proposeFromMessage('Remember that the site launched on 2026-01-02.');const saved=await f.request('/knowledge/approve',{method:'POST',headers,body:JSON.stringify({kind:proposal.kind,proposal:proposal.proposal})});assert.equal(saved.status,201);assert.equal(f.writes.length,1)});
