import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {readFile} from 'node:fs/promises';
import {createBaselineOverviewService,isBaselineOverviewRequest} from '../oracle/baseline-overview.js';
import {createOracleUiRouter} from '../oracle/ui-router.js';

const PROMPT='Can you give me an overview of current baseline KPIs';
const NOW=new Date('2026-10-02T12:00:00.000Z');
function fixture(overrides={}){const calls=[];const record=(name,value)=>async(...args)=>{calls.push([name,args]);if(value instanceof Error)throw value;return structuredClone(value)};const service=createBaselineOverviewService({now:()=>NOW,finance:record('finance',{net_ex_tax:900,net_gross:1080}),shopifyConversion:record('conversion',{metrics:{sessions:100,sessions_that_completed_checkout:4,conversion_rate:.04}}),shopifySales:record('sales',{metrics:{orders:5,average_order_value:216}}),shopifyDevice:record('device',{rows:[{device_type:'mobile',sessions:60,numerator:3},{device_type:'desktop',sessions:40,numerator:1}]}),klaviyo:record('klaviyo',{rows:[{report_kind:'campaign',delivered:80,unique_clicks:8,attributed_conversion_events:2,attributed_conversion_value:40,currency:'GBP'},{report_kind:'flow',delivered:20,unique_clicks:3,attributed_conversion_events:1,attributed_conversion_value:25,currency:'GBP'}],coverage:{windows:[{attribution_provisional:true}]}}),...overrides});return{service,calls}}

test('exact baseline prompt has a governed route and never selects inventory',async()=>{const{service,calls}=fixture();assert.equal(isBaselineOverviewRequest(PROMPT),true);const result=await service(PROMPT);assert.deepEqual(result.attempted_tools,['get_sales_summary','get_shopify_conversion_kpis','get_shopify_sales_kpis','get_shopify_device_conversion_by_traffic_source','get_klaviyo_email_performance']);assert.doesNotMatch(JSON.stringify(calls),/inventory/i);assert.match(result.answer,/Finance — 2026-09-03 to 2026-10-02/);assert.match(result.answer,/Klaviyo — 2026-09-01 to 2026-09-30/);assert.match(result.answer,/Campaigns.*Flows/s);assert.match(result.answer,/provisional/);assert.match(result.answer,/reconciliation remains unresolved/);assert.match(result.answer,/no governed collected paid-advertising evidence/)});

test('optional source failure retains successful independent sections and never substitutes zero',async()=>{const error=Object.assign(new Error('upstream secret'),{code:'THROTTLED'}),{service}=fixture({shopifyDevice:async()=>{throw error}});const result=await service(PROMPT);assert.match(result.answer,/Net sales excluding recorded tax.*GBP 900/);assert.match(result.answer,/Sessions.*100/);assert.match(result.answer,/Device breakdown.*unavailable \(THROTTLED\).*not zero/);assert.match(result.answer,/Missing sections:.*device/);assert.doesNotMatch(result.answer,/upstream secret/);assert.ok(!result.tools.includes('get_shopify_device_conversion_by_traffic_source'))});

test('interactive Oracle server path executes baseline route instead of model chat',async t=>{let chats=0;const{service}=fixture();const env={ORACLE_UI_PASSWORD:'pw',ORACLE_UI_SESSION_SECRET:'01234567890123456789012345678901'};const app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService:{},bigquery:{},project:'p',baselineOverview:service,chat:async()=>{chats++;return{answer:'wrong'}},generateProposals:async()=>[],env}));const server=await new Promise(resolve=>{const s=app.listen(0,()=>resolve(s))});t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api/oracle`,origin=new URL(base).origin,login=await fetch(`${base}/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:'{"password":"pw"}'}),auth=await login.json(),cookie=login.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');const response=await fetch(`${base}/chat`,{method:'POST',headers:{origin,cookie,'content-type':'application/json','x-csrf-token':auth.csrf},body:JSON.stringify({message:PROMPT})}),body=await response.json();assert.equal(response.status,200);assert.equal(chats,0);assert.match(body.answer,/Current baseline KPIs/)});

test('production agent and durable worker are wired to the same deterministic route',async()=>{const [server,router]=await Promise.all([readFile(new URL('../server.js',import.meta.url),'utf8'),readFile(new URL('../oracle/ui-router.js',import.meta.url),'utf8')]);assert.match(server,/const baselineAnswer=await baselineOverview\(message\)/);assert.match(server,/baselineOverview,/);assert.match(router,/baselineOverview\?\.\(input\.message\)\|\|await chat/);assert.match(router,/baselineOverview\?\.\(effectiveMessage\)\|\|await chat/)});
