import test from 'node:test';
import assert from 'node:assert/strict';
import {answerExactPageviewsRequest,createPageviewsPerSessionService,EXACT_PAGEVIEWS_ARGS,EXACT_PAGEVIEWS_REQUEST,PAGEVIEWS_MAX_BYTES,renderPageviewsResult,shopifyPageviewsQuery,wooPageviewsQuery} from '../oracle/pageviews-per-session.js';
import {evidenceSummary} from '../oracle/evidence-summary.js';
import fs from 'node:fs';

const fakeBigQuery=rows=>{const calls=[];return{calls,dataset:()=>({getMetadata:async()=>[{location:'EU'}]}),query:async request=>{calls.push(request);return[rows];}};};
const woo=[{date:'2024-11-20',sessions:2,screen_page_views:10},{date:'2024-11-21',sessions:8,screen_page_views:8}];
const shopify=[{day:'2026-01-01',sessions:4,pageviews:20},{day:'2026-01-02',sessions:6,pageviews:10}];
function fixture({wooRows=woo,shopifyRows=shopify}={}){const bigquery=fakeBigQuery(wooRows),queries=[];const service=createPageviewsPerSessionService({bigquery,project:'gf-full-data',runShopifyql:async query=>{queries.push(query);return query.includes('LIMIT 1')?shopifyRows.slice(0,1):shopifyRows;},getShopTimezone:async()=>'Europe/London'});return{bigquery,queries,service};}

test('exact Oracle wording routes deterministically with exact inclusive dates and labels',async()=>{const {service}=fixture();const routed=await answerExactPageviewsRequest(EXACT_PAGEVIEWS_REQUEST,service);assert.deepEqual(routed.route.args,EXACT_PAGEVIEWS_ARGS);assert.equal(routed.route.tool,'get_governed_pageviews_per_session');assert.match(routed.answer,/WooCommerce — GA4/);assert.match(routed.answer,/Shopify — native ShopifyQL/);assert.match(routed.answer,/2024-11-20/);assert.match(routed.answer,/2026-09-27/);});

test('aggregate weights total views by total sessions rather than averaging daily rates',async()=>{const {service,bigquery,queries}=fixture();const result=await service(EXACT_PAGEVIEWS_ARGS);assert.equal(result.woo_ga4.total_views,18);assert.equal(result.woo_ga4.total_sessions,10);assert.equal(result.woo_ga4.views_per_session,1.8);assert.equal(result.shopify_native.total_views,30);assert.equal(result.shopify_native.total_sessions,10);assert.equal(result.shopify_native.views_per_session,3);assert.equal(result.shopify_native.reporting_timezone,'Europe/London');assert.equal(result.shopify_native.pagination.complete,true);assert.match(queries[0],/WHERE human_or_bot_session = 'human'/);assert.match(queries[0],/SHOW sessions, pageviews/);assert.match(queries[1],/LIMIT 250\nOFFSET 0$/);const request=bigquery.calls[0];assert.equal(request.location,'EU');assert.equal(request.maximumBytesBilled,PAGEVIEWS_MAX_BYTES);assert.deepEqual(request.types,{start_date:'DATE',end_date:'DATE'});assert.equal(request.params.start_date.constructor.name,'BigQueryDate');});

test('incomplete coverage is explicit and source semantics remain separate',async()=>{const result=await fixture().service(EXACT_PAGEVIEWS_ARGS);assert.equal(result.woo_ga4.requested.days,365);assert.equal(result.woo_ga4.coverage.covered_days,2);assert.equal(result.woo_ga4.coverage.missing_days,363);assert.equal(result.shopify_native.requested.days,270);assert.match(result.woo_ga4.source_definition,/combined number of web page views and app screen views/);assert.match(result.shopify_native.source,/ShopifyQL FROM sessions/);assert.match(result.comparison_boundary,/not a like-for-like/);const rendered=renderPageviewsResult(result);assert.match(rendered,/18/);assert.match(rendered,/10/);assert.match(rendered,/1\.8/);});

test('Shopify capability errors are distinguished from retrieval errors and are not evidence',async()=>{for(const [message,code] of [['parse error: Unknown metric pageviews','UNSUPPORTED_TOOL_CAPABILITY'],['socket closed','RETRIEVAL_FAILED']]){const bigquery=fakeBigQuery(woo);const service=createPageviewsPerSessionService({bigquery,project:'p',runShopifyql:async()=>{throw new Error(message);},getShopTimezone:async()=>'UTC'});await assert.rejects(service(EXACT_PAGEVIEWS_ARGS),error=>error.code===code);}const fallback=evidenceSummary([{name:'get_governed_pageviews_per_session',result:{success:false,code:'RETRIEVAL_FAILED',failed_stage:'evidence_retrieval'}}]);assert.match(fallback,/No validated analytical figures were available/);assert.doesNotMatch(fallback,/Total views/);});

test('synthesis fallback preserves validated pageview figures and labels',async()=>{const result=await fixture().service(EXACT_PAGEVIEWS_ARGS);const answer=evidenceSummary([{name:'get_governed_pageviews_per_session',result}]);for(const value of ['18','10','1.8','30','3'])assert.match(answer,new RegExp(`\\b${value}\\b`));assert.match(answer,/WooCommerce — GA4/);assert.match(answer,/Shopify — native ShopifyQL/);assert.match(answer,/daily rates were not averaged/);});

test('queries are bounded aggregate reads without device, source or purchase funnels',()=>{assert.match(wooPageviewsQuery('p'),/screen_page_views/);const sql=shopifyPageviewsQuery('2026-01-01','2026-09-27');assert.doesNotMatch(sql,/device|referrer|purchase|checkout/i);assert.match(sql,/LIMIT 250/);});

test('production diagnostic invokes the same helper with authenticated clients and exposes the Render command',()=>{const diagnostic=fs.readFileSync(new URL('../diagnostics/oracle-pageviews-per-session.js',import.meta.url),'utf8'),pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));assert.match(diagnostic,/createPageviewsPerSessionService/);assert.match(diagnostic,/getShopifyAccessToken/);assert.match(diagnostic,/createBigQueryClient/);assert.match(diagnostic,/typed_parameters:\{start_date:'DATE',end_date:'DATE'\}/);assert.equal(pkg.scripts['diagnose:oracle-pageviews-per-session'],'node diagnostics/oracle-pageviews-per-session.js');});
