import assert from 'node:assert/strict';import test from 'node:test';
import {diagnose,storedLabelsQuery} from '../diagnostics/oracle-shopify-device-source-conversion.js';
import {shopifyDeviceSourceQuery} from '../oracle/device-source-conversion.js';
const row={device_type:'mobile',referrer_source:'Direct',sessions:1200,numerator:48,covered_days:92,source_cardinality_limited:false};
function fake({fail=false,dryRunFailure}={}){const calls=[];return{calls,dataset:()=>({getMetadata:async()=>[{location:'US'}]}),createQueryJob:async o=>{calls.push(o);if(dryRunFailure&&o.query===(dryRunFailure==='setup'?storedLabelsQuery('p'):shopifyDeviceSourceQuery('p')))throw Object.assign(new Error('unsafe provider detail'),{code:400});return[{}]},query:async o=>{calls.push(o);if(o.query===storedLabelsQuery('p'))return[[{device_type:'Mobile',referrer_source:'Direct',row_count:92,sessions:1200}]];if(o.query===shopifyDeviceSourceQuery('p')){if(fail)throw Object.assign(new Error('sanitized'),{code:400});return[[row]];}throw new Error('unexpected');}};}
test('actual generated setup SQL uses a nonreserved row_count alias',()=>{const sql=storedLabelsQuery('p');assert.equal(sql,"SELECT device_type,COALESCE(NULLIF(TRIM(referrer_source),''),'unknown') referrer_source,COUNT(*) row_count,SUM(sessions) sessions FROM `p.shopify_data.session_conversion_by_device_source` WHERE date BETWEEN @start_date AND @end_date GROUP BY 1,2 ORDER BY sessions DESC");assert.doesNotMatch(sql,/COUNT\(\*\)\s+rows\b/i);assert.doesNotMatch(shopifyDeviceSourceQuery('p'),/COUNT\([^)]*\)\s+rows\b/i);});
test('diagnostic invokes exact helper with typed dates, metadata location, dry-run and cap',async()=>{const b=fake(),r=await diagnose({bigquery:b,project:'p'});assert.equal(r.status,'SUCCEEDED');assert.equal(r.storage.location,'US');assert.equal(r.helper.totals.sessions,1200);assert.deepEqual(Object.keys(r.query.bindings),['start_date','end_date']);assert.ok(Object.values(r.query.bindings).every(x=>x.declared_parameter_type==='DATE'&&x.runtime_constructor==='BigQueryDate'));assert.ok(b.calls.every(x=>x.location==='US'&&x.maximumBytesBilled===1_000_000_000));assert.equal(b.calls.filter(x=>x.dryRun).length,2);});
test('diagnostic distinguishes helper query failure from absent evidence',async()=>{const r=await diagnose({bigquery:fake({fail:true}),project:'p'});assert.equal(r.status,'QUERY_FAILED');assert.equal(r.evidence_state,'retrieval_failed_not_absent');assert.equal(r.failure.cause_code,400);});
test('setup dry-run failure is stage-specific and does not expose provider details',async()=>{await assert.rejects(diagnose({bigquery:fake({dryRunFailure:'setup'}),project:'p'}),error=>error.stage==='dry_run:stored_labels'&&error.cause_code===400&&error.message==='Stored-label setup query dry-run failed');});
test('helper dry-run failure is stage-specific and safe',async()=>{const r=await diagnose({bigquery:fake({dryRunFailure:'helper'}),project:'p'});assert.equal(r.status,'QUERY_FAILED');assert.deepEqual(r.failure,{stage:'dry_run:oracle_shopify_device_source',cause_code:400,message:'Shopify device/source query dry-run failed'});});
