import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {readFile} from 'node:fs/promises';
import {createBaselineOverviewService,isBaselineOverviewRequest,resolveBaselinePeriods,baselineChange,evidenceSubject} from '../oracle/baseline-overview.js';
import {createOracleUiRouter} from '../oracle/ui-router.js';
import {createAnalysisJobWorker,createMemoryAnalysisJobStore} from '../oracle/analysis-jobs.js';

const PROMPT=`Build a comprehensive ecommerce baseline for the latest complete calendar month, with the previous month and the same month last year as comparisons where comparable evidence exists.
Include orders, gross sales, discounts, refunds, recorded tax and net sales excluding tax; products, customers, shipping, Shopify sessions, Klaviyo and Search Console. Keep currencies separate.`;
const NOW=new Date('2026-10-02T12:00:00.000Z');
const report={finance:{current:[{currency:'GBP',sales_transaction_count:10,gross_sales:1200,refunds:-100,tax:180,net_gross:1100,net_ex_tax:920},{currency:'USD',sales_transaction_count:2,gross_sales:200,refunds:0,tax:0,net_gross:200,net_ex_tax:200}],comparisons:{previous_period:[{currency:'GBP',metrics:{net_gross:{comparison:1000},gross_sales:{comparison:1100},refunds:{comparison:-100},tax:{comparison:160},net_ex_tax:{comparison:840},sales_transaction_count:{comparison:9}}}],prior_year:[{currency:'GBP',metrics:{net_gross:{comparison:0},gross_sales:{comparison:0},refunds:{comparison:0},tax:{comparison:0},net_ex_tax:{comparison:0},sales_transaction_count:{comparison:0}}}]}},conversion:{current:{sessions:100,sessions_with_cart_additions:20,sessions_that_reached_checkout:10,sessions_that_completed_checkout:4,conversion_rate:.04},comparisons:{previous_period:{sessions:{comparison:80}},prior_year:{sessions:{comparison:null}}}},customers:{current:{overall:{customers:8,new_customers:5,returning_customers:3,returning_customer_rate:.375,orders:10}}},products:{current:[{product_id:'gid://product/1',product_title:'Ring',net_sales:400,gross_sales:450,net_items_sold:6,returns:-50,currency:'GBP'}]}};
function country(period){return{period,rows:[{currency:'GBP',country_code:'GB',orders:8,operational_net_sales:800,source_coverage:[{source_platform:'shopify',source_store:'shopify',eligible_orders:8,eligible_sales:800}]},{currency:'GBP',country_code:'US',orders:2,operational_net_sales:300,source_coverage:[{source_platform:'woo',source_store:'ww',eligible_orders:2,eligible_sales:300}]}]};}
function fixture(overrides={}){const calls=[];const record=(name,value)=>async(...args)=>{calls.push([name,args]);if(value instanceof Error)throw value;return structuredClone(typeof value==='function'?value(...args):value)};const service=createBaselineOverviewService({now:()=>NOW,managementReport:record('management',report),onlineCountrySales:record('country',args=>country(args)),customerReport:record('customers',{overall:{customers:7,orders:9,new_customers:4,returning_customers:3}}),shopifyDevice:record('device',{rows:[{device_type:'mobile',referrer_source:'search',sessions:60,completed_checkout_sessions:3}]}),klaviyo:record('klaviyo',{rows:[{report_kind:'campaign',delivered:80,unique_clicks:8,attributed_conversion_events:2,attributed_conversion_value:40,currency:'GBP'},{report_kind:'flow',delivered:20,unique_clicks:3,attributed_conversion_events:1,attributed_conversion_value:25,currency:'GBP'}],coverage:{complete:true,collected_months:['2026-09'],missing_months:[],latest_retrieved_at:'2026-10-01T01:00:00Z'}}),organicReport:record('organic',{rows:[{clicks:20,impressions:200}]}),...overrides});return{service,calls};}

test('exact comprehensive prompt uses a bounded evidence plan and never selects inventory',async()=>{const{service,calls}=fixture();assert.equal(isBaselineOverviewRequest(PROMPT),true);const result=await service(PROMPT);assert.deepEqual(result.attempted_tools,['get_ecommerce_management_report','get_online_country_sales','get_online_country_sales','get_online_country_sales','get_shopify_device_conversion_by_traffic_source','get_klaviyo_email_performance','get_klaviyo_email_performance','get_klaviyo_email_performance','get_ecommerce_report_v2_evidence']);assert.doesNotMatch(JSON.stringify(calls),/inventory/i);assert.match(result.answer,/current 2026-09-01 to 2026-09-30/);assert.match(result.answer,/previous 2026-08-01 to 2026-08-31/);assert.match(result.answer,/same month last year 2025-09-01 to 2025-09-30/);assert.match(result.answer,/GBP 1,100/);assert.match(result.answer,/USD 200/);assert.match(result.answer,/percentage undefined/);assert.match(result.answer,/latest actual source retrieval 2026-10-01/);assert.equal(result.evidence.kind,'ecommerce_monthly_baseline');});

test('calendar resolver handles year rollover and preserves explicit named months',()=>{assert.deepEqual(resolveBaselinePeriods('baseline',{now:new Date('2026-01-04T12:00:00Z')}).current,{start_date:'2025-12-01',end_date:'2025-12-31',days:31});const explicit=resolveBaselinePeriods('Compare September 2026 native Shopify online sales with September 2025 WooCommerce online sales.',{now:NOW});assert.equal(explicit.explicit,true);assert.equal(explicit.current.start_date,'2026-09-01');assert.equal(explicit.previous_period.start_date,'2025-09-01');assert.equal(explicit.prior_year.start_date,'2025-09-01');});

test('missing and explicit zero periods remain distinct and zero denominator is undefined',()=>{assert.deepEqual(baselineChange(12,null),{absolute:null,percentage:null});assert.deepEqual(baselineChange(12,0),{absolute:12,percentage:null});});

test('optional source failure retains successful evidence and structured failure status',async()=>{const error=Object.assign(new Error('secret upstream text'),{code:'THROTTLED'}),{service}=fixture({shopifyDevice:async()=>{throw error}});const result=await service(PROMPT);assert.match(result.answer,/Net sales excluding recorded tax GBP 920/i);assert.match(result.answer,/Device.*unavailable|Device\/acquisition breakdown unavailable/is);assert.match(result.answer,/device.*THROTTLED/is);assert.doesNotMatch(result.answer,/secret upstream text/);assert.equal(result.evidence.evidence.device.status,'rejected');assert.equal(result.evidence.evidence.management.status,'fulfilled');});

test('Woo versus native Shopify output preserves migration, identity, compatibility and currency boundaries',async()=>{const{service}=fixture();const result=await service('Compare September 2026 native Shopify online sales with September 2025 WooCommerce online sales.');assert.match(result.answer,/Matrixify-migrated Woo representations/);assert.match(result.answer,/retired, historical and reportable/);assert.match(result.answer,/directional rather than canonical finance equivalence/);assert.match(result.answer,/No Woo-to-Shopify person identity bridge/);assert.match(result.answer,/Currencies are never converted or combined/);});

test('explicit focused subjects outrank stale platform language and call only applicable services',async()=>{const prompts=[['Compare September 2026 Shopify shipping countries with August 2026 after that Woo versus Shopify comparison.','shipping','shopify_shipping_country_comparison',['country','country']],['Compare September 2026 Shopify customers with August 2026 after that Woo versus Shopify comparison.','customers','shopify_customer_comparison',['customers','customers']],['Compare September 2026 Search Console with August 2026 after that Woo versus Shopify comparison.','search_console','search_console_comparison',['organic']]];for(const [prompt,subject,kind,expected] of prompts){const{service,calls}=fixture();assert.equal(evidenceSubject(prompt),subject);const result=await service(prompt);assert.equal(result.evidence.kind,kind);assert.deepEqual(calls.map(x=>x[0]),expected);assert.equal(subject==='search_console'?calls[0][1][0].current.start_date:calls[0][1][0].start_date,'2026-09-01');if(subject==='shipping')assert.equal(calls[0][1][0].platform,'shopify');assert.doesNotMatch(result.answer,/Native Shopify versus historical WooCommerce evidence/);assert.match(result.answer,new RegExp(subject==='shipping'?'shipping-country':subject==='customers'?'customer':'Search Console','i'));} });

test('platform totals consume repeated coverage once rather than once per ranked country',async()=>{const{service}=fixture();const result=await service('Compare September 2026 native Shopify online sales with September 2025 WooCommerce online sales.');assert.match(result.answer,/shopify\/shopify · GBP:\*\* 8 eligible orders/);assert.doesNotMatch(result.answer,/16 eligible orders/);});

test('interactive UI and durable worker retain independently renderable evidence',async t=>{let chats=0;const{service}=fixture();const store=createMemoryAnalysisJobStore();const env={ORACLE_UI_PASSWORD:'pw',ORACLE_UI_SESSION_SECRET:'01234567890123456789012345678901',ORACLE_ANALYSIS_JOBS_ENABLED:'true',ORACLE_JOB_RUNTIME_MS:'10000'};const app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService:{searchKnowledge:async()=>({items:[]}),searchMemory:async()=>({items:[]})},bigquery:{},project:'p',baselineOverview:service,analysisJobStore:store,chat:async()=>{chats++;return{answer:'wrong'}},generateProposals:async()=>[],env}));const server=await new Promise(resolve=>{const s=app.listen(0,()=>resolve(s))});t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api/oracle`,origin=new URL(base).origin,login=await fetch(`${base}/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:'{"password":"pw"}'}),auth=await login.json(),cookie=login.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');const response=await fetch(`${base}/chat`,{method:'POST',headers:{origin,cookie,'content-type':'application/json','x-csrf-token':auth.csrf},body:JSON.stringify({message:PROMPT})}),body=await response.json();assert.equal(response.status,200);assert.equal(chats,0);assert.equal(body.evidence.kind,'ecommerce_monthly_baseline');const queued=await store.create({owner_key:'o',request_id:'r',payload_json:{message:PROMPT,analysis_context:{},transition:{},created_by:'x'}});const worker=createAnalysisJobWorker({store,pollMs:100000,run:async job=>{const answer=await service(job.payload_json.message);return{success:true,answer:answer.answer,evidence:answer.evidence,tools:answer.tools}}});await worker.tick();const completed=await store.get(queued.job_id,'o');assert.equal(completed.result_json.evidence.kind,'ecommerce_monthly_baseline');});

test('interactive and durable paths preserve the full Woo to focused-subject regression sequence',async t=>{const{service}=fixture();const store=createMemoryAnalysisJobStore(),env={ORACLE_UI_PASSWORD:'pw',ORACLE_UI_SESSION_SECRET:'01234567890123456789012345678901'};const app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService:{searchKnowledge:async()=>({items:[]}),searchMemory:async()=>({items:[]})},bigquery:{},project:'p',baselineOverview:service,analysisJobStore:null,chat:async()=>({answer:'wrong'}),generateProposals:async()=>[],env}));const server=await new Promise(resolve=>{const s=app.listen(0,()=>resolve(s))});t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api/oracle`,origin=new URL(base).origin,login=await fetch(`${base}/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:'{"password":"pw"}'}),auth=await login.json(),cookie=login.headers.getSetCookie().map(x=>x.split(';')[0]).join('; '),headers={origin,cookie,'content-type':'application/json','x-csrf-token':auth.csrf};const sequence=[['Compare September 2026 native Shopify online sales with September 2025 WooCommerce online sales.','woo_shopify_platform_comparison'],['Compare September 2026 Shopify shipping countries with August 2026.','shopify_shipping_country_comparison'],['Compare September 2026 Shopify customers with August 2026.','shopify_customer_comparison'],['Compare September 2026 Search Console with August 2026.','search_console_comparison']];for(const [message,kind] of sequence){const response=await fetch(`${base}/chat`,{method:'POST',headers,body:JSON.stringify({message})}),body=await response.json();assert.equal(response.status,200);assert.equal(body.evidence.kind,kind);if(kind!=='woo_shopify_platform_comparison')assert.doesNotMatch(body.answer,/Native Shopify versus historical WooCommerce evidence/);}const worker=createAnalysisJobWorker({store,pollMs:100000,run:async job=>{const answer=await service(job.payload_json.message);return{success:true,answer:answer.answer,evidence:answer.evidence,tools:answer.tools}}});for(const [index,[message,kind]] of sequence.entries()){const queued=await store.create({owner_key:'o',request_id:`sequence-${index}`,payload_json:{message,analysis_context:{},transition:{},created_by:'x'}});await worker.tick();const completed=await store.get(queued.job_id,'o');assert.equal(completed.result_json.evidence.kind,kind);}});

test('production agent, UI and durable worker are wired to the same deterministic route',async()=>{const [server,router]=await Promise.all([readFile(new URL('../server.js',import.meta.url),'utf8'),readFile(new URL('../oracle/ui-router.js',import.meta.url),'utf8')]);assert.match(server,/const baselineAnswer=await baselineOverview\(message\)/);assert.match(server,/evidence:baselineAnswer\.evidence/);assert.match(router,/baselineOverview\?\.\(input\.message\)\|\|await chat/);assert.match(router,/evidence:answer\.evidence\|\|null/);});
