import test from 'node:test';
import assert from 'node:assert/strict';
import {createProductEvidenceReportService,isProductEvidenceRequest} from '../oracle/product-report.js';

const single='Show the top 20 Shopify Online Store products by net sales for September 2026. Include product IDs, names, currency, units, discounts and refunds. Do not retrieve inventory.';
const comparison='Compare September 2026 versus August 2026 online product performance. Rank the top 20 products by net sales and show units, discounts and refunds. Do not retrieve inventory.';
const row=(id,sales)=>({product_id:id,product_title:`Product ${id}`,net_sales:sales,gross_sales:sales+10,discounts:-5,returns:-5,net_items_sold:2});

test('single-month product route returns deterministic authoritative-currency evidence without inventory',async()=>{const calls=[];const service=createProductEvidenceReportService({getShopCurrency:async()=> 'GBP',getProductPerformance:async args=>{calls.push(args);return{...args,sales_channel:'Online Store',products:[row('p1',100)]}},now:()=>new Date('2026-10-02T12:00:00Z')});assert.equal(isProductEvidenceRequest(single),true);const result=await service(single);assert.deepEqual(calls,[{start_date:'2026-09-01',end_date:'2026-09-30',days:30,limit:50,sort_by:'net_sales'}]);assert.match(result.answer,/p1.*GBP 100/);assert.doesNotMatch(JSON.stringify(result),/get_shopify_inventory/);assert.equal(result.evidence.sections[0].contract.actual_coverage.complete_population,true);});

test('two-month comparisons preserve exact periods and do not zero missing ranked products',async()=>{const calls=[];const service=createProductEvidenceReportService({getShopCurrency:async()=> 'USD',getProductPerformance:async args=>{calls.push(args);return{...args,products:Array.from({length:50},(_,i)=>row(`p${i}`,100-i))}}});const result=await service(comparison);assert.deepEqual(calls.map(x=>x.start_date),['2026-09-01','2026-08-01']);assert.match(result.answer,/not treated as zero/);assert.equal(result.evidence.sections.every(x=>!x.contract.actual_coverage.complete_population),true);});

test('unknown currency retains diagnostics but excludes monetary ranking',async()=>{const service=createProductEvidenceReportService({getShopCurrency:async()=>{throw Object.assign(new Error('secret'),{code:'CURRENCY_LOOKUP_FAILED'})},getProductPerformance:async args=>({...args,products:[row('p1',100)]})});const result=await service(single);assert.match(result.answer,/excluded from the accepted ranking/);assert.doesNotMatch(result.answer,/- #1/);assert.match(result.answer,/no FX conversion or assumed GBP/);assert.equal(result.evidence.currency_status.status,'failed');});

test('one failed period preserves independently successful evidence',async()=>{let count=0;const service=createProductEvidenceReportService({getShopCurrency:async()=> 'GBP',getProductPerformance:async args=>{if(++count===2)throw Object.assign(new Error('provider details'),{code:'RETRIEVAL_FAILED'});return{...args,products:[row('p1',100)]}}});const result=await service(comparison);assert.match(result.answer,/Product p1/);assert.match(result.answer,/retrieval failed \(RETRIEVAL_FAILED\)/);assert.doesNotMatch(result.answer,/provider details/);});
