import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { createOracleUiRouter } from '../oracle/ui-router.js';
import { createGeneralAnalyticsService } from '../oracle/general-analytics.js';
import { createMemoryAnalysisJobStore } from '../oracle/analysis-jobs.js';

const envBase={ORACLE_UI_PASSWORD:'test-password',ORACLE_UI_SESSION_SECRET:'12345678901234567890123456789012',ORACLE_UI_ADMIN_NAME:'test-admin'};
const refs={shopify:'canonical:shopify:gid://shopify/Product/10434344812871',woo:'canonical:woo_usd:108237',wooSource:'woo:ww:25709'};
const rows=[
  {period:'2026-01',product_ref:refs.shopify,canonical_title:'Small Silver Anatomical Heart Pendant',source_title:'SMALL SILVER ANATOMICAL HEART PENDANT',source_product_ref:'shopify:shopify:10434344812871',mapping_method:'source_identity_only',mapping_status:'source_specific',source_platform:'shopify',source_store:'shopify',channel:'Online',currency:'GBP',product_sales:80},
  {period:'2026-01',product_ref:refs.woo,canonical_title:'Small Silver Anatomical Heart Pendant',source_title:'SMALL SILVER ANATOMICAL HEART PENDANT',source_product_ref:refs.wooSource,mapping_method:'explicit_governed_mapping',mapping_status:'resolved',source_platform:'woo',source_store:'ww',channel:'Online',currency:'GBP',product_sales:120}
];
async function login(request,base){const response=await request('/auth/login',{method:'POST',headers:{'content-type':'application/json',origin:new URL(base).origin},body:JSON.stringify({password:envBase.ORACLE_UI_PASSWORD})}),data=await response.json(),cookie=response.headers.getSetCookie().map(value=>value.split(';')[0]).join('; ');return{cookie,csrf:data.csrf};}
async function fixture(durable){const providerCalls=[],baselineOverview=createGeneralAnalyticsService({loadReport:async(section,args)=>{providerCalls.push({section,args});return{rows,comparison_rows:[]}}}),store=durable?createMemoryAnalysisJobStore():null,env={...envBase,...(durable?{ORACLE_ANALYSIS_JOBS_ENABLED:'true',ORACLE_JOB_RUNTIME_MS:'10000'}:{})},app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService:{},bigquery:{},project:'test',chat:async()=>{throw new Error('fallback must not run')},baselineOverview,analysisJobStore:store,env,now:()=>Date.parse('2026-10-05T12:00:00Z')}));const server=await new Promise(resolve=>{const value=app.listen(0,()=>resolve(value))}),base=`http://127.0.0.1:${server.address().port}/api/oracle`,request=(path,options={})=>fetch(base+path,options),auth=await login(request,base),headers={cookie:auth.cookie,origin:new URL(base).origin,'content-type':'application/json','x-csrf-token':auth.csrf};return{server,request,headers,providerCalls};}
async function send(f,durable,message){if(!durable){const response=await f.request('/chat',{method:'POST',headers:f.headers,body:JSON.stringify({message})});assert.equal(response.status,200);return response.json();}const id=`selection-${crypto.randomUUID()}`,submitted=await f.request('/jobs',{method:'POST',headers:{...f.headers,'x-request-id':id},body:JSON.stringify({message})});assert.equal(submitted.status,202);const {job_id}=await submitted.json();for(let attempt=0;attempt<100;attempt++){const response=await f.request(`/jobs/${job_id}`,{headers:{cookie:f.headers.cookie}}),body=await response.json();if(body.status==='completed')return body;if(body.status==='failed')assert.fail(`durable job failed: ${JSON.stringify(body)}`);await new Promise(resolve=>setTimeout(resolve,10));}assert.fail('durable job did not complete');}

for(const durable of [false,true])test(`${durable?'durable':'interactive'} shared HTTP selection preserves candidates, reaches provider, delivers evidence and graphs`,async t=>{const f=await fixture(durable);t.after(()=>f.server.close());const initial=await send(f,durable,'Show sales for SMALL SILVER ANATOMICAL HEART PENDANT this year.');assert.equal(initial.evidence.ambiguous,true);assert.deepEqual(initial.evidence.candidates.map(x=>x.product_ref),[refs.shopify,refs.woo]);assert.match(initial.answer,/2\. \*\*Small Silver/);assert.match(initial.answer,new RegExp(refs.wooSource.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));const selected=await send(f,durable,refs.shopify);assert.equal(selected.evidence.resolved_product_ref,refs.shopify);const selectedCall=f.providerCalls.find(call=>call.args.selected_product_ref===refs.shopify);assert.ok(selectedCall);assert.deepEqual(selectedCall.args.selected_source_refs,['shopify:shopify:10434344812871']);assert.equal(selected.evidence.rows[0].value,80);assert.deepEqual(selected.evidence.diagnostics.map(x=>x.stage),['selection_validation','provider_arguments','evidence_validation','delivery']);assert.deepEqual(selected.evidence.diagnostics.map(x=>x.code),['SELECTION_VALIDATED','SELECTED_IDENTITY_BOUND','SELECTED_IDENTITY_MATCHED','PRODUCT_SALES_DELIVERED']);const graphed=await send(f,durable,'graph that');assert.equal(graphed.evidence.resolved_product_ref,refs.shopify);assert.equal(graphed.inline_chart.kind,'line');assert.equal(graphed.evidence.rows[0].value,80);});
