import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {transitionAnalysisContext,validateAnalysisContext} from '../oracle/analysis-context.js';
import {dispatchAnalysisRequest,executeGovernedAgentAnalysis,assertEvidenceAgreement} from '../oracle/analysis-route-dispatcher.js';
import {createBaselineOverviewService} from '../oracle/baseline-overview.js';
import {createKlaviyoEmailService,klaviyoCampaignSendQuery} from '../oracle/klaviyo-email.js';
import {createOracleProviderDependencies} from '../oracle/provider-dependencies.js';
import {createOracleUiRouter} from '../oracle/ui-router.js';
import {createMemoryAnalysisJobStore} from '../oracle/analysis-jobs.js';
import {collectMetadata} from '../klaviyo/metadata.js';
const NOW=Date.parse('2026-10-09T12:00:00Z');
const apply=(c,m)=>transitionAnalysisContext(c,m,{now:NOW}).context;
const first='How many sales have resulted from the last Klaviyo campaign?';
const candidate={entity_id:'sent-1',entity_name:'Autumn launch',account:'production',channel:'email',status:'sent',is_sent:true,send_time:'2026-09-20T23:30:00Z',send_time_semantics:'actual campaign send timestamp',reporting_timezone:'Europe/London',reporting_cutoff:'2026-09-30',retrieved_at:'2026-10-02T12:00:00Z'};
function fixture(candidates=[candidate]){
  const calls=[],resolverCalls=[];
  const provider=async(name,args)=>{calls.push({name,args});return {reporting_granularity:'calendar_month',rows:['GBP','USD'].map((currency,i)=>({report_kind:'campaign',entity_id:args.campaign_id,entity_name:'Autumn launch',currency,conversion_metric_id:'placed-order',metric_provenance:'shopify:Placed Order',attributed_conversion_events:3+i,attributed_conversion_value:100+i,actual_start_date:'2026-09-01',actual_end_date:'2026-09-30',reporting_timezone:'Europe/London',retrieved_at:'2026-10-02T12:00:00Z',attribution_settings:'5 day click/open',report_period_semantics:'messages in report window'})),coverage:{complete:true,latest_retrieved_at:'2026-10-02T12:00:00Z'},definitions:{attributed_conversion_events:'Credited events, not distinct orders'},limitations:[]};};
  provider.resolveCampaigns=async args=>{resolverCalls.push(args);return {complete:true,candidates:args.name?candidates.filter(c=>c.entity_name===args.name||c.entity_id===args.name):candidates};};
  return {provider,calls,resolverCalls,baseline:createBaselineOverviewService({klaviyo:provider,now:()=>new Date(NOW)})};
}
async function send(f,prior,message,direct=false){const context=apply(prior,message);const r=direct?await executeGovernedAgentAnalysis({message,analysisContext:context,scopeResolved:true,baselineOverview:f.baseline,now:NOW}):await dispatchAnalysisRequest({message,analysisContext:context,baselineOverview:f.baseline});return {...r,context:r.analysis_context||context};}
function verify(r,f){
  assert.doesNotMatch(r.answer,/What date range/);assert.equal(r.context.requested_subject,'klaviyo_email');assert.deepEqual(r.context.metrics,['email_attribution']);assert.deepEqual(r.context.campaign_request.requested_metrics,['purchases','revenue']);assert.equal(r.evidence.campaign.entity_id,'sent-1');assert.equal(r.evidence.campaign.send_time,candidate.send_time);
  assert.deepEqual(f.calls.at(-1),{name:'get_klaviyo_email_performance',args:{start_date:'2026-09-21',end_date:'2026-09-30',campaign_id:'sent-1',campaign_account:'production',campaign_channel:'email'}});
  assert.equal(r.evidence.reporting_granularity,'calendar_month');assert.equal(r.evidence.rows[0].actual_start_date,'2026-09-01');assert.match(r.answer,/Only calendar-month aggregates/);assert.match(r.answer,/Klaviyo attributed 3 purchases to this campaign/);assert.match(r.answer,/source-native count/);assert.match(r.answer,/not established distinct orders/);assert.match(r.answer,/Europe\/London/);assert.match(r.answer,/Latest retrieval/);assert.match(r.answer,/provisional/);assert.deepEqual(r.evidence.rows.map(r=>r.currency),['GBP','USD']);assert.equal(r.context.start_date,'2026-09-21');
}
for(const priorMessage of [null,'Export published products with units sold this year sorted by units sold.','How are mobile and desktop conversion rates this year?'])for(const direct of [false,true])test(`two-turn campaign date clarification ${direct?'agent':'shared'} after ${priorMessage||'fresh'}`,async()=>{
  const f=fixture(),prior=priorMessage?apply(null,priorMessage):null,initial=await send(f,prior,first,direct);assert.match(initial.answer,/What date range/);assert.equal(initial.context.product_report,null);assert.equal(initial.context.comparison_type,null);
  const follow=await send(f,JSON.parse(JSON.stringify(initial.context)),'Since it was sent.',direct);verify(follow,f);assert.equal(f.resolverCalls.length,1);assert.deepEqual(f.resolverCalls[0],{name:null,channel:null,cutoff:'2026-10-09T12:00:00.000Z'});
});
for(const phrase of ['latest email','latest email campaign','last Klaviyo campaign'])test(`${phrase} and since sending resolve campaign send`,async()=>{const f=fixture(),r=await send(f,null,`Show purchases for the ${phrase} since sending.`);verify(r,f);});
test('named campaign uses a bounded exact name resolver and retains identity for dates',async()=>{const f=fixture(),a=await send(f,null,'How many purchases for campaign named Autumn launch?');assert.equal(f.resolverCalls[0].name,'Autumn launch');verify(await send(f,a.context,'Since sending.'),f);});
test('new conversion subject clears campaign continuation',()=>{const campaign=apply(null,first),next=apply(campaign,'Show mobile and desktop conversion rates this year.');assert.equal(next.campaign_request,null);assert.equal(next.requested_subject,'device_conversion');});
test('latest excludes drafts, scheduled unsent and flows and sorts actual sends',async()=>{const f=fixture([{...candidate,entity_id:'old',send_time:'2026-08-01T00:00:00Z'},candidate,{...candidate,entity_id:'draft',status:'draft',is_sent:false},{...candidate,entity_id:'scheduled',status:'scheduled',is_sent:false},{...candidate,entity_id:'flow',channel:'email',entity_kind:'flow'}]);const a=await send(f,null,first);verify(await send(f,a.context,'Since it was sent.'),f);});
test('multiple accounts/channels retain identifiable candidates and relative date intent through selection',async()=>{const f=fixture([candidate,{...candidate,entity_id:'sms-1',account:'US',channel:'sms',send_time:'2026-09-22T10:00:00Z'}]);let r=await send(f,null,first);assert.match(r.answer,/ID sent-1; account production; email/);assert.match(r.answer,/ID sms-1; account US; sms/);r=await send(f,r.context,'Since sending.');assert.equal(r.context.campaign_request.date_mode,'since_send');r=await send(f,r.context,'1');verify(r,f);assert.equal(f.resolverCalls.length,1);});
test('latest email does not silently select another channel',async()=>{const f=fixture();f.provider.resolveCampaigns=async()=>({complete:true,candidates:[candidate,{...candidate,entity_id:'sms',channel:'sms'}]});const r=await send(f,null,'Purchases for latest email since sending.');assert.equal(r.context.campaign_request.selected?.entity_id,'sent-1');});
test('missing actual timestamp asks once and supplied send date advances selected campaign',async()=>{const f=fixture([{...candidate,send_time:null}]);let r=await send(f,null,first+' Since sending.');assert.match(r.answer,/provide the campaign name or send date/i);r=await send(f,r.context,'2026-09-20');assert.doesNotMatch(r.answer,/provide.*send date|What date range/i);assert.equal(f.calls[0].args.start_date,'2026-09-20');assert.equal(r.evidence.campaign.entity_id,'sent-1');assert.equal(r.context.campaign_request.send_date,'2026-09-20');});
test('missing metadata supplied name resumes resolver; unavailable reply is not asked again',async()=>{const f=fixture([]);let r=await send(f,null,first+' Since sending.');assert.match(r.answer,/provide the campaign name or send date/i);r=await send(f,r.context,'Autumn launch');assert.equal(f.resolverCalls.at(-1).name,'Autumn launch');assert.doesNotMatch(r.answer,/please provide|What date range/i);assert.equal(r.context.campaign_request.name,'Autumn launch');});
test('unknown metric counts remain conversions rather than purchases or orders',async()=>{const f=fixture(),original=f.provider;const provider=async(n,a)=>{const r=await original(n,a);r.rows.forEach(row=>row.metric_provenance='unknown integration');return r;};provider.resolveCampaigns=original.resolveCampaigns;f.baseline=createBaselineOverviewService({klaviyo:provider});const r=await send(f,null,first+' Since sending.');assert.match(r.answer,/Klaviyo attributed 3 conversion events/);assert.doesNotMatch(r.answer,/3 purchases|3 distinct orders/);});
test('campaign ID agreement rejects a different retrieved campaign',async()=>{const f=fixture(),r=await send(f,null,first+' Since sending.');assert.throws(()=>assertEvidenceAgreement(r.context,{...r.evidence,campaign:{...candidate,entity_id:'different'}}),e=>e.code==='EVIDENCE_SCOPE_MISMATCH');assert.doesNotThrow(()=>validateAnalysisContext(JSON.parse(JSON.stringify(r.context))));});
test('metadata never substitutes scheduled or updated timestamps for sends',async()=>{const rows=await collectMetadata({client:{paginate:async path=>({data:path.includes('campaigns')?[{id:'c',attributes:{name:'C',status:'sent',scheduled_at:'2026-09-01',updated:'2026-10-01'}}]:[],included:[]})}});assert.equal(rows[0].send_time,null);assert.equal(rows[0].send_time_semantics,'actual send timestamp unavailable');});
test('production dependency sends scoped BigQuery arguments and retains attribution when comparison fails',async()=>{
  const calls=[],bq={dataset:()=>({getMetadata:async()=>[{location:'US'}]}),query:async a=>{calls.push(a);if(a.query.includes('entity_metadata'))return [[candidate]];if(a.query.includes('message_performance'))return [[{report_kind:'campaign',entity_id:'sent-1',metric_provenance:'shopify:Placed Order'}]];if(a.query.includes('window_coverage'))return [[{month_start:'2026-09-01',status:'collected'}]];throw Error('unavailable');}};
  const provider=createOracleProviderDependencies({bigquery:bq,project:'fixture',env:{}}).klaviyo;await provider.resolveCampaigns({name:null,channel:null,cutoff:new Date(NOW).toISOString()});const r=await provider('compare_klaviyo_email_with_shopify_referrer',{start_date:'2026-09-21',end_date:'2026-09-30',campaign_id:'sent-1'});assert.equal(r.rows.length,1);assert.equal(r.component_failures[0].component,'shopify_email_referrer');const a=calls.find(c=>c.query.includes('message_performance'));assert.equal(a.params.campaign_id,'sent-1');assert.equal(a.params.start_date.value,'2026-09-21');assert.equal(a.params.end_date.value,'2026-09-30');assert.match(a.query,/report_kind='campaign' AND entity_id=@campaign_id/);const query=klaviyoCampaignSendQuery('fixture');assert.match(query,/entity_kind='campaign' AND is_sent=TRUE/);assert.match(query,/send_time_semantics='actual campaign send timestamp'/);assert.doesNotMatch(query,/scheduled_at|updated_at/);
});
for(const durable of [false,true])for(const seed of [null,'Export products with units sold this year sorted by units sold.','Show mobile and desktop conversion rates this year.'])test(`real ${durable?'durable':'interactive'} two-turn HTTP after ${seed||'fresh'}`,async t=>{
  const f=fixture(),app=express(),jobs=createMemoryAnalysisJobStore();
  // Seed through the shared context transition; execute the exact production
  // two-turn campaign exchange through the real authenticated router/worker.
  const baseline=async(message,options)=>{if(options.analysisContext?.requested_subject==='klaviyo_email')return f.baseline(message,options);return {answer:'Seed conversation',tools:[]};};
  app.use('/api/oracle',createOracleUiRouter({bigquery:{},project:'fixture',knowledgeService:{},baselineOverview:baseline,chat:async()=>assert.fail('No fallback'),analysisJobStore:jobs,generateProposals:async()=>[],env:{ORACLE_UI_PASSWORD:'password',ORACLE_UI_SESSION_SECRET:'12345678901234567890123456789012',ORACLE_UI_ADMIN_NAME:'staff',ORACLE_ANALYSIS_JOBS_ENABLED:String(durable)},now:()=>NOW}));
  const server=await new Promise((resolve,reject)=>{const s=app.listen(0,'127.0.0.1');s.once('listening',()=>resolve(s));s.once('error',reject);});t.after(()=>{server.closeAllConnections();server.close();});const base=`http://127.0.0.1:${server.address().port}/api/oracle`;
  const login=await fetch(base+'/auth/login',{method:'POST',headers:{origin:new URL(base).origin,'content-type':'application/json'},body:JSON.stringify({password:'password'})}),auth=await login.json(),cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; '),headers={cookie,origin:new URL(base).origin,'content-type':'application/json','x-csrf-token':auth.csrf};let id=0;
  const submit=async message=>{let r=await(await fetch(base+`/${durable?'jobs':'chat'}`,{method:'POST',headers:{...headers,'x-request-id':`campaign-${++id}`},body:JSON.stringify({message})})).json();if(durable){const jobId=r.job_id;for(let i=0;i<300;i++){r=await(await fetch(base+'/jobs/'+jobId,{headers:{cookie}})).json();if(['completed','failed'].includes(r.status))break;await new Promise(resolve=>setTimeout(resolve,10));}assert.equal(r.status,'completed');}return r;};
  if(seed)await submit(seed);const initial=await submit(first);assert.match(initial.answer,/What date range/);const follow=await submit('Since it was sent.');assert.equal(follow.success,true);assert.doesNotMatch(follow.answer,/What date range/);assert.equal(follow.evidence.campaign.entity_id,'sent-1');assert.equal(f.calls.length,1);assert.deepEqual(f.calls[0].args,{start_date:'2026-09-21',end_date:'2026-09-30',campaign_id:'sent-1',campaign_account:'production',campaign_channel:'email'});assert.equal(f.resolverCalls.length,1);if(durable){const recovery=await(await fetch(base+'/jobs/'+follow.job_id,{headers:{cookie}})).json();assert.deepEqual(recovery.evidence,follow.evidence);}
});
test('coverage failure retains successful attributed counts and revenue',async()=>{
  const provider=createKlaviyoEmailService({project:'fixture',bigquery:{dataset:()=>({getMetadata:async()=>[{location:'US'}]}),query:async a=>{if(a.query.includes('message_performance'))return [[{entity_id:'sent-1',attributed_conversion_events:3,attributed_conversion_value:100,currency:'GBP'}]];throw Error('coverage unavailable');}}});const r=await provider('get_klaviyo_email_performance',{start_date:'2026-09-21',end_date:'2026-09-30',campaign_id:'sent-1'});assert.equal(r.rows[0].attributed_conversion_events,3);assert.equal(r.rows[0].attributed_conversion_value,100);assert.equal(r.coverage.complete,false);assert.equal(r.component_failures[0].component,'coverage');
});
test('report failure retains successful send evidence and retry advances without a date question',async()=>{
  const f=fixture(),provider=async()=>{throw Error('report failure');};provider.resolveCampaigns=f.provider.resolveCampaigns;f.baseline=createBaselineOverviewService({klaviyo:provider});let r=await send(f,null,first+' Since sending.');assert.equal(r.evidence.campaign.send_time,candidate.send_time);assert.equal(r.context.campaign_request.selected.entity_id,'sent-1');assert.match(r.answer,/retrieval failed/);assert.doesNotMatch(r.answer,/What date range/);f.baseline=createBaselineOverviewService({klaviyo:f.provider});verify(await send(f,r.context,'Retry that request.'),f);
});
test('supplied campaign name after unavailable metadata resolves the retained since-send request',async()=>{
  const f=fixture();let unavailable=true;const resolver=f.provider.resolveCampaigns;f.provider.resolveCampaigns=async a=>{if(unavailable){unavailable=false;throw Error('metadata temporarily unavailable');}return resolver(a);};let r=await send(f,null,first+' Since sending.');r=await send(f,r.context,'Autumn launch');verify(r,f);assert.equal(f.resolverCalls.at(-1).name,'Autumn launch');
});
test('named send date preserves day precision and does not use the month start',async()=>{const f=fixture([{...candidate,send_time:null}]);let r=await send(f,null,first+' Since sending.');r=await send(f,r.context,'It was sent on 20 September 2026.');assert.equal(f.calls[0].args.start_date,'2026-09-20');assert.doesNotMatch(r.answer,/What date range/);});
test('explicit campaign date range is retained and does not resolve since-send implicitly',async()=>{const f=fixture(),r=await send(f,null,'Show purchases for campaign named Autumn launch from 2026-09-01 to 2026-09-30.');assert.equal(f.resolverCalls[0].name,'Autumn launch');assert.equal(r.evidence.campaign.entity_id,'sent-1');assert.deepEqual(f.calls[0].args,{start_date:'2026-09-01',end_date:'2026-09-30',campaign_id:'sent-1',campaign_account:'production',campaign_channel:'email'});assert.equal(r.context.campaign_request.date_mode,null);});
test('explicit period replaces a previous relative date mode without losing the campaign',async()=>{const f=fixture();let r=await send(f,null,first+' Since sending.');r=await send(f,r.context,'For September 2026.');assert.equal(r.context.campaign_request.date_mode,null);assert.deepEqual(f.calls.at(-1).args,{start_date:'2026-09-01',end_date:'2026-09-30',campaign_id:'sent-1',campaign_account:'production',campaign_channel:'email'});});
test('duplicate names across accounts are never an implicit candidate selection',async()=>{const f=fixture([candidate,{...candidate,account:'US',entity_id:'sent-2'}]);let r=await send(f,null,first+' Since sending.');r=await send(f,r.context,'Autumn launch');assert.equal(r.context.campaign_request.selected,null);assert.equal(f.calls.length,0);assert.equal(r.context.campaign_request.candidates.length,2);});
test('future send timestamps cannot win latest resolution at the reporting request cutoff',async()=>{const f=fixture([candidate,{...candidate,entity_id:'future',send_time:'2026-10-10T12:00:00Z'}]);verify(await send(f,null,first+' Since sending.'),f);});
test('successful coverage survives attribution failure and does not become zero purchases',async()=>{const provider=createKlaviyoEmailService({project:'fixture',bigquery:{dataset:()=>({getMetadata:async()=>[{location:'US'}]}),query:async a=>{if(a.query.includes('window_coverage'))return [[{month_start:'2026-09-01',status:'collected'}]];throw Error('attribution unavailable');}}});const r=await provider('get_klaviyo_email_performance',{start_date:'2026-09-21',end_date:'2026-09-30',campaign_id:'sent-1'});assert.equal(r.success,false);assert.equal(r.coverage.complete,true);assert.equal(r.component_failures[0].component,'attribution');assert.deepEqual(r.rows,[]);});
test('nullable tool campaign ID does not become a BigQuery DATE parameter',async()=>{const calls=[],service=createKlaviyoEmailService({project:'fixture',bigquery:{dataset:()=>({getMetadata:async()=>[{location:'US'}]}),query:async a=>{calls.push(a);return [[]];}}});await service('get_klaviyo_email_performance',{start_date:'2026-09-01',end_date:'2026-09-30',campaign_id:null});assert.ok(calls.every(c=>!Object.hasOwn(c.params,'campaign_id')));assert.deepEqual(calls[0].types,{start_date:'DATE',end_date:'DATE'});});
test('candidate selection carries account and channel to the actual performance provider',async()=>{const f=fixture([candidate,{...candidate,entity_id:'us-sms',account:'US',channel:'sms'}]);let r=await send(f,null,first+' Since sending.');r=await send(f,r.context,'2');assert.equal(r.evidence.campaign.account,'US');assert.equal(f.calls[0].args.campaign_account,'US');assert.equal(f.calls[0].args.campaign_channel,'sms');assert.equal(f.calls[0].args.campaign_id,'us-sms');});
test('persisted email binding rejects a foreign account/channel before querying',async()=>{let queried=false;const service=createKlaviyoEmailService({project:'fixture',bigquery:{query:async()=>{queried=true;return [[]];}}});for(const scope of [{campaign_account:'US'},{campaign_channel:'sms'}])await assert.rejects(service('get_klaviyo_email_performance',{start_date:'2026-09-01',end_date:'2026-09-30',campaign_id:'sent-1',...scope}),e=>e.code==='KLAVIYO_CAMPAIGN_SCOPE_UNSUPPORTED');assert.equal(queried,false);});
