import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { transitionAnalysisContext } from '../oracle/analysis-context.js';
import { dispatchAnalysisRequest } from '../oracle/analysis-route-dispatcher.js';
import { createGeneralAnalyticsService } from '../oracle/general-analytics.js';
import { createBaselineOverviewService } from '../oracle/baseline-overview.js';
import { selectChartForDataset, selectOracleCharts } from '../oracle/evidence-charts.js';
import { createOracleUiRouter } from '../oracle/ui-router.js';
import { createMemoryAnalysisJobStore } from '../oracle/analysis-jobs.js';
import { createReadOnlyProductHistory } from '../oracle/product-history.js';
import { inspectAnalysisIncident } from '../diagnostics/oracle-analysis-incident.js';
const NOW=Date.parse('2026-10-06T12:00:00Z'),now=()=>NOW;
const apply=(context,message)=>transitionAnalysisContext(context,message,{now:NOW}).context;
const env={ORACLE_UI_PASSWORD:'test-password',ORACLE_UI_SESSION_SECRET:'12345678901234567890123456789012',ORACLE_UI_ADMIN_NAME:'staff'};
const salesRow=(period,extra={})=>({period,product_ref:'shopify:shopify:10',canonical_title:'Pendant',source_title:'Pendant',source_product_ref:'shopify:shopify:10',source_platform:'shopify',source_store:'shopify',channel:'Online',currency:'GBP',product_sales:100,...extra});
const days=args=>Math.floor((Date.parse(args.end_date)-Date.parse(args.start_date))/86400000)+1;
function baselineFixture(){const calls=[];const device=async(tool,args)=>{calls.push({tool,args});const covered=days(args);return {rows:[{device_type:'mobile',sessions:100,numerator:5,coverage:{expected_days:covered,covered_days:covered,complete:true}},{device_type:'desktop',sessions:100,numerator:10,coverage:{expected_days:covered,covered_days:covered,complete:true}}]};};
  return {calls,service:createBaselineOverviewService({now:()=>new Date(NOW),shopifyDevice:device,wooConversion:device,shopifySales:async args=>{calls.push({tool:'get_shopify_sales_kpis',args});return{currency:'GBP',metrics:{net_sales:100,orders:2,gross_sales:110,discounts:10,returns:0,total_sales:100,net_items_sold:3}};},onlineCountrySales:async args=>{calls.push({tool:'get_online_country_sales',args});return{rows:[{country_code:'GB',currency:'GBP',sources:[{source_platform:'shopify',orders:3,operational_net_sales:100}]},{country_code:'US',currency:'USD',sources:[{source_platform:'shopify',orders:2,operational_net_sales:200}]}]};}})};
}
async function dispatch(message,service,prior=null){const context=apply(prior,message);return dispatchAnalysisRequest({message,analysisContext:context,baselineOverview:service,chat:async()=>assert.fail('must execute governed binding')});}

test('natural sales, country, product, conversion and compatible comparison requests select charts without graph instructions',async()=>{
  const b=baselineFixture();
  const sales=await dispatch('How are online sales this year?',b.service);assert.equal(sales.inline_chart.kind,'line');assert.equal(sales.inline_chart.unit,'GBP');assert.ok(sales.inline_chart.table.rows.length>2);
  const country=await dispatch('Show shipping countries by online sales for September 2026.',b.service);assert.equal(country.inline_chart.kind,'horizontal_bar');assert.deepEqual(country.charts.map(c=>c.unit),['GBP','USD']);assert.ok(country.charts.every(c=>c.bounded));
  const p=createGeneralAnalyticsService({loadReport:async()=>({rows:[salesRow('2026-01'),salesRow('2026-02',{product_sales:120}),salesRow('2026-03',{product_sales:null}),salesRow('2026-04',{currency:'USD',product_sales:1000}),salesRow('2026-05',{currency:'USD',product_sales:1500})],comparison_rows:[]})});
  const product=await dispatch('Show online sales for Pendant this year.',p);assert.equal(product.inline_chart.kind,'line');assert.deepEqual(product.charts.map(c=>c.unit),['GBP','USD']);assert.ok(product.charts.every(c=>c.table.rows.every(r=>r[4]!==null)));assert.ok(product.charts[0].accessible_label.includes('Missing evidence is not zero'));
  const conversion=await dispatch('how mobile and desktop conversion rates this year',b.service);assert.equal(conversion.inline_chart.kind,'line');assert.equal(conversion.inline_chart.unit,'percent');assert.equal(conversion.charts[0].table.rows[0][4],5);assert.ok(b.calls.some(c=>c.tool==='get_shopify_device_conversion_by_traffic_source'));
  const context=apply(null,'how mobile and desktop conversion rates this year'),comparison=await dispatch('What changed between August and September?',b.service,context);assert.equal(comparison.inline_chart.kind,'grouped_bar');const sections=comparison.evidence.sections;assert.deepEqual(sections.map(s=>[s.period.start_date,s.period.end_date]),[['2026-09-01','2026-09-30'],['2026-08-01','2026-08-31']]);assert.ok(comparison.inline_chart.table.rows.some(r=>r[1]==='2026-08-01 to 2026-08-31'));
});
test('selector excludes unsupported overlaps, top-N whole-population shares, mixed money, failed cells and incompatible funnels',()=>{
  const base={id:'contract',title:'Example',shape:'composition',definition:'Same population',unit:'customers',period:'2026-09',compatible:true,points:[{label:'New',value:5},{label:'Returning',value:7}]};assert.deepEqual(selectChartForDataset(base),[]);assert.deepEqual(selectChartForDataset({...base,mutually_exclusive:true,complete_population:true,bounded:true}),[]);
  const composition=selectChartForDataset({...base,mutually_exclusive:true,complete_population:true});assert.equal(composition[0].kind,'stacked_percentage_bar');assert.equal(composition[0].groups[0].items.reduce((s,p)=>s+p.value,0),100);
  assert.deepEqual(selectChartForDataset({...base,shape:'funnel',same_population:true,unit:'sessions'}),[]);
  const funnel=selectChartForDataset({...base,shape:'funnel',same_population:true,unit:'sessions',points:[{label:'Sessions',value:100},{label:'Cart sessions',value:50},{label:'Checkout sessions',value:10}]});assert.equal(funnel[0].kind,'stage_bar');
  const money=selectChartForDataset({...base,shape:'ranking',unit:'money',points:[{label:'A',currency:'GBP',value:10},{label:'B',currency:'USD',value:1000},{label:'C',currency:'GBP',value:null},{label:'D',currency:'GBP',value:0},{label:'E',currency:'GBP',value:7,status:'failed'}]});assert.deepEqual(money.map(c=>c.unit),['GBP','USD']);assert.deepEqual(money[0].table.rows.map(r=>r[4]),[10,0]);assert.deepEqual(selectOracleCharts({kind:'shopify_customer_comparison',classification_boundary:{new_and_returning_mutually_exclusive:null},sections:[]}),[]);
  const comparison=selectChartForDataset({...base,shape:'comparison',unit:'percent',points:[{label:'Mobile',series:'2025',value:2,definition:'GA4 purchase events/session'},{label:'Mobile',series:'2026',value:3,definition:'Shopify checkout sessions/session'}]});assert.deepEqual(comparison,[]);
});
test('read-only reporting-family history uses resolved governed decisions and never calls setup or invents links',async()=>{
  const calls=[],inspect=createReadOnlyProductHistory({project:'test',bigquery:{query:async args=>{calls.push(args);return[[{source_ref:'woo:ww:7',shopify_parent_ref:'shopify:shopify:10',status:'active',decision_id:'d1'}]];}}});
  const history=await inspect({product_ref:'family:shopify:shopify:10',sources:[{source_product_ref:'shopify:shopify:10'}]});assert.deepEqual(history.active_source_refs,['woo:ww:7']);assert.match(calls[0].query,/family_superseded/);assert.match(calls[0].query,/family_current/);assert.match(calls[0].query,/LIMIT 1001/);assert.doesNotMatch(calls[0].query,/\b(?:CREATE|INSERT|MERGE|UPDATE)\b/);assert.equal(calls[0].params.parent,'shopify:shopify:10');
});
test('product historical outcomes distinguish empty retrieval, missing mapping, unavailable coverage and provider failure',async()=>{
  const candidate={product_ref:'shopify:shopify:10',catalogue_titles:['Pendant'],sources:[{source_product_ref:'shopify:shopify:10',source_platform:'shopify',source_store:'shopify'}],reporting_family_relationships:[]},context={...apply(null,'Show online sales for Pendant last year.'),product_ref:candidate.product_ref,pending_product_candidates:[candidate]};
  for(const [expected,report,history] of [['historical_mapping_missing',{rows:[],comparison_rows:[]},{status:'available',active_source_refs:[],members:[]}],['source_coverage_unavailable',{rows:[],coverage:{complete:false}},null],['successful_empty_retrieval',{rows:[],retrieval:[{status:'fulfilled'}]},{status:'available',active_source_refs:['woo:ww:7'],members:[]}],['provider_failure',{rows:[],retrieval:[{status:'failed'}]},null]]){
    const calls=[],service=createGeneralAnalyticsService({loadReport:async(section,args)=>{calls.push(args);return report;},inspectProductHistory:async()=>history});const result=await dispatchAnalysisRequest({message:'What about last year?',analysisContext:context,baselineOverview:service});assert.equal(result.evidence.availability,expected);assert.doesNotMatch(result.answer,/\| Month \|/);assert.match(result.answer,/2025-01-01 to 2025-12-31/);assert.equal(calls[0].channel,'Online');assert.equal(result.evidence.resolved_product_ref,candidate.product_ref);assert.deepEqual(result.charts,[]);
  }
  const service=createGeneralAnalyticsService({inspectProductHistory:async()=>({status:'available',active_source_refs:['woo:ww:7'],members:[{source_ref:'woo:ww:7',status:'active'}]}),loadReport:async(section,args)=>{assert.ok(args.selected_source_refs.includes('woo:ww:7'));return{rows:[salesRow('2025-02',{product_ref:'family:shopify:shopify:10',canonical_title:'Renamed historical product',source_product_ref:'woo:ww:7',source_platform:'woo'})]};}});const mapped=await dispatchAnalysisRequest({message:'What about last year?',analysisContext:context,baselineOverview:service});assert.equal(mapped.evidence.rows[0].value,100);assert.equal(mapped.evidence.resolved_product_ref,candidate.product_ref);
});

test('exact-correlated incident trace reports context, executable binding and recorded actual stage without mutation',async()=>{
  const calls=[],result=await inspectAnalysisIncident({project:'test',dataset:'commerce',table:'jobs',requestId:'6395298a-d087-4ed6-aa3a-b2aeb7eb4106',bigquery:{dataset:()=>({getMetadata:async()=>[{location:'EU'}]}),query:async args=>{calls.push(args);return [[{status:'failed',route:'get_governed_device_conversion',subject:'device_conversion',start_date:'2026-01-01',end_date:'2026-10-06',channel:'online',failed_stage:'query:oracle_shopify',error_code:'SOURCE_TIMEOUT'}]];}}});assert.equal(result.binding,'registered');assert.equal(result.actual_failed_stage,'query:oracle_shopify');assert.equal(result.context.channel,'online');assert.equal(calls.length,1);assert.match(calls[0].query,/WHERE request_id=@request_id/);assert.match(calls[0].query,/LIMIT 1/);assert.doesNotMatch(calls[0].query,/\b(?:CREATE|MERGE|UPDATE|INSERT)\b/);
});

for(const durable of [false,true])test(`complete selection → historical limitation → failed conversion → month clarification sequence through ${durable?'durable':'interactive'} shared delivery`,async t=>{
  const args=[],b=baselineFixture(),product=createGeneralAnalyticsService({inspectProductHistory:async()=>({status:'available',members:[],active_source_refs:[]}),loadReport:async(section,input)=>{args.push(input);return{rows:input.start_date.startsWith('2025')?[]:[salesRow('2026-01'),salesRow('2026-02'),salesRow('2026-01',{product_ref:'family:shopify:shopify:20',source_product_ref:'woo:ww:7',source_platform:'woo'})],comparison_rows:[],retrieval:[{status:'fulfilled'}]};}});
  let failConversion=true;const contexts=[],baseline=async(message,options)=>{contexts.push(options.analysisContext);if(options.analysisContext?.tool_route==='get_governed_device_conversion'&&failConversion){failConversion=false;throw Object.assign(new Error('native query failure'),{code:'NATIVE_QUERY_FAILED',failed_stage:'query:oracle_shopify'});}return await product(message,options)||await b.service(message,options);};
  const jobs=createMemoryAnalysisJobStore(),app=express();app.use('/api/oracle',createOracleUiRouter({knowledgeService:{},bigquery:{},project:'test',baselineOverview:baseline,chat:async()=>assert.fail('no fallback'),analysisJobStore:jobs,generateProposals:async()=>[],env:{...env,ORACLE_ANALYSIS_JOBS_ENABLED:String(durable)},now}));const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`;
  const login=await fetch(base+'/api/oracle/auth/login',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({password:env.ORACLE_UI_PASSWORD})}),auth=await login.json(),cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; '),headers={cookie,origin:base,'content-type':'application/json','x-csrf-token':auth.csrf};let index=0;
  const send=async(message)=>{const response=await fetch(base+`/api/oracle/${durable?'jobs':'chat'}`,{method:'POST',headers:{...headers,'x-request-id':`sequence-${++index}`},body:JSON.stringify({message})});let result=await response.json();if(durable){assert.equal(response.status,202);for(let i=0;i<300;i++){result=await(await fetch(base+`/api/oracle/jobs/${result.job_id}`,{headers:{cookie}})).json();if(['completed','failed'].includes(result.status))break;await new Promise(r=>setTimeout(r,10));}}return {status:response.status,...result};};
  const offered=await send('Show online sales for Pendant this year.');assert.equal(offered.evidence.ambiguous,true);const selected=await send('1');assert.equal(selected.evidence.resolved_product_ref,'shopify:shopify:10');assert.equal(selected.evidence.channel,'online');assert.equal(selected.inline_chart.kind,'line');
  const historical=await send('What about last year?');assert.equal(historical.evidence.availability,'historical_mapping_missing');assert.match(historical.answer,/no active Woo source link/);assert.doesNotMatch(historical.answer,/\| Month \|/);assert.equal(args.at(-1).start_date,'2025-01-01');assert.equal(args.at(-1).end_date,'2025-12-31');assert.equal(args.at(-1).channel,'Online');
  const failed=await send('how mobile and desktop conversion rates this year');assert.equal(durable?failed.failed_stage:failed.failure_stage,'query:oracle_shopify');assert.equal(contexts.at(-1).tool_route,'get_governed_device_conversion');assert.equal(contexts.at(-1).requested_subject,'device_conversion');assert.equal(contexts.at(-1).start_date,'2026-01-01');
  const compared=await send('What changed between August and September?');assert.match(compared.answer,/conversion rates or product sales/);assert.equal(compared.evidence,null);assert.equal(compared.inline_chart,null);
  const resolved=await send('Conversion rates');assert.equal(resolved.evidence.requested_subject,'device_conversion');assert.equal(resolved.inline_chart.kind,'grouped_bar');assert.deepEqual(b.calls.map(c=>[c.args.start_date,c.args.end_date]),[['2026-09-01','2026-09-30'],['2026-08-01','2026-08-31']]);
  if(durable){const recovered=await(await fetch(base+`/api/oracle/jobs/${resolved.job_id}`,{headers:{cookie}})).json();assert.deepEqual(recovered.charts,resolved.charts);assert.deepEqual(recovered.evidence.chart_specs,resolved.charts);}
});
