import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlatformSalesService,describeBigQueryFailure,platformSalesSql,readableTemporal} from '../oracle/platform-sales.js';

test('platform population SQL is independent of geography and exposes acceptance diagnostics',()=>{const sql=platformSalesSql('project');assert.match(sql,/original_order_total/);assert.match(sql,/recorded_refunds/);assert.match(sql,/total_less_refunds/);assert.match(sql,/retail_location_id IS NULL/);assert.match(sql,/order_source/);assert.match(sql,/missing_financial/);assert.match(sql,/missing_location/);assert.match(sql,/missing_customer/);assert.match(sql,/included_fully_refunded_orders/);assert.match(sql,/excluded_refunded_status_orders/);assert.match(sql,/source_app_id!=@matrixify_app_id/);assert.doesNotMatch(sql,/geograph|country/i);});

test('platform service binds real DATE wrappers and returns query representations',async()=>{let options;const service=createPlatformSalesService({project:'project',bigquery:{query:async value=>{options=value;return [[{source_platform:'shopify',source_store:'shopify',currency:'GBP',eligible_orders:1}]];}}}),result=await service({start_date:'2026-04-01',end_date:'2026-04-30',platform:'shopify'});assert.equal(options.types.start_date,'DATE');assert.equal(options.params.start_date.value,'2026-04-01');assert.equal(options.params.end_date.value,'2026-04-30');assert.equal(options.params.platform,'shopify');assert.equal(result.query.parameter_representations.start_date.runtime,'BigQueryDate');assert.equal(result.coverage.population_rows,1);});

test('BigQuery temporal wrappers render as readable scalars',async()=>{assert.equal(readableTemporal({value:'2026-04-01'}),'2026-04-01');assert.equal(readableTemporal({value:'2026-05-01T12:34:56.000Z'}),'2026-05-01T12:34:56.000Z');const service=createPlatformSalesService({project:'project',bigquery:{query:async()=>[[{source_platform:'woo',source_store:'ww',currency:'GBP',actual_first_order_date:{value:'2025-04-01'},actual_last_order_date:{value:'2025-04-30'},source_collected_at:{value:'2026-10-01T00:00:00Z'}}]]}}),result=await service({start_date:'2025-04-01',end_date:'2025-04-30',platform:'woo'});assert.equal(result.rows[0].actual_first_order_date,'2025-04-01');assert.doesNotMatch(JSON.stringify(result.rows),/\[object Object\]/);});

test('BigQuery failure diagnostics retain only bounded reason and statement location',async()=>{const diagnostic=describeBigQueryFailure({errors:[{reason:'invalidQuery',location:'query:17:9',message:'SELECT private payload'}]});assert.deepEqual(diagnostic,{reason:'invalidQuery',location:'query:17:9'});const service=createPlatformSalesService({project:'project',bigquery:{query:async()=>{throw{errors:[{reason:'invalidQuery',location:'query:22:4',message:'secret SQL'}]};}}});await assert.rejects(service({start_date:'2025-04-01',end_date:'2025-04-30',platform:'woo'}),error=>error.code==='PLATFORM_SALES_QUERY_FAILED'&&error.diagnostic.reason==='invalidQuery'&&error.diagnostic.location==='query:22:4'&&!JSON.stringify(error).includes('secret SQL'));});
