import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlatformSalesService,describeBigQueryFailure,platformSalesSql,readableTemporal,resolvePlatformSalesLocation} from '../oracle/platform-sales.js';

test('platform population SQL exposes bounded population acceptance evidence',()=>{const sql=platformSalesSql('project');for(const evidence of ['candidate_reconciliation','authoritative_channel','raw_channel','Other identified','Unknown','unmatched_customer_evidence','present_customer_rows_with_null_identity','component_freshness','minimum_stored_retrieval_timestamp','positive_original_fully_refunded_orders','zero_original_value_orders','fully_refunded_residual','duplicate_identities','conflicting_duplicate_identities'])assert.match(sql,new RegExp(evidence));assert.match(sql,/retail_location_id IS NULL/);assert.match(sql,/source_app_id!=@matrixify_app_id/);assert.doesNotMatch(sql,/geograph|country/i);});

test('platform service binds real DATE wrappers, location and parses diagnostics',async()=>{let options;const service=createPlatformSalesService({project:'project',location:'EU',bigquery:{query:async value=>{options=value;return [[{source_platform:'shopify',source_store:'shopify',currency:'GBP',eligible_orders:1,population_diagnostics_json:'{"missing_customer":16,"component_freshness":[]}'}]];}}}),result=await service({start_date:'2026-04-01',end_date:'2026-04-30',platform:'shopify'});assert.equal(options.types.start_date,'DATE');assert.equal(options.params.start_date.value,'2026-04-01');assert.equal(options.location,'EU');assert.equal(result.rows[0].population_diagnostics.missing_customer,16);assert.equal(result.query.parameter_representations.start_date.runtime,'BigQueryDate');});

test('BigQuery temporal wrappers render as readable scalars including nested component ranges',async()=>{assert.equal(readableTemporal({value:'2026-04-01'}),'2026-04-01');const service=createPlatformSalesService({project:'project',location:'EU',bigquery:{query:async()=>[[{source_platform:'woo',source_store:'ww',currency:'GBP',actual_first_order_date:{value:'2025-04-01'},population_diagnostics_json:'{"component_freshness":[{"minimum_stored_retrieval_timestamp":{"value":"2026-10-01T00:00:00Z"}}]}'}]]}}),result=await service({start_date:'2025-04-01',end_date:'2025-04-30',platform:'woo'});assert.equal(result.rows[0].actual_first_order_date,'2025-04-01');assert.equal(result.rows[0].population_diagnostics.component_freshness[0].minimum_stored_retrieval_timestamp,'2026-10-01T00:00:00Z');});

test('dataset location is resolved from metadata and mismatches are rejected',async()=>{const bigquery={dataset:name=>({getMetadata:async()=>[{location:name==='metorik_us'?'EU':'EU'}]})};assert.equal((await resolvePlatformSalesLocation(bigquery,'project')).location,'EU');const mismatch={dataset:name=>({getMetadata:async()=>[{location:name==='shopify_data'?'US':'EU'}]})};await assert.rejects(()=>resolvePlatformSalesLocation(mismatch,'project'),error=>error.code==='DATASET_LOCATION_MISMATCH');});

test('BigQuery failure diagnostics retain only bounded reason and statement location',async()=>{const diagnostic=describeBigQueryFailure({errors:[{reason:'invalidQuery',location:'query:17:9',message:'SELECT private payload'}]});assert.deepEqual(diagnostic,{reason:'invalidQuery',location:'query:17:9'});const service=createPlatformSalesService({project:'project',location:'EU',bigquery:{query:async()=>{throw{errors:[{reason:'invalidQuery',location:'query:22:4',message:'secret SQL'}]};}}});await assert.rejects(service({start_date:'2025-04-01',end_date:'2025-04-30',platform:'woo'}),error=>error.code==='PLATFORM_SALES_QUERY_FAILED'&&error.diagnostic.reason==='invalidQuery'&&error.diagnostic.location==='query:22:4'&&!JSON.stringify(error).includes('secret SQL'));});
