import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlatformSalesService,describeBigQueryFailure,platformSalesSql} from '../oracle/platform-sales.js';

test('platform population SQL is independent of geography and exposes order/refund components',()=>{const sql=platformSalesSql('project');assert.match(sql,/original_order_total/);assert.match(sql,/recorded_refunds/);assert.match(sql,/total_less_refunds/);assert.match(sql,/retail_location_id IS NULL/);assert.match(sql,/source_app_id!=@matrixify_app_id/);assert.doesNotMatch(sql,/geograph|country|LIMIT 10/i);});

test('platform service binds real DATE wrappers and returns query representations',async()=>{let options;const service=createPlatformSalesService({project:'project',bigquery:{query:async value=>{options=value;return [[{source_platform:'shopify',source_store:'shopify',currency:'GBP',eligible_orders:1}]];}}}),result=await service({start_date:'2026-04-01',end_date:'2026-04-30',platform:'shopify'});assert.equal(options.types.start_date,'DATE');assert.equal(options.params.start_date.value,'2026-04-01');assert.equal(options.params.end_date.value,'2026-04-30');assert.equal(options.params.platform,'shopify');assert.equal(result.query.parameter_representations.start_date.runtime,'BigQueryDate');assert.equal(result.coverage.population_rows,1);});

test('BigQuery failure diagnostics retain only bounded reason and statement location',async()=>{const diagnostic=describeBigQueryFailure({errors:[{reason:'invalidQuery',location:'query:17:9',message:'SELECT private payload'}]});assert.deepEqual(diagnostic,{reason:'invalidQuery',location:'query:17:9'});const service=createPlatformSalesService({project:'project',bigquery:{query:async()=>{throw{errors:[{reason:'invalidQuery',location:'query:22:4',message:'secret SQL'}]};}}});await assert.rejects(service({start_date:'2025-04-01',end_date:'2025-04-30',platform:'woo'}),error=>error.code==='PLATFORM_SALES_QUERY_FAILED'&&error.diagnostic.reason==='invalidQuery'&&error.diagnostic.location==='query:22:4'&&!JSON.stringify(error).includes('secret SQL'));});
