import assert from 'node:assert/strict';import test from 'node:test';
import {normalizeRows,shopifyql,validateRows} from '../shopify/conversion-analytics.js';import {decode,parseArgs,plan,probeQueries,readiness,runBackfill} from '../shopify/conversion-backfill.js';
const metrics='sessions, sessions_that_completed_checkout, conversion_rate, sessions_with_cart_additions, sessions_that_reached_checkout';
test('pilot ShopifyQL statements use the supported GROUP BY clause',()=>{
  assert.equal(shopifyql('2025-11-20','2025-11-26'),`FROM sessions\nSHOW ${metrics}\nGROUP BY day, session_device_type\nWHERE human_or_bot_session = 'human'\nSINCE 2025-11-20 UNTIL 2025-11-26\nORDER BY day ASC`);
  assert.equal(shopifyql('2025-11-20','2025-11-26',true),`FROM sessions\nSHOW ${metrics}\nGROUP BY day, session_device_type, referrer_source\nWHERE human_or_bot_session = 'human'\nSINCE 2025-11-20 UNTIL 2025-11-26\nORDER BY day ASC`);
});
test('returned ShopifyQL dimension columns decode into persisted names',()=>{const tableData={columns:['day','session_device_type','referrer_source',...metrics.split(', ')].map(name=>({name})),rows:[['2025-11-20','mobile','Google',12,3,.25,5,4]]};const rows=normalizeRows(decode(tableData),{withSource:true,timezone:'Europe/London',syncedAt:'2026-09-28T00:00:00.000Z'});assert.equal(rows.length,1);assert.deepEqual({date:rows[0].date,device_type:rows[0].device_type,referrer_source:rows[0].referrer_source},{date:'2025-11-20',device_type:'mobile',referrer_source:'Google'});assert.equal(rows[0].sessions,12);});
test('read-only probe sends exactly two bounded statements',async()=>{const seen=[];const chunk={startDate:'2025-11-20',endDate:'2025-11-26'};const result=await probeQueries({chunk,query:async q=>{seen.push(q);return{columns:[],rows:[]};}});assert.equal(result.length,2);assert.deepEqual(seen,[shopifyql(chunk.startDate,chunk.endDate),shopifyql(chunk.startDate,chunk.endDate,true)]);});
test('both queries parse before schema creation',async()=>{const events=[];const options=parseArgs(['--start','2025-11-20','--end','2025-11-26','--chunk-days','7','--max-chunks','1','--max-sources','40','--timezone','Europe/London','--project','project']);const bigquery={query:async()=>{events.push('write');return[[]];}};await assert.rejects(runBackfill({options,bigquery,query:async()=>{events.push('parse');if(events.filter(x=>x==='parse').length===2)throw new Error('parse rejected');return{columns:[],rows:[]};}}),/parse rejected/);assert.deepEqual(events,['parse','parse']);});
test('source cardinality collapses deterministically and preserves totals',()=>{const rows=Array.from({length:6},(_,i)=>({day:'2025-11-16',session_device_type:'mobile',referrer_source:`s${i}`,sessions:i+1,sessions_that_completed_checkout:1,conversion_rate:1/(i+1),sessions_with_cart_additions:1,sessions_that_reached_checkout:1}));const out=normalizeRows(rows,{withSource:true,maxSourcesPerDeviceDay:5,timezone:'Europe/London'});assert.equal(out.length,6);assert.equal(out.find(r=>r.referrer_source==='__other__').sessions,1);assert.equal(out.reduce((n,r)=>n+r.sessions,0),21);validateRows(out,'2025-11-16','2025-11-16');});
test('backfill is resumable and tightly bounded',()=>{const options=parseArgs(['--start','2025-11-16','--end','2025-12-31','--chunk-days','7','--max-chunks','2','--resume-after','2025-11-22','--timezone','Europe/London']);assert.deepEqual(plan(options),[{startDate:'2025-11-23',endDate:'2025-11-29'},{startDate:'2025-11-30',endDate:'2025-12-06'}]);assert.throws(()=>parseArgs(['--start','2025-11-16','--end','2025-12-31','--chunk-days','30']),/Bounds/);});
test('impossible native funnel counts fail closed',()=>{assert.throws(()=>validateRows(normalizeRows([{day:'2025-11-16',session_device_type:'desktop',sessions:1,sessions_that_completed_checkout:2}],{timezone:'Europe/London'}),'2025-11-16','2025-11-16'),/Impossible/);});
test('readiness reports configuration names without exposing values',()=>{const options=parseArgs(['--start','2025-11-20','--end','2025-11-26','--timezone','Europe/London']);const result=readiness({env:{SHOPIFY_SHOP:'secret-shop'},options});assert.deepEqual(result,{ready:false,missing:['SHOPIFY_CLIENT_ID','SHOPIFY_CLIENT_SECRET']});assert.doesNotMatch(JSON.stringify(result),/secret-shop/);});
