import test from 'node:test';import assert from 'node:assert/strict';
import {TikTokClient} from '../tiktok/client.js';import {probe,collect} from '../tiktok/collect.js';import {observations,historicalObservations,windows} from '../tiktok/contract.js';import {TikTokStore} from '../tiktok/storage.js';import {socialContextPatch} from '../oracle/social-context.js';import {createOracleToolDefinitions} from '../oracle/tool-registry.js';
const response=(data,status=200,code=0)=>({ok:status===200,status,headers:{get:()=>null},json:async()=>({code,data,request_id:'fixture-request'})});
const client=fetchImpl=>new TikTokClient({token:'private-test-token',businessId:'openid',fetchImpl,sleep:async()=>{}});
test('read allowlist, invalid and expired credentials, private exceptions',async()=>{const c=client(async()=>response({},200,40105));await assert.rejects(c.request('business/get/'),{code:'TOKEN_EXPIRED_OR_INVALID'});await assert.rejects(c.request('business/video/publish/'),{code:'ENDPOINT_PROHIBITED'});const bad=client(async()=>{throw new Error('secret');});await assert.rejects(bad.request('business/get/'),e=>e.code==='TRANSPORT_FAILED'&&!e.message.includes('secret'));});
test('native and HTTP rate limits retry within bounds',async()=>{let calls=0;const c=client(async()=>++calls<3?response({},429,40100):response({username:'x'}));await c.request('business/get/');assert.equal(calls,3);const d=client(async()=>response({},500,51065));await assert.rejects(d.request('business/get/'),{code:'RETRIES_EXHAUSTED'});assert.equal(d.calls,4);});
test('probe verifies account and actual catalogue response',async()=>{const c=client(async url=>response(String(url).includes('video/list')?{videos:[{item_id:'7000000000000000001',create_time:'2018-01-01 00:00:00'}],has_more:false,cursor:0}:{username:'thegreatfroglondon'}));assert.equal((await probe(c)).catalogue_probe_count,1);await assert.rejects(probe(client(async()=>response({username:'other'}))),{code:'ACCOUNT_IDENTITY_MISMATCH'});});
test('zero, missing, native snapshots and native dated history remain distinct',()=>{const args={data:{likes:0},fields:['likes','reach'],kind:'lifetime_post_counter',accountId:'a',runId:'r',observedAt:'2026-10-07',endpoint:'business/video/list/'};const r=observations(args);assert.equal(r[0].value,0);assert.equal(r[1].value,null);assert.equal(r[1].availability,'missing');const h=historicalObservations({...args,data:{metrics:[{date:'2020-01-01',likes:4}]},fields:['likes'],start:'2020-01-01',end:'2020-01-07'});assert.equal(h[1].evidence_kind,'native_dated_observation');assert.equal(h[1].applied_start,'2020-01-01');assert.equal(h[1].requested_end,'2020-01-07');assert.equal(h[1].reporting_timezone,null);});
class MemoryStore{states=new Map();rows=new Map();async checkpoint(a,i,g){return this.states.get(g);}async save(a,i,g,s,rows=[]){this.states.set(g,structuredClone(s));for(const r of rows)this.rows.set(r.evidence_id,r);}}
test('complete pagination includes old posts; failure isolation; resume is idempotent',async()=>{const store=new MemoryStore();let calls=0;const c={request:async(path,p)=>{calls++;if(path==='business/get/')return {data:{username:'thegreatfroglondon',metrics:[{date:'2020-01-01',followers_count:42}]}};if(p.fields.includes('reach'))throw Object.assign(new Error('hidden'),{code:'PERMISSION_DENIED'});const last=Number(p.cursor)===1;return {data:{videos:[{item_id:last?'old':'new',create_time:last?'2017-01-01 00:00:00':'2026-10-06 00:00:00',likes:0}],has_more:!last,cursor:last?2:1}};}};const args={client:c,store,accountId:'a',importId:'preserve',start:'2020-01-01',end:'2020-01-07'};const r=await collect(args);assert.equal(r.catalogue.complete,true);assert.equal(r.catalogue.post_count,2);assert.equal(r.catalogue.earliest_native,'2017-01-01 00:00:00');assert.ok(r.failures.some(f=>f.grain==='posts:reach'));const count=store.rows.size,first=calls;await collect(args);assert.equal(store.rows.size,count);assert.equal(calls,first);});
test('warehouse promotion uses atomic checkpoints, lease fence and insert-only merge',async()=>{const queries=[];const store=new TikTokStore({project:'gf-full-data',bigquery:{query:async q=>{queries.push(q);return [[]];}}});store.location='EU';await store.save('a','r','catalogue',{cursor:1},[]);assert.match(queries[0].query,/BEGIN TRANSACTION/);assert.match(queries[0].query,/lease_until>CURRENT_TIMESTAMP/);assert.match(queries[0].query,/WHEN NOT MATCHED THEN INSERT/);assert.doesNotMatch(queries[0].query,/DELETE|TRUNCATE/);assert.equal(queries[0].location,'EU');assert.deepEqual(queries[0].types.rows,['STRING']);});
test('bounded windows retain full historical request without post cutoff',()=>{const w=windows('2017-01-01','2017-01-15');assert.equal(w.length,3);assert.equal(w.at(-1).start,'2017-01-01');assert.equal(w[0].end,'2017-01-15');});
test('Oracle routes TikTok audiences and follower questions through shared scope',()=>{const base={limit:100};const p=socialContextPatch(base,'Show TikTok audience demographics in September 2026',new Date('2026-10-07'));assert.equal(p.tool_route,'get_tiktok_performance');assert.equal(p.social_scope.scope,'account');assert.equal(p.social_scope.metric,'audience_countries');assert.ok(createOracleToolDefinitions().some(t=>t.name==='get_tiktok_performance'));assert.equal(socialContextPatch(base,'How has TikTok influenced sales this year?',new Date()),null);});
test('pagination cycles and malformed pages are failed evidence, not completion',async()=>{const store=new MemoryStore();const c={request:async(path,p)=>path==='business/get/'?{data:{}}:{data:{videos:[],has_more:true,cursor:0}}};const r=await collect({client:c,store,accountId:'a',importId:'r',start:'2020-01-01',end:'2020-01-01'});assert.equal(r.catalogue.complete,false);assert.ok(r.failures.some(x=>x.error_code==='PAGINATION_CYCLE'));});
test('interruption resumes from the last committed page',async()=>{const store=new MemoryStore();let interrupted=true;const c={request:async(path,p)=>{if(path==='business/get/')return {data:{}};if(p.cursor===1&&interrupted){interrupted=false;throw Object.assign(new Error('expired'),{code:'TOKEN_EXPIRED_OR_INVALID'});}return {data:{videos:[{item_id:p.cursor===1?'old':'new'}],has_more:p.cursor===0,cursor:1}};}};const args={client:c,store,accountId:'a',importId:'r',start:'2020-01-01',end:'2020-01-01'};await assert.rejects(collect(args),{code:'TOKEN_EXPIRED_OR_INVALID'});assert.equal(store.states.get('catalogue').cursor,1);const r=await collect(args);assert.equal(r.catalogue.post_count,2);assert.equal(r.catalogue.complete,true);});
test('shared Oracle charts and owned download retain snapshot/historical distinction',async()=>{const {answerSocialAnalysis}=await import('../oracle/social-analysis.js');const saved=new Map();const context={requested_subject:'tiktok',tool_route:'get_tiktok_performance',start_date:'2026-09-01',end_date:'2026-09-30',limit:100,output_preference:'xlsx',social_scope:{account_id:null,scope:'account',metric:'followers_count',media_type:null}};const rows=['2026-09-01','2026-09-02'].map((date,i)=>({account_id:'a',resource_id:'a',metric:'followers_count',unit:'count',value:10+i,evidence_kind:'native_dated_observation',applied_start:date,availability:'available',retrieved_at:'2026-10-07'}));const result=await answerSocialAnalysis({context,provider:async()=>({rows,coverage:{complete:false},definitions:{},limitations:['No sales attribution.']}),exportStore:{get:async id=>saved.get(id),put:async(id,owner,r)=>saved.set(id,r)},exportOwner:'owner',requestId:'request'});assert.match(result.answer,/lifetime snapshots/);assert.match(result.artifact.filename,/tiktok/);assert.ok(result.artifact.download_url);assert.equal(result.evidence.subject,'tiktok');assert.equal(result.evidence.chart_datasets[0].shape,'time_series');assert.equal(saved.size,1);});
test('conflicting lock acquisition fails before promotion',async()=>{const store=new TikTokStore({project:'gf-full-data',bigquery:{query:async()=>{throw Object.assign(new Error('concurrent collector'),{code:409});}}});await assert.rejects(store.lock(),{code:409});});
test('Oracle native period queries preserve separate requested windows and actual dataset location',async()=>{const {createTikTokService}=await import('../oracle/tiktok.js');const queries=[];const bigquery={dataset:()=>({getMetadata:async()=>[{location:'EU'}]}),query:async q=>{queries.push(q);return [[]];}};await createTikTokService({bigquery,project:'gf-full-data'})('get_tiktok_performance',{start_date:'2026-09-01',end_date:'2026-09-30',account_id:null,scope:'account',metric:'followers_count',limit:100});assert.equal(queries[0].location,'EU');assert.match(queries[0].query,/IF\(evidence_kind='native_period_unverified',requested_start,NULL\)/);assert.match(queries[0].query,/evidence_kind='native_period_unverified' AND requested_start<=@end/);assert.doesNotMatch(queries[0].query,/SUM\(/);});
