#!/usr/bin/env node
import {readFile} from 'node:fs/promises';
import {createBigQueryClient} from '../bigquery/client.js';
import {createKlaviyoClient,redactKlaviyo} from './client.js';
import {PILOT,REPORT_STATISTICS,reportBody,parseMetricIds,resolveReportWindow} from './discovery.js';
import {collectMetadata,joinMetadata} from './metadata.js';
import {BigQuery} from '@google-cloud/bigquery';

export const DATASET='klaviyo';
export const SCHEMA='report_kind STRING NOT NULL, channel STRING NOT NULL, entity_id STRING NOT NULL, entity_name STRING, message_id STRING NOT NULL, report_start TIMESTAMP NOT NULL, report_end TIMESTAMP NOT NULL, report_period_semantics STRING NOT NULL, conversion_metric_id STRING NOT NULL, metric_provenance STRING NOT NULL, currency STRING NOT NULL, reporting_timezone STRING NOT NULL, api_revision STRING NOT NULL, attribution_settings STRING NOT NULL, recipients INT64, delivered INT64, opens INT64, opens_unique INT64, clicks INT64, clicks_unique INT64, conversions FLOAT64, conversion_value NUMERIC, bounced INT64, unsubscribes INT64, spam_complaints INT64, retrieved_at TIMESTAMP NOT NULL';
const safe=v=>{if(!/^[A-Za-z0-9_-]+$/.test(v))throw new Error('Invalid BigQuery identifier');return v};
const ATTRIBUTION_KEYS=['email_open_window_days','email_click_window_days','sms_delivery_window_hours','sms_click_window_days','exclude_transactional_messages','exclude_email_bot_clicks','exclude_sms_bot_clicks','exclude_apple_mpp_opens'];
export function serializeAttributionSettings(value){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length!==ATTRIBUTION_KEYS.length||!ATTRIBUTION_KEYS.every(k=>Object.hasOwn(value,k)))throw new Error('Approved discovery manifest has invalid attribution_settings structure');for(const key of ATTRIBUTION_KEYS.slice(0,4))if(!Number.isFinite(value[key])||value[key]<=0)throw new Error(`Invalid attribution setting: ${key}`);for(const key of ATTRIBUTION_KEYS.slice(4))if(typeof value[key]!=='boolean')throw new Error(`Invalid attribution setting: ${key}`);return JSON.stringify(Object.fromEntries(ATTRIBUTION_KEYS.map(k=>[k,value[k]])));}
export function requireGate(manifest,{timezone,currency,metricIds}){if(manifest?.gate_version!==1||manifest?.approved_for_pilot!==true)throw new Error('Production discovery gate is not approved; historical collection is blocked');if(manifest.timezone!==timezone||manifest.currency!==currency)throw new Error('Discovery gate account settings do not match collection settings');if(!Array.isArray(metricIds)||metricIds.length===0)throw new Error('At least one conversion metric must be selected');const selected=[...new Set(metricIds)].sort(),approved=[...new Set(manifest.approved_metric_ids||[])].sort();if(JSON.stringify(selected)!==JSON.stringify(approved))throw new Error('Selected conversion metrics do not exactly match the reviewed manifest');if(manifest.pilot?.start!==PILOT.start||manifest.pilot?.end!==PILOT.end)throw new Error('Discovery gate does not approve the exact pilot window');for(const id of metricIds)for(const kind of ['campaign','flow'])if(!manifest.probes?.some(p=>p.metric_id===id&&p.kind===kind&&p.status==='available'))throw new Error(`Metric ${id} did not pass ${kind} discovery`);serializeAttributionSettings(manifest.attribution_settings);return true;}
export function requireAccountConfig(config,{timezone,currency,metricIds}){if(config?.configuration_version!==1)throw new Error('Unsupported Klaviyo account configuration');if(config.timezone!==timezone||config.currency!==currency)throw new Error('Reviewed account configuration does not match collection settings');const selected=[...new Set(metricIds||[])].sort(),approved=[...new Set(config.approved_metric_ids||[])].sort();if(!selected.length||JSON.stringify(selected)!==JSON.stringify(approved))throw new Error('Selected conversion metrics do not exactly match reviewed durable configuration');serializeAttributionSettings(config.attribution_settings);if(!config.review?.reviewed_at||!config.review?.basis)throw new Error('Durable configuration review provenance is required');return true;}
function val(stats,name){if(!Object.hasOwn(stats||{},name)||stats[name]===null)throw new Error(`Missing ${name} statistic`);const n=Number(stats[name]);if(!Number.isFinite(n)||n<0)throw new Error(`Invalid ${name} statistic`);return n;}
export function normalizeReport(payload,{kind,metricId,currency,timezone,revision,retrievedAt,attributionSettings,metricProvenance='Klaviyo metric ID; integration population preserved',start=PILOT.start,end=PILOT.end}){const results=payload?.data?.attributes?.results;if(!Array.isArray(results))throw new Error('Klaviyo report response has no results array');const window=resolveReportWindow({timezone,start,end}),entityKey=`${kind}_id`,messageKey=`${kind}_message_id`,settings=serializeAttributionSettings(attributionSettings);return results.map(item=>{const d=item?.groupings,s=item?.statistics;if(!d||typeof d!=='object'||!s||typeof s!=='object')throw new Error('Klaviyo report result does not match the reviewed grouping/statistics structure');const entityId=String(d[entityKey]??'').trim(),messageId=String(d[messageKey]??'').trim();if(!entityId||!messageId)throw new Error(`Klaviyo ${kind} report result has a blank persistence ID`);return {report_kind:kind,channel:'email',entity_id:entityId,entity_name:null,message_id:messageId,report_start:window.startInstant,report_end:window.endInstant,report_period_semantics:'Klaviyo attribution report for messages in the requested report window; not asserted to be order-occurrence calendar dates',conversion_metric_id:metricId,metric_provenance:metricProvenance,currency,reporting_timezone:timezone,api_revision:revision,attribution_settings:settings,...Object.fromEntries(REPORT_STATISTICS[kind].map(k=>[k,val(s,k)])),retrieved_at:retrievedAt};});}
async function collectReportPages({client,kind,metricId,timezone,start=PILOT.start,end=PILOT.end,maxPages=8}){const results=[];const cursors=new Set();let pageCursor;for(let page=1;page<=maxPages;page++){const payload=await client.request(`/api/${kind}-values-reports`,{method:'POST',body:reportBody(kind,metricId,{timezone,start,end,pageCursor})}),attributes=payload?.data?.attributes;if(!Array.isArray(attributes?.results))throw new Error('Klaviyo report response has no results array');results.push(...attributes.results);const next=attributes.next_cursor;if(next===null||next===undefined)return {data:{attributes:{results}}};if(typeof next!=='string'||!next.trim()||cursors.has(next))throw new Error('Invalid Klaviyo report pagination cursor');cursors.add(next);pageCursor=next;}throw Object.assign(new Error(`Klaviyo report pagination bound exceeded (${maxPages} pages); collection is incomplete`),{code:'PAGINATION_BOUND'});}
function assertUnique(rows){const seen=new Set();for(const row of rows){const key=[row.report_kind,row.entity_id,row.message_id,row.report_start,row.report_end,row.conversion_metric_id].join('\u0000');if(seen.has(key))throw new Error('Duplicate Klaviyo result at the persistence grain');seen.add(key);}}
export async function collectPilot({client,manifest,revision,timezone,currency,metricIds,retrievedAt=new Date().toISOString(),maxReportPages=8}){requireGate(manifest,{timezone,currency,metricIds});const rows=[];const failures=[];for(const metricId of metricIds)for(const kind of ['campaign','flow'])try{const payload=await collectReportPages({client,kind,metricId,timezone,maxPages:maxReportPages});rows.push(...normalizeReport(payload,{kind,metricId,currency,timezone,revision,retrievedAt,attributionSettings:manifest.attribution_settings}));}catch(error){failures.push({kind,metric_id:metricId,code:error.code||error.name,message:'Retrieval failed; detail redacted'});}if(failures.length)throw Object.assign(new Error('Klaviyo pilot partially failed or was incomplete; no rows were promoted'),{code:'PARTIAL_FAILURE',failures});assertUnique(rows);return rows;}
export function validateBoundedWindow({start,end,maximumDays=92}){const window=resolveReportWindow({timezone:'UTC',start,end}),days=(new Date(window.endInstant)-new Date(window.startInstant))/86400000;if(days>maximumDays)throw Object.assign(new Error(`Report window exceeds ${maximumDays} day bound`),{code:'WINDOW_BOUND'});return window;}
export async function collectWindow({client,config,revision,timezone=config?.timezone,currency=config?.currency,metricIds=config?.approved_metric_ids,start,end,retrievedAt=new Date().toISOString(),maxReportPages=8,includeContent=false}){requireAccountConfig(config,{timezone,currency,metricIds});validateBoundedWindow({start,end,maximumDays:config.refresh_policy?.maximum_manual_days||92});const rows=[],failures=[],definitions=new Map((config.metric_definitions||[]).map(x=>[x.metric_id,x]));for(const metricId of metricIds)for(const kind of ['campaign','flow'])try{const payload=await collectReportPages({client,kind,metricId,timezone,start,end,maxPages:maxReportPages}),definition=definitions.get(metricId);rows.push(...normalizeReport(payload,{kind,metricId,metricProvenance:definition?`${definition.integration}:${definition.name}; ${definition.evidence}`:undefined,currency,timezone,revision,retrievedAt,attributionSettings:config.attribution_settings,start,end}));}catch(error){failures.push({kind,metric_id:metricId,stage:`report:${kind}`,endpoint:`/api/${kind}-values-reports`,http_status:error.status||null,code:error.code||error.name,errors:error.validationErrors||[],message:'Retrieval failed; sanitized details attached'});}let metadata=[];try{metadata=await collectMetadata({client,retrievedAt,includeContent});}catch(error){failures.push({kind:'metadata',stage:error.stage||'metadata:unknown',endpoint:error.endpoint||null,http_status:error.status||null,code:error.code||error.name,errors:error.validationErrors||[],message:'Retrieval failed; sanitized details attached'});}if(failures.length)throw Object.assign(new Error('Klaviyo refresh partially failed or was incomplete; no rows were promoted'),{code:'PARTIAL_FAILURE',failures});const joined=joinMetadata(rows,metadata);assertUnique(joined);return {rows:joined,metadata,window:resolveReportWindow({timezone,start,end}),retrieved_at:retrievedAt};}
export function rollingWindow({now=new Date(),timezone,rollingDays=7,attributionLagDays=5}){if(!timezone)throw new Error('timezone is required');const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now).filter(part=>part.type!=='literal').map(part=>[part.type,part.value])),end=new Date(Date.UTC(+parts.year,+parts.month-1,+parts.day-attributionLagDays+1)),start=new Date(end);start.setUTCDate(start.getUTCDate()-rollingDays);return {start:start.toISOString().slice(0,10)+'T00:00:00',end:end.toISOString().slice(0,10)+'T00:00:00'};}
const reportJsonColumns=[['report_kind','STRING'],['channel','STRING'],['entity_id','STRING'],['entity_name','STRING'],['message_id','STRING'],['report_start','TIMESTAMP'],['report_end','TIMESTAMP'],['report_period_semantics','STRING'],['conversion_metric_id','STRING'],['metric_provenance','STRING'],['currency','STRING'],['reporting_timezone','STRING'],['api_revision','STRING'],['attribution_settings','STRING'],['recipients','INT64'],['delivered','INT64'],['opens','INT64'],['opens_unique','INT64'],['clicks','INT64'],['clicks_unique','INT64'],['conversions','FLOAT64'],['conversion_value','NUMERIC'],['bounced','INT64'],['unsubscribes','INT64'],['spam_complaints','INT64'],['retrieved_at','TIMESTAMP']];
const metadataJsonColumns=[['entity_kind','STRING'],['entity_id','STRING'],['entity_name','STRING'],['status','STRING'],['send_time','STRING'],['send_time_semantics','STRING'],['message_ids','JSON_STRING'],['subject','STRING'],['preview_text','STRING'],['destination_links','JSON_STRING'],['source_endpoint','STRING'],['retrieved_at','TIMESTAMP'],['is_sent','BOOL']];
const jsonProjection=columns=>columns.map(([name,type])=>type==='STRING'?`JSON_VALUE(item, '$.${name}') AS ${name}`:type==='JSON_STRING'?`SAFE.PARSE_JSON(JSON_VALUE(item, '$.${name}')) AS ${name}`:`SAFE_CAST(JSON_VALUE(item, '$.${name}') AS ${type}) AS ${name}`).join(',\n');

/**
 * One query job materializes both bounded JSON payloads as temporary tables and
 * promotes reports and metadata in one transaction. Query parameters are not
 * Storage Write API streaming inserts, so subsequent DML cannot encounter rows
 * that this refresh placed in a streaming buffer.
 */
export function persistenceQuery(project,dataset=DATASET,{promoteStatus=false,promoteCoverage=false}={}){safe(project);safe(dataset);const reportTable=`\`${project}.${dataset}.message_performance\``,metadataTable=`\`${project}.${dataset}.entity_metadata\``;return `
CREATE TEMP TABLE incoming_reports AS SELECT ${jsonProjection(reportJsonColumns)} FROM UNNEST(JSON_QUERY_ARRAY(@report_payload)) item;
CREATE TEMP TABLE incoming_metadata AS SELECT ${jsonProjection(metadataJsonColumns)} FROM UNNEST(JSON_QUERY_ARRAY(@metadata_payload)) item;
ASSERT (SELECT COUNT(*) FROM incoming_reports)=@report_count AS 'KLAVIYO_REPORT_PAYLOAD_COUNT_MISMATCH';
ASSERT (SELECT COUNT(*) FROM incoming_metadata)=@metadata_count AS 'KLAVIYO_METADATA_PAYLOAD_COUNT_MISMATCH';
BEGIN TRANSACTION;
MERGE ${reportTable} T USING incoming_reports S ON T.report_kind=S.report_kind AND T.entity_id=S.entity_id AND T.message_id=S.message_id AND T.report_start=S.report_start AND T.report_end=S.report_end AND T.conversion_metric_id=S.conversion_metric_id
WHEN MATCHED THEN UPDATE SET entity_name=S.entity_name,channel=S.channel,report_period_semantics=S.report_period_semantics,metric_provenance=S.metric_provenance,recipients=S.recipients,delivered=S.delivered,opens=S.opens,opens_unique=S.opens_unique,clicks=S.clicks,clicks_unique=S.clicks_unique,conversions=S.conversions,conversion_value=S.conversion_value,bounced=S.bounced,unsubscribes=S.unsubscribes,spam_complaints=S.spam_complaints,currency=S.currency,reporting_timezone=S.reporting_timezone,api_revision=S.api_revision,attribution_settings=S.attribution_settings,retrieved_at=S.retrieved_at
WHEN NOT MATCHED THEN INSERT ROW;
MERGE ${metadataTable} T USING incoming_metadata S ON T.entity_kind=S.entity_kind AND T.entity_id=S.entity_id
WHEN MATCHED THEN UPDATE SET entity_name=S.entity_name,status=S.status,send_time=S.send_time,send_time_semantics=S.send_time_semantics,message_ids=S.message_ids,subject=S.subject,preview_text=S.preview_text,destination_links=S.destination_links,source_endpoint=S.source_endpoint,retrieved_at=S.retrieved_at,is_sent=S.is_sent
WHEN NOT MATCHED THEN INSERT ROW;
DELETE FROM ${metadataTable} WHERE STRUCT(entity_kind,entity_id,retrieved_at) NOT IN (SELECT AS STRUCT entity_kind,entity_id,MAX(retrieved_at) FROM ${metadataTable} GROUP BY 1,2);
${promoteStatus?`UPDATE \`${project}.${dataset}.sync_status\` SET status='succeeded',completed_at=CURRENT_TIMESTAMP(),retrieved_at=@retrieved_at,row_count=@report_count WHERE run_id=@run_id AND status='running';
ASSERT @@row_count=1 AS 'KLAVIYO_REFRESH_STATUS_NOT_RUNNING';`:''}
${promoteCoverage?`MERGE \`${project}.${dataset}.window_coverage\` T USING (SELECT @report_start report_start,@report_end report_end,@reporting_timezone reporting_timezone,@retrieved_at retrieved_at,@report_count row_count,@run_id run_id) S ON T.report_start=S.report_start AND T.report_end=S.report_end AND T.reporting_timezone=S.reporting_timezone
WHEN MATCHED THEN UPDATE SET status='collected',row_count=S.row_count,retrieved_at=S.retrieved_at,run_id=S.run_id,failure_class=NULL
WHEN NOT MATCHED THEN INSERT (report_start,report_end,reporting_timezone,status,row_count,retrieved_at,run_id,failure_class) VALUES (S.report_start,S.report_end,S.reporting_timezone,'collected',S.row_count,S.retrieved_at,S.run_id,NULL);`:''}
COMMIT TRANSACTION;`;}

export async function assertBuffersReady({bigquery,project,dataset=DATASET}){safe(project);safe(dataset);const tables=bigquery.dataset(dataset,{projectId:project}),buffers={};for(const name of ['message_performance','entity_metadata']){const [metadata]=await tables.table(name).getMetadata();buffers[name]=metadata.streamingBuffer||null;}const blocked=Object.entries(buffers).filter(([,buffer])=>buffer!==null).map(([table,streaming_buffer])=>({table,streaming_buffer}));if(blocked.length)throw Object.assign(new Error(`Klaviyo recovery is blocked by BigQuery streaming buffers: ${blocked.map(x=>x.table).join(', ')}`),{code:'KLAVIYO_STREAMING_BUFFER_BLOCKED',recovery_status:'waiting_for_streaming_buffers',buffers});return buffers;}

export async function persist({bigquery,project,rows,metadata=[],dataset=DATASET,runId=null,retrievedAt=null,coverage=null}){safe(project);safe(dataset);if(Boolean(runId)!==Boolean(retrievedAt))throw new Error('runId and retrievedAt must be supplied together');if(coverage&&!runId)throw new Error('Coverage promotion requires a run ledger entry');await bigquery.query({query:`CREATE SCHEMA IF NOT EXISTS \`${project}.${dataset}\` OPTIONS(location="US"); CREATE TABLE IF NOT EXISTS \`${project}.${dataset}.message_performance\` (${SCHEMA}) PARTITION BY DATE(report_start) OPTIONS(partition_expiration_days=2555); CREATE TABLE IF NOT EXISTS \`${project}.${dataset}.entity_metadata\` (entity_kind STRING NOT NULL,entity_id STRING NOT NULL,entity_name STRING,status STRING,send_time STRING,send_time_semantics STRING,message_ids JSON,subject STRING,preview_text STRING,destination_links JSON,source_endpoint STRING NOT NULL,retrieved_at TIMESTAMP NOT NULL,is_sent BOOL); CREATE TABLE IF NOT EXISTS \`${project}.${dataset}.window_coverage\` (report_start TIMESTAMP NOT NULL,report_end TIMESTAMP NOT NULL,reporting_timezone STRING NOT NULL,status STRING NOT NULL,row_count INT64,retrieved_at TIMESTAMP,run_id STRING,failure_class STRING)`});await assertBuffersReady({bigquery,project,dataset});const params={report_payload:JSON.stringify(rows),metadata_payload:JSON.stringify(metadata),report_count:rows.length,metadata_count:metadata.length},types={report_payload:'STRING',metadata_payload:'STRING',report_count:'INT64',metadata_count:'INT64'};if(runId){Object.assign(params,{run_id:runId,retrieved_at:BigQuery.timestamp(retrievedAt)});Object.assign(types,{run_id:'STRING',retrieved_at:'TIMESTAMP'});}if(coverage){Object.assign(params,{report_start:BigQuery.timestamp(coverage.startInstant),report_end:BigQuery.timestamp(coverage.endInstant),reporting_timezone:coverage.timezone});Object.assign(types,{report_start:'TIMESTAMP',report_end:'TIMESTAMP',reporting_timezone:'STRING'});}await bigquery.query({query:persistenceQuery(project,dataset,{promoteStatus:Boolean(runId),promoteCoverage:Boolean(coverage)}),params,types});return {rows:rows.length,metadata_rows:metadata.length,mode:'transactional_query_upsert',idempotent_key:['report_kind','entity_id','message_id','report_start','report_end','conversion_metric_id']};}
export async function main({env=process.env}={}){const manifest=JSON.parse(await readFile(env.KLAVIYO_DISCOVERY_MANIFEST,'utf8'));const metricIds=parseMetricIds(env.KLAVIYO_CONVERSION_METRIC_IDS),client=createKlaviyoClient({apiKey:env.KLAVIYO_PRIVATE_API_KEY,revision:env.KLAVIYO_API_REVISION,maxCalls:Number(env.KLAVIYO_MAX_API_CALLS||40),timeoutMs:Number(env.KLAVIYO_TIMEOUT_MS||15000)}),rows=await collectPilot({client,manifest,revision:env.KLAVIYO_API_REVISION,timezone:env.KLAVIYO_ACCOUNT_TIMEZONE,currency:env.KLAVIYO_ACCOUNT_CURRENCY,metricIds}),{bigquery,project}=createBigQueryClient(env);console.log(JSON.stringify(await persist({bigquery,project,rows})));}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(e=>{console.error(JSON.stringify({status:'error',code:e.code||e.name,message:redactKlaviyo(e.message),failures:e.failures}));process.exitCode=1});
