#!/usr/bin/env node
import {readFile} from 'node:fs/promises';
import {createBigQueryClient} from '../bigquery/client.js';
import {createKlaviyoClient,redactKlaviyo} from './client.js';
import {PILOT,REPORT_STATISTICS,reportBody,parseMetricIds} from './discovery.js';

export const DATASET='klaviyo';
export const SCHEMA='report_kind STRING NOT NULL, channel STRING NOT NULL, entity_id STRING NOT NULL, entity_name STRING, message_id STRING NOT NULL, report_start TIMESTAMP NOT NULL, report_end TIMESTAMP NOT NULL, report_period_semantics STRING NOT NULL, conversion_metric_id STRING NOT NULL, metric_provenance STRING NOT NULL, currency STRING NOT NULL, reporting_timezone STRING NOT NULL, api_revision STRING NOT NULL, attribution_settings STRING NOT NULL, recipients INT64, delivered INT64, opens INT64, opens_unique INT64, clicks INT64, clicks_unique INT64, conversions FLOAT64, conversion_value NUMERIC, bounced INT64, unsubscribes INT64, spam_complaints INT64, retrieved_at TIMESTAMP NOT NULL';
const safe=v=>{if(!/^[A-Za-z0-9_-]+$/.test(v))throw new Error('Invalid BigQuery identifier');return v};
export function requireGate(manifest,{timezone,currency,metricIds}){if(manifest?.gate_version!==1||manifest?.approved_for_pilot!==true)throw new Error('Production discovery gate is not approved; historical collection is blocked');if(manifest.timezone!==timezone||manifest.currency!==currency)throw new Error('Discovery gate account settings do not match collection settings');for(const id of metricIds)if(!manifest.probes?.some(p=>p.metric_id===id&&p.status==='available'))throw new Error(`Metric ${id} did not pass discovery`);if(!manifest.attribution_settings)throw new Error('Approved discovery manifest must record attribution_settings');return true;}
function val(stats,name){if(stats?.[name]===undefined||stats?.[name]===null)return null;const n=Number(stats[name]);if(!Number.isFinite(n)||n<0)throw new Error(`Invalid ${name} statistic`);return n;}
export function normalizeReport(payload,{kind,metricId,currency,timezone,revision,retrievedAt,attributionSettings="unknown"}){const results=payload?.data?.attributes?.results;if(!Array.isArray(results))throw new Error('Klaviyo report response has no results array');return results.map(item=>{const d=item.dimensions||item.groupings||{},s=item.statistics||item.stats||item;return {report_kind:kind,channel:'email',entity_id:String(d.campaign_id||d.flow_id||item.id||''),entity_name:d.campaign_name||d.flow_name||null,message_id:String(d.message_id||''),report_start:`${PILOT.start}Z`,report_end:`${PILOT.end}Z`,report_period_semantics:'Klaviyo attribution report for messages in the requested report window; not asserted to be order-occurrence calendar dates',conversion_metric_id:metricId,metric_provenance:'Klaviyo metric ID; integration population preserved',currency,reporting_timezone:timezone,api_revision:revision,attribution_settings:attributionSettings,...Object.fromEntries(REPORT_STATISTICS.map(k=>[k,val(s,k)])),retrieved_at:retrievedAt};});}
export async function collectPilot({client,manifest,revision,timezone,currency,metricIds,retrievedAt=new Date().toISOString()}){requireGate(manifest,{timezone,currency,metricIds});const rows=[];const failures=[];for(const metricId of metricIds)for(const kind of ['campaign','flow'])try{const payload=await client.request(`/api/${kind}-values-reports`,{method:'POST',body:reportBody(kind,metricId,{timezone})});rows.push(...normalizeReport(payload,{kind,metricId,currency,timezone,revision,retrievedAt,attributionSettings:manifest.attribution_settings}));}catch(error){failures.push({kind,metric_id:metricId,code:error.code||error.name,message:'Retrieval failed; detail redacted'});}if(failures.length)throw Object.assign(new Error('Klaviyo pilot partially failed; no rows were promoted'),{code:'PARTIAL_FAILURE',failures});return rows;}
export async function persist({bigquery,project,rows,dataset=DATASET}){safe(project);safe(dataset);await bigquery.query({query:`CREATE SCHEMA IF NOT EXISTS \`${project}.${dataset}\` OPTIONS(location="US"); CREATE TABLE IF NOT EXISTS \`${project}.${dataset}.message_performance\` (${SCHEMA}) PARTITION BY DATE(report_start) OPTIONS(partition_expiration_days=2555)`});const stage=`_pilot_${Date.now()}`;const table=bigquery.dataset(dataset,{projectId:project}).table(stage);try{await bigquery.query({query:`CREATE TABLE \`${project}.${dataset}.${stage}\` LIKE \`${project}.${dataset}.message_performance\` OPTIONS(expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(),INTERVAL 1 DAY))`});if(rows.length)await table.insert(rows);await bigquery.query({query:`MERGE \`${project}.${dataset}.message_performance\` T USING \`${project}.${dataset}.${stage}\` S ON T.report_kind=S.report_kind AND T.entity_id=S.entity_id AND T.message_id=S.message_id AND T.report_start=S.report_start AND T.report_end=S.report_end AND T.conversion_metric_id=S.conversion_metric_id WHEN MATCHED THEN UPDATE SET entity_name=S.entity_name, recipients=S.recipients,delivered=S.delivered,opens=S.opens,opens_unique=S.opens_unique,clicks=S.clicks,clicks_unique=S.clicks_unique,conversions=S.conversions,conversion_value=S.conversion_value,bounced=S.bounced,unsubscribes=S.unsubscribes,spam_complaints=S.spam_complaints,currency=S.currency,reporting_timezone=S.reporting_timezone,api_revision=S.api_revision,attribution_settings=S.attribution_settings,retrieved_at=S.retrieved_at WHEN NOT MATCHED THEN INSERT ROW`});}finally{await table.delete({ignoreNotFound:true}).catch(()=>{});}return {rows:rows.length,mode:'august_2026_pilot_only',idempotent_key:['report_kind','entity_id','message_id','report_start','report_end','conversion_metric_id']};}
export async function main({env=process.env}={}){const manifest=JSON.parse(await readFile(env.KLAVIYO_DISCOVERY_MANIFEST,'utf8'));const metricIds=parseMetricIds(env.KLAVIYO_CONVERSION_METRIC_IDS),client=createKlaviyoClient({apiKey:env.KLAVIYO_PRIVATE_API_KEY,revision:env.KLAVIYO_API_REVISION,maxCalls:Number(env.KLAVIYO_MAX_API_CALLS||40),timeoutMs:Number(env.KLAVIYO_TIMEOUT_MS||15000)}),rows=await collectPilot({client,manifest,revision:env.KLAVIYO_API_REVISION,timezone:env.KLAVIYO_ACCOUNT_TIMEZONE,currency:env.KLAVIYO_ACCOUNT_CURRENCY,metricIds}),{bigquery,project}=createBigQueryClient(env);console.log(JSON.stringify(await persist({bigquery,project,rows})));}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(e=>{console.error(JSON.stringify({status:'error',code:e.code||e.name,message:redactKlaviyo(e.message),failures:e.failures}));process.exitCode=1});
