import {BigQuery} from '@google-cloud/bigquery';
import {createProductClassificationService} from '../oracle/product-classification.js';
import {governedDecisionCtes} from '../oracle/product-mapping.js';
import {collectionClassificationDdl} from '../oracle/collection-classification.js';

export const CATALOGUE_DATASETS=Object.freeze([{dataset:'shopify_data',source:'shopify',store:'shopify'},{dataset:'metorik_uk',source:'woo',store:'ww'},{dataset:'metorik_us',source:'woo',store:'usd'},{dataset:'square_data',source:'square',store:'square'}]);
export const AUTHORITATIVE_FIELDS=Object.freeze(['product_type','tags','collections','collection','categories','category','attributes','vendor','item_metadata','catalogue_categories']);
export const quoteBigQueryIdentifier=value=>`\`${String(value).replace(/`/g,'``')}\``;
/** BigQuery requires AS between each expression and its STRUCT field alias. */
export function metadataStructSql(fields){if(!fields.length)return `'{}'`;return `TO_JSON_STRING(STRUCT(${fields.map(field=>`TO_JSON_STRING(${quoteBigQueryIdentifier(field)}) AS ${quoteBigQueryIdentifier(field)}`).join(', ')}))`}
export async function auditCatalogueMetadata(bigquery,project){const results=[];for(const config of CATALOGUE_DATASETS){const [rows]=await bigquery.query({query:`SELECT table_name,column_name,data_type FROM \`${project}.${config.dataset}.INFORMATION_SCHEMA.COLUMNS\` WHERE LOWER(column_name) IN UNNEST(@fields) OR REGEXP_CONTAINS(LOWER(table_name),r'(product|catalog|item)') ORDER BY table_name,column_name`,params:{fields:AUTHORITATIVE_FIELDS}});results.push({...config,available_fields:rows,usable_fields:rows.filter(x=>AUTHORITATIVE_FIELDS.includes(x.column_name.toLowerCase()))});}return results;}
export async function loadCatalogueEvidence(bigquery,project){const products=[];
  const [shopify]=await bigquery.query({query:`SELECT CONCAT('shopify:shopify:',p.product_id) source_product_ref,p.product_type,p.vendor,p.tags,ARRAY_AGG(IF(g.classification_value='collaboration',STRUCT(c.collection_id,c.title,n.classification_value),NULL) IGNORE NULLS) governed_collaborations FROM \`${project}.shopify_catalogue.products\` p LEFT JOIN \`${project}.shopify_catalogue.product_collections\` pc USING(product_id) LEFT JOIN \`${project}.shopify_catalogue.collections\` c USING(collection_id) LEFT JOIN \`${project}.commerce.collection_classifications\` g ON g.platform='shopify' AND g.collection_id=c.collection_id AND g.classification_type='collection_group' AND g.classification_value='collaboration' AND g.status='active' LEFT JOIN \`${project}.commerce.collection_classifications\` n ON n.platform='shopify' AND n.collection_id=c.collection_id AND n.classification_type='collaboration_name' AND n.status='active' GROUP BY p.product_id,p.product_type,p.vendor,p.tags`});for(const row of shopify)products.push({source_product_ref:row.source_product_ref,metadata:{product_type:row.product_type,vendor:row.vendor,tags:row.tags||[],governed_collaborations:row.governed_collaborations||[]}});
  const audit=await auditCatalogueMetadata(bigquery,project);for(const source of audit.filter(x=>x.source!=='shopify')){const byTable=new Map();for(const col of source.usable_fields){const a=byTable.get(col.table_name)||[];a.push(col.column_name);byTable.set(col.table_name,a)}for(const [table,fields] of byTable){const id=(source.available_fields.find(x=>x.table_name===table&&['product_id','id','item_id','catalog_object_id'].includes(x.column_name.toLowerCase()))||{}).column_name;if(!id)continue;const qi=quoteBigQueryIdentifier(id);const [rows]=await bigquery.query({query:`SELECT CAST(${qi} AS STRING) source_product_id,${metadataStructSql(fields)} metadata_json FROM \`${project}.${source.dataset}.${table.replace(/`/g,'``')}\` WHERE ${qi} IS NOT NULL`});for(const row of rows)products.push({source_product_ref:`${source.source}:${source.store}:${row.source_product_id}`,metadata:JSON.parse(row.metadata_json||'{}')})}}return products;}
async function main(){const project=process.env.GOOGLE_PROJECT_ID||'gf-full-data';if(!process.env.GOOGLE_SERVICE_ACCOUNT_JSON)throw new Error('Missing GOOGLE_SERVICE_ACCOUNT_JSON');const bigquery=new BigQuery({projectId:project,credentials:JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON)});await bigquery.query({query:collectionClassificationDdl(project)});const service=createProductClassificationService({bigquery,project,evidenceLoader:()=>loadCatalogueEvidence(bigquery,project),mappingLoader:async()=>{const [rows]=await bigquery.query({query:`WITH ${governedDecisionCtes(project,'map')} SELECT left_ref,right_ref,status,mapping_method FROM map_active`});return rows;}});console.log(JSON.stringify(await service.sync(),null,2));}
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href)main().catch(error=>{console.error(error);process.exitCode=1});
