import {BigQuery} from '@google-cloud/bigquery';
import {createProductClassificationService} from '../oracle/product-classification.js';
import {governedDecisionCtes} from '../oracle/product-mapping.js';

export const CATALOGUE_DATASETS=Object.freeze([{dataset:'shopify_data',source:'shopify',store:'shopify'},{dataset:'metorik_uk',source:'woo',store:'ww'},{dataset:'metorik_us',source:'woo',store:'usd'},{dataset:'square_data',source:'square',store:'square'}]);
export const AUTHORITATIVE_FIELDS=Object.freeze(['product_type','tags','collections','collection','categories','category','attributes','vendor','item_metadata','catalogue_categories']);
export async function auditCatalogueMetadata(bigquery,project){const results=[];for(const config of CATALOGUE_DATASETS){const [rows]=await bigquery.query({query:`SELECT table_name,column_name,data_type FROM \`${project}.${config.dataset}.INFORMATION_SCHEMA.COLUMNS\` WHERE LOWER(column_name) IN UNNEST(@fields) OR REGEXP_CONTAINS(LOWER(table_name),r'(product|catalog|item)') ORDER BY table_name,column_name`,params:{fields:AUTHORITATIVE_FIELDS}});results.push({...config,available_fields:rows,usable_fields:rows.filter(x=>AUTHORITATIVE_FIELDS.includes(x.column_name.toLowerCase()))});}return results;}
export async function loadCatalogueEvidence(bigquery,project){const audit=await auditCatalogueMetadata(bigquery,project),products=[];for(const source of audit){const byTable=new Map();for(const col of source.usable_fields){const a=byTable.get(col.table_name)||[];a.push(col.column_name);byTable.set(col.table_name,a)}for(const [table,fields] of byTable){const id=(source.available_fields.find(x=>x.table_name===table&&['product_id','id','item_id','catalog_object_id'].includes(x.column_name.toLowerCase()))||{}).column_name;if(!id)continue;const struct=fields.map(f=>`TO_JSON_STRING(${f}) ${f}`).join(',');const [rows]=await bigquery.query({query:`SELECT CAST(${id} AS STRING) source_product_id,TO_JSON_STRING(STRUCT(${struct})) metadata_json FROM \`${project}.${source.dataset}.${table}\` WHERE ${id} IS NOT NULL`});for(const row of rows)products.push({source_product_ref:`${source.source}:${source.store}:${row.source_product_id}`,metadata:JSON.parse(row.metadata_json||'{}')})}}return products;}
async function main(){const project=process.env.GOOGLE_PROJECT_ID||'gf-full-data';if(!process.env.GOOGLE_SERVICE_ACCOUNT_JSON)throw new Error('Missing GOOGLE_SERVICE_ACCOUNT_JSON');const bigquery=new BigQuery({projectId:project,credentials:JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON)});const service=createProductClassificationService({bigquery,project,evidenceLoader:()=>loadCatalogueEvidence(bigquery,project),mappingLoader:async()=>{const [rows]=await bigquery.query({query:`WITH ${governedDecisionCtes(project,'map')} SELECT left_ref,right_ref,status,mapping_method FROM map_active`});return rows;}});console.log(JSON.stringify(await service.sync(),null,2));}
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href)main().catch(error=>{console.error(error);process.exitCode=1});
