import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {BigQueryDate,BigQueryTimestamp} from '@google-cloud/bigquery';
export const identifier=v=>{if(!/^[A-Za-z0-9_-]+$/.test(v||''))throw new Error('Invalid BigQuery identifier');return v;};
const ads='account_id STRING,account_name STRING,report_date DATE,campaign_id STRING,campaign_name STRING,adset_id STRING,adset_name STRING,ad_id STRING,ad_name STRING,currency STRING,reporting_timezone STRING,spend NUMERIC,impressions INT64,clicks INT64,link_clicks INT64,outbound_clicks NUMERIC,landing_page_views NUMERIC,purchase_count NUMERIC,purchase_value NUMERIC,purchase_action_type STRING,actions_json STRING,action_values_json STRING,breakdown_json STRING,creative_id STRING,creative_json STRING,attribution_json STRING,attribution_contract_id STRING,action_report_time STRING,api_version STRING,requested_start DATE,requested_end DATE,observed_at TIMESTAMP';
export const SCHEMAS=Object.freeze({ad_daily:ads,country_daily:ads,placement_daily:ads,device_daily:ads,instagram_observations:'account_id STRING,resource_id STRING,media_type STRING,metric STRING,period STRING,metric_type STRING,timeframe STRING,evidence_kind STRING,paid_organic_scope STRING,availability STRING,definition STRING,value NUMERIC,breakdown_json STRING,native_json STRING,publication_at TIMESTAMP,permalink STRING,observed_at TIMESTAMP,report_date DATE,requested_start DATE,requested_end DATE,reporting_timezone STRING,api_version STRING,profile_key STRING',instagram_media:'account_id STRING,media_id STRING,media_type STRING,publication_at TIMESTAMP,permalink STRING,metadata_json STRING,observed_at TIMESTAMP,api_version STRING'});
export async function ensureMetaSchema(bigquery,project){identifier(project);await bigquery.query({query:`CREATE SCHEMA IF NOT EXISTS \`${project}.meta\`; ${Object.entries(SCHEMAS).map(([t,s])=>`CREATE TABLE IF NOT EXISTS \`${project}.meta.${t}\` (${s}) ${t.endsWith('_daily')?'PARTITION BY report_date':'PARTITION BY DATE(observed_at)'} CLUSTER BY account_id;`).join('\n')} CREATE TABLE IF NOT EXISTS \`${project}.meta.coverage\` (source STRING,account_id STRING,grain STRING,contract_id STRING,window_start DATE,window_end DATE,status STRING,run_id STRING,row_count INT64,error_code STRING,run_mode STRING,observed_at TIMESTAMP); CREATE TABLE IF NOT EXISTS \`${project}.meta.checkpoints\` (source STRING,account_id STRING,grain STRING,contract_id STRING,window_start DATE,window_end DATE,job_id STRING,status STRING,updated_at TIMESTAMP);`,useLegacySql:false});}
const types={source:'STRING',accountId:'STRING',grain:'STRING',contract:'STRING',start:'DATE',end:'DATE'};
export class MetaStore {
  constructor({bigquery,project}){identifier(project);Object.assign(this,{bigquery,project});}
  async ensure(){await ensureMetaSchema(this.bigquery,this.project);}
  binding(ctx){return {params:{source:ctx.source,accountId:ctx.account.account_id,grain:ctx.grain,contract:ctx.contract,start:new BigQueryDate(ctx.start),end:new BigQueryDate(ctx.end)},types};}
  async checkpoint(ctx){const [rows]=await this.bigquery.query({query:`SELECT * FROM \`${this.project}.meta.checkpoints\` WHERE source=@source AND account_id=@accountId AND grain=@grain AND contract_id=@contract AND window_start=@start AND window_end=@end`,...this.binding(ctx),useLegacySql:false});return rows[0]||null;}
  async saveJob(ctx,jobId){await this.bigquery.query({query:`MERGE \`${this.project}.meta.checkpoints\` t USING (SELECT @source source,@accountId account_id,@grain grain,@contract contract_id,@start window_start,@end window_end) s ON t.source=s.source AND t.account_id=s.account_id AND t.grain=s.grain AND t.contract_id=s.contract_id AND t.window_start=s.window_start AND t.window_end=s.window_end WHEN MATCHED THEN UPDATE SET job_id=@jobId,status='pending',updated_at=CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT VALUES(@source,@accountId,@grain,@contract,@start,@end,@jobId,'pending',CURRENT_TIMESTAMP())`,...this.binding(ctx),params:{...this.binding(ctx).params,jobId},types:{...types,jobId:'STRING'},useLegacySql:false});}
  async failure(ctx,error,status='failed'){await this.bigquery.query({query:`INSERT INTO \`${this.project}.meta.coverage\` VALUES(@source,@accountId,@grain,@contract,@start,@end,@status,@runId,NULL,@error,@mode,CURRENT_TIMESTAMP())`,params:{...this.binding(ctx).params,runId:ctx.runId,status,mode:ctx.runMode||'manual',error:String(error.code||'COLLECTION_FAILED').replace(/[^A-Z0-9_]/g,'').slice(0,80)},types:{...types,runId:'STRING',status:'STRING',mode:'STRING',error:'STRING'},useLegacySql:false});}
  async resetJob(ctx){await this.bigquery.query({query:`UPDATE \`${this.project}.meta.checkpoints\` SET job_id=NULL,status='failed',updated_at=CURRENT_TIMESTAMP() WHERE source=@source AND account_id=@accountId AND grain=@grain AND contract_id=@contract AND window_start=@start AND window_end=@end`,...this.binding(ctx),useLegacySql:false});}
  async promote(ctx,tables,{observedAt=new Date().toISOString()}={}){
    const dir=await mkdtemp(join(tmpdir(),'meta-stage-')),stages=[];
    try{
      for(const [table,rows] of Object.entries(tables)){
        if(!SCHEMAS[table])throw new Error('Unknown evidence table');
        const stage=`_stage_${table}_${randomUUID().replaceAll('-','')}`,target=this.bigquery.dataset('meta').table(stage);stages.push({table,stage});
        await target.create({schema:SCHEMAS[table],expirationTime:Date.now()+3600000});
        if(rows.length){const path=join(dir,`${table}.ndjson`);await writeFile(path,rows.map(r=>JSON.stringify(r)).join('\n'));await target.load(path,{sourceFormat:'NEWLINE_DELIMITED_JSON',schema:SCHEMAS[table],writeDisposition:'WRITE_TRUNCATE'});}
      }
      const statements=stages.map(({table,stage})=>{
        const predicate=table.endsWith('_daily')?'account_id=@accountId AND report_date BETWEEN @start AND @end':table==='instagram_media'?'account_id=@accountId AND DATE(observed_at,@timezone)=DATE(@observedAt,@timezone)':'account_id=@accountId AND ((evidence_kind IN (\'historical_daily\',\'window_total\') AND requested_start=@start AND requested_end=@end) OR (evidence_kind NOT IN (\'historical_daily\',\'window_total\') AND DATE(observed_at,@timezone)=DATE(@observedAt,@timezone)))';
        return `DELETE FROM \`${this.project}.meta.${table}\` WHERE ${predicate}; INSERT INTO \`${this.project}.meta.${table}\` SELECT * FROM \`${this.project}.meta.${stage}\`;`;
      }).join('\n');
      await this.bigquery.query({query:`BEGIN TRANSACTION; ${statements} DELETE FROM \`${this.project}.meta.coverage\` WHERE source=@source AND account_id=@accountId AND grain=@grain AND contract_id=@contract AND window_start=@start AND window_end=@end AND status='collected'; INSERT INTO \`${this.project}.meta.coverage\` VALUES(@source,@accountId,@grain,@contract,@start,@end,'collected',@runId,@count,NULL,@mode,@observedAt); DELETE FROM \`${this.project}.meta.checkpoints\` WHERE source=@source AND account_id=@accountId AND grain=@grain AND contract_id=@contract AND window_start=@start AND window_end=@end; INSERT INTO \`${this.project}.meta.checkpoints\` VALUES(@source,@accountId,@grain,@contract,@start,@end,NULL,'complete',@observedAt); COMMIT TRANSACTION;`,params:{...this.binding(ctx).params,runId:ctx.runId,mode:ctx.runMode||'manual',count:Object.values(tables).reduce((n,r)=>n+r.length,0),observedAt:new BigQueryTimestamp(observedAt),timezone:ctx.account.timezone},types:{...types,runId:'STRING',mode:'STRING',count:'INT64',observedAt:'TIMESTAMP',timezone:'STRING'},useLegacySql:false});
      return {account_id:ctx.account.account_id,grain:ctx.grain,start:ctx.start,end:ctx.end,counts:Object.fromEntries(Object.entries(tables).map(([t,r])=>[t,r.length]))};
    }finally{await Promise.allSettled(stages.map(({stage})=>this.bigquery.dataset('meta').table(stage).delete({ignoreNotFound:true})));await rm(dir,{recursive:true,force:true});}
  }
}
