import {BigQueryDate} from '@google-cloud/bigquery';
const dates={type:'object',additionalProperties:false,properties:{start_date:{type:'string'},end_date:{type:'string'},customer_id:{type:['string','null']}},required:['start_date','end_date','customer_id']};
export const GOOGLE_ADS_TOOL_DEFINITIONS=[
 {type:'function',name:'get_google_ads_performance',description:'Get governed Google Ads daily performance, account scope, spend, traffic, attributed conversions/value and warehouse coverage. Google Ads attribution is non-incremental and not finance revenue.',strict:true,parameters:dates},
 {type:'function',name:'get_google_ads_monthly_trends',description:'Get Google Ads monthly trends separately by customer and currency; incompatible currencies are never combined.',strict:true,parameters:dates},
 {type:'function',name:'rank_google_ads_campaigns',description:'Rank Google Ads campaigns for a bounded period without relabelling conversions as purchases.',strict:true,parameters:{...dates,properties:{...dates.properties,limit:{type:'integer',minimum:1,maximum:100}},required:[...dates.required,'limit']}},
 {type:'function',name:'get_google_ads_conversion_actions',description:'Get conversion-action performance; purchase-specific interpretation is supported only when the stored action category identifies purchase.',strict:true,parameters:dates}
];
export const googleAdsAccountFreshness=({collection_status,last_success_at=null,scheduled_execution=false})=>collection_status==='historical_only'?{overdue:false,classification:'historical_only',scheduled_execution:false}:{overdue:!last_success_at,classification:last_success_at?'active_collected':'active_missing_collection',scheduled_execution:Boolean(scheduled_execution)};
const valid=(s,n)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))throw new Error(`${n} must be YYYY-MM-DD`)};
const base=(project,where)=>`WITH coverage AS (SELECT customer_id, MIN(window_start) coverage_start,MAX(window_end) coverage_end,MAX(retrieved_at) latest_retrieved_at,COUNTIF(status='collected') collected_windows,COUNTIF(status='failed') failed_windows FROM \`${project}.google_ads.coverage\` WHERE window_end>=@start AND window_start<=@end ${where} GROUP BY customer_id)`;
export function googleAdsQuery(project,name,filtered){const w=filtered?'AND customer_id=@customerId':'';if(name==='get_google_ads_conversion_actions')return `${base(project,w)} SELECT d.*,d.conversion_action_category='PURCHASE' AS purchase_evidence,c.* EXCEPT(customer_id) FROM \`${project}.google_ads.conversion_action_daily\` d LEFT JOIN coverage c USING(customer_id) WHERE report_date BETWEEN @start AND @end ${w.replace('customer_id','d.customer_id')} ORDER BY report_date,customer_id,conversion_action_name`;
 const group=name==='get_google_ads_monthly_trends'?`DATE_TRUNC(report_date,MONTH) period`:name==='rank_google_ads_campaigns'?`campaign_id,campaign_name`:`report_date`;
 return `${base(project,w)} SELECT d.customer_id,ANY_VALUE(account_display_name) account_display_name,${group},ANY_VALUE(currency_code) currency_code,ANY_VALUE(reporting_timezone) reporting_timezone,SUM(cost_micros) cost_micros,SUM(impressions) impressions,SUM(clicks) clicks,SAFE_DIVIDE(SUM(clicks),SUM(impressions)) ctr,SAFE_DIVIDE(SUM(cost_micros),1000000*SUM(clicks)) cpc,SAFE_DIVIDE(SUM(cost_micros),1000*SUM(impressions)) cpm,SUM(conversions) conversions,SUM(conversion_value) conversion_value,SUM(all_conversions) all_conversions,SUM(all_conversion_value) all_conversion_value,SAFE_DIVIDE(SUM(cost_micros),1000000*SUM(conversions)) cost_per_conversion,SAFE_DIVIDE(SUM(conversion_value),SUM(cost_micros)/1000000) roas,ANY_VALUE(c.coverage_start) coverage_start,ANY_VALUE(c.coverage_end) coverage_end,ANY_VALUE(c.latest_retrieved_at) latest_retrieved_at FROM \`${project}.google_ads.campaign_daily\` d LEFT JOIN coverage c USING(customer_id) WHERE report_date BETWEEN @start AND @end ${w.replace('customer_id','d.customer_id')} GROUP BY d.customer_id,${group} ORDER BY ${name==='rank_google_ads_campaigns'?'cost_micros DESC':group}${name==='rank_google_ads_campaigns'?' LIMIT @limit':''}`;}
export function createGoogleAdsService({bigquery,project}){return async(name,args)=>{if(!GOOGLE_ADS_TOOL_DEFINITIONS.some(x=>x.name===name))throw new Error('Unsupported Google Ads tool');valid(args.start_date,'start_date');valid(args.end_date,'end_date');if(args.start_date>args.end_date)throw new Error('Invalid date range');const customerId=args.customer_id?.replace(/-/g,'')||null,params={start:new BigQueryDate(args.start_date),end:new BigQueryDate(args.end_date),customerId};if(name==='rank_google_ads_campaigns')params.limit=args.limit;try{const [rows]=await bigquery.query({query:googleAdsQuery(project,name,Boolean(customerId)),params,types:{start:'DATE',end:'DATE',customerId:'STRING',...(name==='rank_google_ads_campaigns'?{limit:'INT64'}:{})},useLegacySql:false,maximumBytesBilled:1_000_000_000});return{success:true,requested_period:{start_date:args.start_date,end_date:args.end_date},account_scope:customerId||'all configured accounts (kept separate by customer and currency)',rows,evidence_available:rows.length>0,definitions:{date_semantics:'Google Ads interaction-date metrics. Conversion-date metrics are not mixed into these tables.',conversions:'metrics.conversions (primary actions included in Conversions); fractional attribution is valid',all_conversions:'metrics.all_conversions, kept separate',roas:'conversion_value / spend; attributed value is not finance sales or incremental revenue',purchase:'Only conversion-action rows whose Google category is PURCHASE are described as purchase evidence'},limitations:['Currencies are never converted or combined.','Cross-platform attribution is not deduplicated.','No rows means missing evidence unless collected zero-activity coverage is present.']};}catch(error){throw Object.assign(new Error('Google Ads evidence retrieval failed; this is missing evidence, not zero spend or conversions'),{code:'GOOGLE_ADS_RETRIEVAL_FAILED',cause:error});}};}
export async function executeGoogleAdsToolCall(service,name,args){if(!GOOGLE_ADS_TOOL_DEFINITIONS.some(x=>x.name===name))return{handled:false};return{handled:true,result:await service(name,args)};}
