import {bigQueryDateParameters} from '../bigquery/date-parameters.js';
import {datasetLocation} from '../bigquery/dataset-location.js';

const dates={type:'object',additionalProperties:false,properties:{start_date:{type:'string'},end_date:{type:'string'}},required:['start_date','end_date']};
export const KLAVIYO_TOOL_DEFINITIONS=[
  {type:'function',name:'get_klaviyo_email_performance',description:'Return governed Klaviyo email campaign and flow performance, volumes, rates, coverage, metric IDs and attribution limitations. Reporting windows retain Klaviyo report semantics and are not order-occurrence cohorts.',strict:true,parameters:dates},
  {type:'function',name:'get_klaviyo_click_purchase_opportunities',description:'Rank Klaviyo email campaigns with unique clicks but comparatively weak attributed conversions, without asserting causality or statistical significance.',strict:true,parameters:dates},
  {type:'function',name:'compare_klaviyo_email_with_shopify_referrer',description:'Show Klaviyo email-attributed conversion value beside Shopify-native email-referrer sessions and completed-checkout sessions. The populations are separate and values are not finance sales.',strict:true,parameters:dates}
];
const valid=(v,n)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(`${v}T00:00:00Z`)))throw new Error(`${n} must be YYYY-MM-DD`)};
export function klaviyoAggregateQuery(project,opportunity=false){return `SELECT report_kind, entity_id, ANY_VALUE(entity_name) entity_name, conversion_metric_id, currency, reporting_timezone, api_revision, attribution_settings, report_period_semantics, SUM(recipients) recipients, SUM(delivered) delivered, SUM(opens_unique) unique_opens, SUM(clicks_unique) unique_clicks, SUM(conversions) attributed_conversions, SUM(conversion_value) attributed_conversion_value, SUM(bounced) bounces, SUM(unsubscribes) unsubscribes, SUM(spam_complaints) spam_complaints, SAFE_DIVIDE(SUM(clicks_unique),SUM(delivered)) unique_click_rate, SAFE_DIVIDE(SUM(opens_unique),SUM(delivered)) unique_open_rate, SAFE_DIVIDE(SUM(conversion_value),SUM(delivered)) revenue_per_delivered, MIN(DATE(report_start,reporting_timezone)) actual_start_date, MAX(DATE(report_end,reporting_timezone)) actual_end_date, COUNT(*) evidence_rows FROM \`${project}.klaviyo.message_performance\` WHERE DATE(report_start,reporting_timezone)>=@start_date AND DATE(report_start,reporting_timezone)<=@end_date GROUP BY 1,2,4,5,6,7,8,9 ${opportunity?'HAVING SUM(clicks_unique)>0 ORDER BY SAFE_DIVIDE(SUM(conversions),SUM(clicks_unique)), unique_clicks DESC':'ORDER BY report_kind, attributed_conversion_value DESC'} LIMIT 500`;}
export function shopifyEmailQuery(project){return `SELECT SUM(sessions) sessions,SUM(sessions_that_completed_checkout) completed_checkout_sessions,COUNT(DISTINCT date) covered_days FROM \`${project}.shopify_data.session_conversion_by_device_source\` WHERE date BETWEEN @start_date AND @end_date AND REGEXP_CONTAINS(LOWER(COALESCE(referrer_source,'')),r'email|newsletter|klaviyo')`;}
export function createKlaviyoEmailService({bigquery,project}){return async(name,args)=>{if(!KLAVIYO_TOOL_DEFINITIONS.some(x=>x.name===name))throw new Error('Unsupported Klaviyo tool');valid(args.start_date,'start_date');valid(args.end_date,'end_date');if(args.start_date>args.end_date)throw new Error('Invalid date range');const location=await datasetLocation(bigquery,project,'klaviyo',{fallback:'US'}),base={params:bigQueryDateParameters(args),types:{start_date:'DATE',end_date:'DATE'},useLegacySql:false,maximumBytesBilled:1_000_000_000,location,labels:{component:'oracle_klaviyo_email'}};let rows;try{[rows]=await bigquery.query({...base,query:klaviyoAggregateQuery(project,name==='get_klaviyo_click_purchase_opportunities')});}catch(error){throw Object.assign(new Error('Klaviyo evidence retrieval failed; this is not zero performance or absent data'),{code:'KLAVIYO_RETRIEVAL_FAILED',cause:error});}const common={success:true,requested_period:args,rows,definitions:{unique_click_rate:'unique clicks / delivered messages',unique_open_rate:'unique opens / delivered messages; privacy protections and machine opens can affect opens',revenue_per_delivered:'attributed conversion value / delivered messages, within one currency and conversion metric only'},limitations:['Klaviyo attribution is not incremental revenue and must not be added to Shopify or Woo finance sales.','Each conversion_metric_id is a distinct integration population; rows and currencies are not combined.','The stored report-period semantics apply; results are not relabelled as orders occurring in the calendar period.','No campaign-level device or session join is established.']};if(name!=='compare_klaviyo_email_with_shopify_referrer')return common;let shopify;try{[[shopify]]=await bigquery.query({...base,location:await datasetLocation(bigquery,project,'shopify_data',{fallback:'US'}),query:shopifyEmailQuery(project)});}catch(error){throw Object.assign(new Error('Shopify referrer evidence retrieval failed; comparison unavailable, not zero'),{code:'SHOPIFY_REFERRER_RETRIEVAL_FAILED',cause:error});}return {...common,shopify_email_referrer:shopify||null,comparison_semantics:'Side-by-side only: Shopify referrer sessions do not cover all email-influenced purchases, and Klaviyo attribution is not finance revenue.'};};}
export async function executeKlaviyoEmailToolCall(service,name,args){if(!KLAVIYO_TOOL_DEFINITIONS.some(x=>x.name===name))return {handled:false};return {handled:true,result:await service(name,args)};}

export function classifyKlaviyoQuestion(message){const text=String(message).toLowerCase();if(/compare.*klaviyo.*shopify|shopify.*email-referrer/.test(text))return 'compare_klaviyo_email_with_shopify_referrer';if(/strong clicks.*weak.*purchases/.test(text))return 'get_klaviyo_click_purchase_opportunities';if(/email campaigns.*automated flows.*august 2026/.test(text))return 'get_klaviyo_email_performance';return null;}
