const MONTHS={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};
const PRODUCT_REQUEST=/\b(?:top\s*20|product performance|products? by net sales|largest increases|largest decreases)\b/i;
const n=value=>value==null?'unsupported':Number(value).toLocaleString('en-GB',{maximumFractionDigits:2});
const money=(value,currency)=>value==null?'unsupported':`${currency} ${n(value)}`;
const iso=clock=>new Date(clock()).toISOString();

function months(message){return [...String(message).toLowerCase().matchAll(new RegExp(`\\b(${Object.keys(MONTHS).join('|')})\\s+(20\\d{2})\\b`,'g'))].map(match=>{const y=Number(match[2]),m=MONTHS[match[1]],end=new Date(Date.UTC(y,m+1,0)).getUTCDate();return{start_date:`${y}-${String(m+1).padStart(2,'0')}-01`,end_date:`${y}-${String(m+1).padStart(2,'0')}-${end}`,days:end};});}
export function isProductEvidenceRequest(message){const text=String(message||'');return PRODUCT_REQUEST.test(text)&&/shopify|online product|product performance/i.test(text)&&!/(?:show|include|compare|rank|analyse|analyze)\s+(?:current\s+)?(?:inventory|stock)\b/i.test(text);}
const key=row=>`${row.product_id||''}|${row.currency||''}`;
const safeError=error=>String(error?.code||'PRODUCT_RETRIEVAL_FAILED').replace(/[^A-Za-z0-9_.-]/g,'').slice(0,60);
const coverage=(period,result,executedAt)=>({requested_scope:{...period,platform:'Shopify',channel:'Online Store',ranking:'net_sales desc',limit:20},applied_scope:{start_date:result?.start_date||period.start_date,end_date:result?.end_date||period.end_date,platform:'Shopify',channel:result?.sales_channel||'Online Store',retrieval_limit:50},actual_coverage:{basis:'ShopifyQL returned aggregate rows for the exact applied dates; row dates alone do not establish source collection completeness.',complete_population:Boolean(result&&result.products?.length<50),returned_rows:result?.products?.length||0},source:{platform:'Shopify',report:'ShopifyQL FROM sales'},currency_basis:'Authoritative Shopify shop currency; monetary rows with unavailable currency are retained diagnostically and excluded from accepted rankings.',metric_definitions:{net_sales:'Shopify operational net sales at product grain.',gross_sales:'Shopify operational gross sales at product grain.',discounts:'Shopify operational product discounts.',returns:'Shopify operational monetary return value; not accounting refund money.',net_items_sold:'Shopify net items sold.'},grain:'product_id + product_title + Shopify shop currency',source_collection_timestamp:null,query_executed_at:executedAt,status:result?'available':'retrieval_failed',limitations:['A returned ranking is not a store total.','No inventory was requested or retrieved.']});

export function createProductEvidenceReportService({getProductPerformance,getShopCurrency,now=()=>new Date()}){
  return async message=>{
    if(!isProductEvidenceRequest(message))return null;
    const periods=months(message);if(!periods.length)return null;
    const selected=periods.slice(0,/compare|versus|\bvs\b/i.test(message)?2:1);
    let currency=null,currencyFailure=null;
    try{currency=await getShopCurrency();if(!/^[A-Z]{3}$/.test(String(currency)))throw Object.assign(new Error('invalid currency'),{code:'INVALID_SHOP_CURRENCY'});}catch(error){currencyFailure=safeError(error);currency=null;}
    const evidence=[];
    for(const period of selected){const executedAt=iso(now);try{const result=await getProductPerformance({...period,limit:50,sort_by:'net_sales'});const rows=(result.products||[]).map(row=>({...row,currency}));evidence.push({period,result:{...result,products:rows},contract:coverage(period,{...result,products:rows},executedAt)});}catch(error){evidence.push({period,error_code:safeError(error),contract:coverage(period,null,executedAt)});}}
    const lines=['# Shopify Online Store product evidence',`**Requested scope:** ${selected.map(p=>`${p.start_date} to ${p.end_date}`).join(' versus ')}; top 20 by net sales; Shopify Online Store; no inventory.`];
    for(const item of evidence){lines.push(`\n## ${item.period.start_date} to ${item.period.end_date}`);if(!item.result){lines.push(`- Status: retrieval failed (${item.error_code}); missing evidence is not zero.`);continue;}const accepted=item.result.products.filter(row=>row.currency).slice(0,20);if(!accepted.length)lines.push(item.result.products.length?'- Diagnostic rows were returned, but authoritative currency was unavailable; monetary rows were excluded from the accepted ranking.':'- No usable rows were returned. This is empty evidence, not asserted zero activity.');else for(const [i,row] of accepted.entries())lines.push(`- #${i+1} **${String(row.product_title||'Unknown product').slice(0,120)}** (${row.product_id||'stable ID unavailable'}) · ${row.currency}: net sales ${money(row.net_sales,row.currency)}; gross sales ${money(row.gross_sales,row.currency)}; discounts ${money(row.discounts,row.currency)}; operational returns ${money(row.returns,row.currency)}; net units ${n(row.net_items_sold)}.`);lines.push(`- Applied scope: ${item.contract.applied_scope.start_date} to ${item.contract.applied_scope.end_date}; ${item.contract.applied_scope.platform} ${item.contract.applied_scope.channel}; grain ${item.contract.grain}; returned ${item.contract.actual_coverage.returned_rows} rows; complete population ${item.contract.actual_coverage.complete_population?'established':'not established (bounded at 50)'}.`,'- Source collection timestamp: unavailable from ShopifyQL. Query execution timestamp: '+item.contract.query_executed_at+'.');}
    if(evidence.length===2&&evidence.every(x=>x.result)){const [current,comparison]=evidence,complete=current.contract.actual_coverage.complete_population&&comparison.contract.actual_coverage.complete_population;const a=new Map(current.result.products.filter(x=>x.currency).map(x=>[key(x),x])),b=new Map(comparison.result.products.filter(x=>x.currency).map(x=>[key(x),x]));const common=[...a].filter(([k])=>b.has(k)).map(([k,row])=>({row,prior:b.get(k),change:Number(row.net_sales)-Number(b.get(k).net_sales)})).filter(x=>Number.isFinite(x.change)).sort((x,y)=>Math.abs(y.change)-Math.abs(x.change)).slice(0,20);lines.push('\n## Compatible product changes');for(const x of common)lines.push(`- **${x.row.product_title}** (${x.row.product_id}) · ${x.row.currency}: absolute change ${money(x.change,x.row.currency)}; percentage change ${Number(x.prior.net_sales)===0?'undefined':`${(x.change/Math.abs(Number(x.prior.net_sales))*100).toFixed(2)}%`}.`);if(complete){for(const row of current.result.products.filter(x=>x.currency&&!b.has(key(x))))lines.push(`- **Only in current complete population:** ${row.product_title} (${row.product_id}) · ${row.currency}.`);for(const row of comparison.result.products.filter(x=>x.currency&&!a.has(key(x))))lines.push(`- **Only in comparison complete population:** ${row.product_title} (${row.product_id}) · ${row.currency}.`);}else lines.push('- Products missing from either bounded ranking are not treated as zero or described as absent; complete applicable populations were not established.');}
    lines.push('\n## Definitions and limitations','- Rankings stay separate by authoritative currency; no FX conversion or assumed GBP.','- Operational product returns are not accounting refund money. Percent change from a zero baseline is undefined.','- Collections/collaborations are unavailable here unless a governed classification result is independently supplied; names are never used to infer membership.','- Top-N rows are never used to derive store totals or product shares.');if(currencyFailure)lines.push(`- Currency lookup failed (${currencyFailure}); affected monetary rows remain diagnostic only.`);
    return{answer:lines.join('\n'),tools:['get_shopify_product_performance'],attempted_tools:['get_shopify_shop_currency',...selected.map(()=> 'get_shopify_product_performance')],evidence:{kind:'shopify_product_evidence',requested_at:iso(now),periods:selected,currency_status:currency?{status:'available',currency}:{status:'failed',error_code:currencyFailure},sections:evidence}};
  };
}
