import {datasetLocation,assertDatasetIdentifier} from '../bigquery/dataset-location.js';
import {date} from '../meta/config.js';
export const TIKTOK_TOOL_DEFINITIONS=[{type:'function',name:'get_tiktok_performance',description:'Read preserved TikTok organic metadata, lifetime post snapshots, dated native account evidence and audience snapshots with collection coverage. Publication-period rankings are lifetime counters, not historical activity; no sales attribution.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{start_date:{type:'string'},end_date:{type:'string'},account_id:{type:['string','null']},scope:{type:'string',enum:['account','media']},metric:{type:'string'},media_type:{type:['string','null']},limit:{type:'integer',minimum:1,maximum:100}},required:['start_date','end_date','account_id','scope','metric','media_type','limit']}}];
export function createTikTokService({bigquery,project}){
 assertDatasetIdentifier(project);
 return async(name,args)=>{
  if(name!=='get_tiktok_performance')throw new Error('Unsupported TikTok tool');date(args.start_date);date(args.end_date);
  if(args.start_date>args.end_date||!['account','media'].includes(args.scope)||!/^[a-z][a-z0-9_]{0,79}$/.test(args.metric)||!Number.isInteger(args.limit)||args.limit<1||args.limit>100)throw new Error('Invalid TikTok evidence scope');
  const params={start:args.start_date,end:args.end_date,account:args.account_id,metric:args.metric,limit:args.limit},types={start:'STRING',end:'STRING',account:'STRING',metric:'STRING',limit:'INT64'};
  const query=`WITH latest AS (SELECT * FROM \`${project}.tiktok_organic.observations\` WHERE metric=@metric AND (@account IS NULL OR account_id=@account) QUALIFY ROW_NUMBER() OVER(PARTITION BY account_id,resource_id,metric,evidence_kind,applied_start,applied_end,IF(evidence_kind='native_period_unverified',requested_start,NULL),IF(evidence_kind='native_period_unverified',requested_end,NULL) ORDER BY retrieved_at DESC)=1) SELECT *,retrieved_at observed_at FROM latest WHERE ${args.scope==='media'?"resource_id!=account_id AND COALESCE(SUBSTR(IF(REGEXP_CONTAINS(publication_native,r'^\\d{4}-'),publication_native,NULL),1,10),CAST(DATE(TIMESTAMP_SECONDS(SAFE_CAST(publication_native AS INT64))) AS STRING)) BETWEEN @start AND @end":"resource_id=account_id AND ((applied_start BETWEEN @start AND @end) OR (evidence_kind IN ('current_snapshot','audience_snapshot','metadata') AND SUBSTR(retrieved_at,1,10) BETWEEN @start AND @end) OR (evidence_kind='native_period_unverified' AND requested_start<=@end AND requested_end>=@start))"} ORDER BY value IS NULL,value DESC,resource_id LIMIT @limit`;
  try{const location=await datasetLocation(bigquery,project,'tiktok_organic');const [rows]=await bigquery.query({query,params,types,location,useLegacySql:false,maximumBytesBilled:1_000_000_000});const [checkpoints]=await bigquery.query({query:`SELECT account_id,import_id,grain,state_json,updated_at FROM \`${project}.tiktok_organic.checkpoints\` WHERE (@account IS NULL OR account_id=@account) ORDER BY updated_at DESC LIMIT 2000`,params:{account:args.account_id},types:{account:'STRING'},location,useLegacySql:false,maximumBytesBilled:1_000_000_000});
    return {success:true,rows,limited:rows.length===args.limit,coverage:{complete:false,checkpoints,note:'Review per-field pagination and native returned dates; requested dates do not prove complete historical coverage.'},historical_metric_coverage_verified:false,definitions:{snapshots:'Current account and audience observations; lifetime post counters. Native dated observations preserve API dates; follower and reach populations must not be summed.',periods:'Requested and applied dates are separate. Ambiguous native periods remain unverified.'},limitations:['No sales attribution or causal evidence.','No daily activity reconstructed from lifetime counters.','Missing, inaccessible and rejected fields are not zero.','API reporting timezone and historical bounds require live verification.']};
  }catch{return {success:false,rows:[],coverage:{complete:false},historical_metric_coverage_verified:false,definitions:{},limitations:['TikTok warehouse evidence unavailable; no zero activity inference.'],error_code:'TIKTOK_EVIDENCE_UNAVAILABLE'};}
 };
}
export async function executeTikTokToolCall(service,name,args){return name==='get_tiktok_performance'?{handled:true,result:await service(name,args)}:{handled:false};}
