import {mkdtemp,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {BigQueryDate,BigQueryTimestamp} from '@google-cloud/bigquery';
export const DATASET='google_ads';
const schemas={campaign_daily:'customer_id STRING, account_display_name STRING, report_date DATE, campaign_id STRING, campaign_name STRING, campaign_status STRING, advertising_channel_type STRING, currency_code STRING, reporting_timezone STRING, cost_micros NUMERIC, impressions INT64, clicks INT64, conversions NUMERIC, conversion_value NUMERIC, all_conversions NUMERIC, all_conversion_value NUMERIC, api_version STRING, retrieved_at TIMESTAMP',account_daily:'customer_id STRING, report_date DATE, currency_code STRING, reporting_timezone STRING, cost_micros NUMERIC, impressions INT64, clicks INT64, conversions NUMERIC, conversion_value NUMERIC, all_conversions NUMERIC, all_conversion_value NUMERIC, api_version STRING, retrieved_at TIMESTAMP',conversion_action_daily:'customer_id STRING, report_date DATE, conversion_action_resource STRING, conversion_action_name STRING, conversion_action_category STRING, currency_code STRING, reporting_timezone STRING, conversions NUMERIC, conversion_value NUMERIC, all_conversions NUMERIC, all_conversion_value NUMERIC, api_version STRING, retrieved_at TIMESTAMP'};
const keys={campaign_daily:['customer_id','report_date','campaign_id'],account_daily:['customer_id','report_date'],conversion_action_daily:['customer_id','report_date','conversion_action_resource']};
const safe=s=>{if(!/^[A-Za-z0-9_-]+$/.test(s))throw new Error('Invalid BigQuery identifier');return s};
export async function ensureGoogleAdsSchema(bigquery,project){safe(project);const ddl=Object.entries(schemas).map(([t,s])=>`CREATE TABLE IF NOT EXISTS \`${project}.${DATASET}.${t}\` (${s}) PARTITION BY report_date CLUSTER BY customer_id;`).join('\n');await bigquery.query({query:`CREATE SCHEMA IF NOT EXISTS \`${project}.${DATASET}\`; ${ddl} CREATE TABLE IF NOT EXISTS \`${project}.${DATASET}.coverage\` (customer_id STRING, window_start DATE, window_end DATE, status STRING, row_counts_json STRING, run_id STRING, run_mode STRING, scheduled_execution BOOL, error_reason STRING, retrieved_at TIMESTAMP, PRIMARY KEY(customer_id,window_start,window_end) NOT ENFORCED);`,useLegacySql:false});}
const typed=row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,k==='report_date'?new BigQueryDate(v):k==='retrieved_at'?new BigQueryTimestamp(v):v]));
export async function promoteWindow({bigquery,project,account,start,end,runId,runMode='manual',rowsByTable,retrievedAt=new Date()}){safe(project);await ensureGoogleAdsSchema(bigquery,project);const dir=await mkdtemp(path.join(os.tmpdir(),'google-ads-'));const stages=[];try{for(const [table,rows] of Object.entries(rowsByTable)){if(!schemas[table])throw new Error(`Unknown Google Ads table ${table}`);const stage=`_stage_${table}_${runId.replace(/-/g,'')}`;const file=path.join(dir,`${table}.ndjson`);await writeFile(file,rows.map(x=>JSON.stringify(x)).join('\n'));const target=bigquery.dataset(DATASET).table(stage);await target.create({schema:schemas[table],expirationTime:Date.now()+3600000});if(rows.length)await target.load(file,{sourceFormat:'NEWLINE_DELIMITED_JSON',writeDisposition:'WRITE_TRUNCATE',schema:schemas[table]});stages.push({table,stage});}
    const counts=JSON.stringify(Object.fromEntries(Object.entries(rowsByTable).map(([k,v])=>[k,v.length]))),params={customerId:account.customer_id,start:new BigQueryDate(start),end:new BigQueryDate(end),runId,runMode,scheduled:runMode==='scheduled',counts,retrievedAt:new BigQueryTimestamp(retrievedAt)};
    const statements=stages.map(({table,stage})=>`DELETE FROM \`${project}.${DATASET}.${table}\` WHERE customer_id=@customerId AND report_date BETWEEN @start AND @end; INSERT INTO \`${project}.${DATASET}.${table}\` SELECT * FROM \`${project}.${DATASET}.${stage}\`;`).join('\n');
    const query=`BEGIN TRANSACTION; ${statements} MERGE \`${project}.${DATASET}.coverage\` t USING (SELECT @customerId customer_id,@start window_start,@end window_end) s ON t.customer_id=s.customer_id AND t.window_start=s.window_start AND t.window_end=s.window_end WHEN MATCHED THEN UPDATE SET status='collected',row_counts_json=@counts,run_id=@runId,run_mode=@runMode,scheduled_execution=@scheduled,error_reason=NULL,retrieved_at=@retrievedAt WHEN NOT MATCHED THEN INSERT VALUES(@customerId,@start,@end,'collected',@counts,@runId,@runMode,@scheduled,NULL,@retrievedAt); COMMIT TRANSACTION;`;
    // BigQuery cannot fully validate later statements in multi-statement dry runs. Validate each DML shape first, then execute the atomic script.
    for(const {table,stage} of stages)await bigquery.createQueryJob({query:`SELECT * FROM \`${project}.${DATASET}.${stage}\` WHERE FALSE; SELECT * FROM \`${project}.${DATASET}.${table}\` WHERE customer_id=@customerId AND report_date BETWEEN @start AND @end LIMIT 0`,params,types:{customerId:'STRING',start:'DATE',end:'DATE',runId:'STRING',runMode:'STRING',scheduled:'BOOL',counts:'STRING',retrievedAt:'TIMESTAMP'},dryRun:true,useLegacySql:false});
    await bigquery.query({query,params,types:{customerId:'STRING',start:'DATE',end:'DATE',runId:'STRING',runMode:'STRING',scheduled:'BOOL',counts:'STRING',retrievedAt:'TIMESTAMP'},useLegacySql:false});return{customer_id:account.customer_id,start,end,row_counts:JSON.parse(counts)};
  }catch(error){throw Object.assign(new Error(`Google Ads persistence failed at bounded promotion: ${String(error.message).slice(0,500)}`),{code:'GOOGLE_ADS_PROMOTION_FAILED',reason:error?.errors?.[0]?.reason,location:error?.errors?.[0]?.location});}finally{await Promise.allSettled(stages.map(x=>bigquery.dataset(DATASET).table(x.stage).delete({ignoreNotFound:true})));await rm(dir,{recursive:true,force:true});}}
export const typedNullableParameters=({customerId,start,end,limit=null})=>({params:{customerId,start:new BigQueryDate(start),end:new BigQueryDate(end),limit},types:{customerId:'STRING',start:'DATE',end:'DATE',limit:'INT64'}});
export async function recordWindowFailure({bigquery,project,account,start,end,runId,runMode='manual',error,retrievedAt=new Date()}){await ensureGoogleAdsSchema(bigquery,project);const params={customerId:account.customer_id,start:new BigQueryDate(start),end:new BigQueryDate(end),runId,runMode,scheduled:runMode==='scheduled',reason:String(error?.code||error?.reason||'COLLECTION_FAILED').slice(0,80),retrievedAt:new BigQueryTimestamp(retrievedAt)};await bigquery.query({query:`MERGE \`${project}.${DATASET}.coverage\` t USING (SELECT @customerId customer_id,@start window_start,@end window_end) s ON t.customer_id=s.customer_id AND t.window_start=s.window_start AND t.window_end=s.window_end WHEN MATCHED AND t.status!='collected' THEN UPDATE SET status='failed',run_id=@runId,run_mode=@runMode,scheduled_execution=@scheduled,error_reason=@reason,retrieved_at=@retrievedAt WHEN NOT MATCHED THEN INSERT VALUES(@customerId,@start,@end,'failed',NULL,@runId,@runMode,@scheduled,@reason,@retrievedAt)`,params,types:{customerId:'STRING',start:'DATE',end:'DATE',runId:'STRING',runMode:'STRING',scheduled:'BOOL',reason:'STRING',retrievedAt:'TIMESTAMP'},useLegacySql:false});}
