export const DOMAIN_PROPERTY = 'sc-domain:thegreatfroglondon.com';
export const WWW_PROPERTY = 'https://www.thegreatfroglondon.com/';
export const PROPERTIES = Object.freeze([
  { source_property: DOMAIN_PROPERTY, property_scope: 'domain', property_hostname: 'thegreatfroglondon.com' },
  { source_property: WWW_PROPERTY, property_scope: 'url_prefix', property_hostname: 'www.thegreatfroglondon.com' }
]);
// Bounded URL-prefix fallback for the required prior-year comparison.
export const HISTORY_START = '2024-11-01';
const ISO = /^\d{4}-\d{2}-\d{2}$/;
export function assertDate(value, name='date') { if (!ISO.test(value||'') || new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)!==value) throw new Error(`${name} must be a valid YYYY-MM-DD date`); return value; }
export function datesBetween(start,end) { assertDate(start); assertDate(end); const out=[]; for(let d=new Date(`${start}T00:00:00Z`);d<=new Date(`${end}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1)) out.push(d.toISOString().slice(0,10)); return out; }
export function propertyMetadata(source) { const found=PROPERTIES.find(p=>p.source_property===source); if(!found) throw new Error(`Ungoverned Search Console property: ${source}`); return found; }
export function normalizePage(value) { try { const u=new URL(value); if(!['http:','https:'].includes(u.protocol)||!u.hostname) throw new Error(); return { normalized_hostname:u.hostname.toLowerCase(), normalized_path:u.pathname||'/' }; } catch { throw new Error('Search Console page is not a valid HTTP(S) URL'); } }
export function metricRow(row) { const clicks=Number(row.clicks??0), impressions=Number(row.impressions??0), position=impressions ? Number(row.position??0) : null; return { clicks, impressions, ctr:impressions ? clicks/impressions : 0, position }; }
export function aggregate(rows) { let clicks=0,impressions=0,weight=0; for(const row of rows){const m=metricRow(row);clicks+=m.clicks;impressions+=m.impressions;if(m.position!=null)weight+=m.position*m.impressions;} return {clicks,impressions,ctr:impressions?clicks/impressions:0,position:impressions?weight/impressions:null}; }
export function canonicalDaily(sourceRows,start,end,syncedAt=new Date().toISOString()) { const by=new Map(sourceRows.filter(r=>r.coverage_status==='available').map(r=>[`${r.source_property}|${r.date}`,r])); return datesBetween(start,end).map(date=>{const d=by.get(`${DOMAIN_PROPERTY}|${date}`),w=by.get(`${WWW_PROPERTY}|${date}`),s=d||w;if(!s)return {date,clicks:null,impressions:null,ctr:null,position:null,selected_source_property:null,selected_property_scope:null,selection_reason:'no_available_property_evidence',coverage_status:'unavailable',synced_at:syncedAt};return {date,clicks:s.clicks,impressions:s.impressions,ctr:s.ctr,position:s.position,selected_source_property:s.source_property,selected_property_scope:s.property_scope,selection_reason:d?'preferred_domain_property':'fallback_www_property',coverage_status:'available',synced_at:syncedAt};}); }
export function validateRows(name,rows){const keys={daily:['source_property','date'],queries:['source_property','date','query'],pages:['source_property','date','page'],device_country:['source_property','date','device','country']}[name],seen=new Set();for(const r of rows){const meta=propertyMetadata(r.source_property);if(r.property_scope!==meta.property_scope||r.property_hostname!==meta.property_hostname)throw new Error(`${name} contains invalid property provenance`);assertDate(r.date);if(name==='pages'){const normalized=normalizePage(r.page);if(r.normalized_hostname!==normalized.normalized_hostname||r.normalized_path!==normalized.normalized_path)throw new Error('pages contains invalid normalized identity');}const k=JSON.stringify(keys.map(x=>r[x]));if(seen.has(k))throw new Error(`${name} contains duplicate semantic key`);seen.add(k);if(r.clicks<0||r.impressions<0||r.clicks>r.impressions)throw new Error(`${name} contains invalid metrics`);if(r.ctr<0||r.ctr>1||Math.abs(r.ctr-(r.impressions?r.clicks/r.impressions:0))>1e-9)throw new Error(`${name} contains invalid CTR`);if(r.position!=null&&r.position<0)throw new Error(`${name} contains invalid position`);}return rows;}
