import { assertDate, metricComparability, rangeCoverage } from './semantic.js';

const safeId = value => { if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error('Invalid BigQuery identifier'); return value; };
const range = (startDate, endDate) => { assertDate(startDate, 'startDate'); assertDate(endDate, 'endDate'); if (startDate > endDate) throw new Error('startDate must not be after endDate'); return { startDate, endDate }; };
export function createGa4QueryService({ bigquery, project, dataset = 'ga4' }) {
  safeId(project); safeId(dataset); const table = name => `\`${project}.${dataset}.${name}\``;
  const run = async (query, params) => { const [rows] = await bigquery.query({ query, params, types: { startDate: 'DATE', endDate: 'DATE' }, labels: { component: 'ga4_semantic_query' } }); return rows; };
  const evidence = (startDate, endDate, extra = {}) => ({ provenance: { source: 'Google Analytics 4 Data API', property_role: 'website_behaviour_not_transaction_or_money_truth', aggregate_only: true, native_bigquery_export: false }, tracking: rangeCoverage(startDate, endDate), ...extra });
  return {
    async trafficSummary(startDate, endDate) { range(startDate, endDate); const rows = await run(`SELECT SUM(sessions) sessions, SUM(total_users) total_users, SUM(new_users) new_users, SUM(engaged_sessions) engaged_sessions, SAFE_DIVIDE(SUM(engaged_sessions),SUM(sessions)) engagement_rate, SUM(screen_page_views) screen_page_views FROM ${table('daily')} WHERE date BETWEEN @startDate AND @endDate`, { startDate, endDate }); return { values: rows[0], ...evidence(startDate, endDate) }; },
    async trafficComparison(first, second) { const [a, b] = await Promise.all([this.trafficSummary(first.startDate, first.endDate), this.trafficSummary(second.startDate, second.endDate)]); return { periods: [a, b], comparability: metricComparability('sessions', first, second) }; },
    async acquisitionBreakdown(startDate, endDate) { range(startDate, endDate); return { rows: await run(`SELECT session_default_channel_group,session_source,session_medium,session_campaign_name,SUM(sessions) sessions,SUM(total_users) total_users,SUM(engaged_sessions) engaged_sessions,SAFE_DIVIDE(SUM(engaged_sessions),SUM(sessions)) engagement_rate FROM ${table('acquisition')} WHERE date BETWEEN @startDate AND @endDate GROUP BY 1,2,3,4 ORDER BY sessions DESC LIMIT 500`, { startDate, endDate }), ...evidence(startDate, endDate) }; },
    async landingPagePerformance(startDate, endDate) { range(startDate, endDate); return { rows: await run(`SELECT landing_path,SUM(sessions) sessions,SUM(total_users) total_users,SUM(engaged_sessions) engaged_sessions,SAFE_DIVIDE(SUM(engaged_sessions),SUM(sessions)) engagement_rate,SUM(screen_page_views) screen_page_views FROM ${table('landing_pages')} WHERE date BETWEEN @startDate AND @endDate GROUP BY 1 ORDER BY sessions DESC LIMIT 500`, { startDate, endDate }), ...evidence(startDate, endDate) }; },
    async deviceGeoBreakdown(startDate, endDate) { range(startDate, endDate); return { rows: await run(`SELECT device_category,browser,country,SUM(sessions) sessions,SUM(total_users) total_users,SUM(engaged_sessions) engaged_sessions,SAFE_DIVIDE(SUM(engaged_sessions),SUM(sessions)) engagement_rate FROM ${table('device_geo')} WHERE date BETWEEN @startDate AND @endDate GROUP BY 1,2,3 ORDER BY sessions DESC LIMIT 500`, { startDate, endDate }), ...evidence(startDate, endDate) }; },
    async ecommerceFunnel(startDate, endDate) { range(startDate, endDate); const tracking = rangeCoverage(startDate, endDate); if (!tracking.ecommerce_comparable_within_range) return { values: null, ...evidence(startDate, endDate, { availability: 'unavailable_or_mixed_tracking_era', zero_is_not_assumed: true }) }; const rows = await run(`SELECT SUM(view_item) view_item,SUM(add_to_cart) add_to_cart,SUM(begin_checkout) begin_checkout,SUM(purchase) purchase FROM ${table('ecommerce_funnel')} WHERE date BETWEEN @startDate AND @endDate`, { startDate, endDate }); return { values: rows[0], ...evidence(startDate, endDate, { availability: 'observed_provisional', zero_is_observed_event_count: true, transaction_truth: false }) }; },
    trackingCoverage: (startDate, endDate) => rangeCoverage(startDate, endDate),
    metricComparability
  };
}
