#!/usr/bin/env node
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {BigQuery} from '@google-cloud/bigquery';
import {ORACLE_SOURCE_CONTRACTS} from '../oracle/freshness.js';

export const CONTROL_DATASET='oracle_ops';
const safe=value=>{if(!/^[A-Za-z0-9_-]+$/.test(value))throw new Error('Invalid identifier');return value};
const isoDate=d=>d.toISOString().slice(0,10);
const minusDays=(date,n)=>{const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-n);return isoDate(d)};
export function plannedCommand(source,{now=new Date(),coverageEnd=null}={}){
  const yesterday=minusDays(isoDate(now),1),max=coverageEnd?String(coverageEnd).slice(0,10):null;
  if(source==='shopify_finance')return ['npm',['run','refresh:shopify-finance','--','--mode','scheduled']];
  if(source==='ga4'){const end=yesterday,start=max?minusDays(max,6):null;if(!start)throw new Error('ga4 has no persisted coverage; supply an explicit bounded catch-up before scheduling');return ['npm',['run','sync:ga4','--','--start',start,'--end',end]];}
  if(source==='search_console'){const end=minusDays(isoDate(now),3),start=max?minusDays(max,6):null;if(!start)throw new Error('search_console has no persisted coverage; supply an explicit bounded catch-up before scheduling');return ['npm',['run','sync:search-console','--','--start',start,'--end',end]];}
  if(source==='shopify_geography')return ['npm',['run','sync:shopify-shipping-geography']];
  if(source==='shopify_conversion'){const end=yesterday,start=max?minusDays(max,6):null;if(!start)throw new Error('shopify_conversion has no persisted coverage; supply an explicit bounded catch-up before scheduling');return ['npm',['run','backfill:shopify-conversion','--','--mode','repair','--start',start,'--end',end,'--chunk-days','7','--max-chunks','2','--max-sources','40']];}
  if(source==='shopify_catalogue')return ['npm',['run','sync:shopify-catalogue']];
  if(source==='product_classifications')return ['npm',['run','sync:product-classifications']];
  if(source==='klaviyo')return ['npm',['run','schedule:klaviyo']];
  throw new Error(`${source} is not an active warehouse collector`);
}
const daily=(project,dataset,table,column)=>({table,kind:'daily',query:`SELECT CAST(MIN(${column}) AS STRING) coverage_start,CAST(MAX(${column}) AS STRING) coverage_end,COUNT(*) row_count,COUNT(DISTINCT ${column}) covered_days,IF(MIN(${column}) IS NULL,NULL,DATE_DIFF(MAX(${column}),MIN(${column}),DAY)+1-COUNT(DISTINCT ${column})) internal_gap_days FROM \`${project}.${dataset}.${table}\``});
const snapshot=(project,dataset,table,timestamp=null)=>({table,kind:'snapshot',query:`SELECT COUNT(*) row_count${timestamp?`,CAST(MAX(${timestamp}) AS STRING) snapshot_retrieved_at`:''} FROM \`${project}.${dataset}.${table}\``});
export function sourceInspections(project,source){safe(project);const q={
  ga4:['daily','acquisition','landing_pages','device_geo','conversion_device','conversion_breakdown','conversion_coverage','ecommerce_funnel'].map(t=>daily(project,'ga4',t,'date')),
  search_console:['daily','queries','pages','device_country','canonical_daily'].map(t=>daily(project,'search_console',t,'date')),
  shopify_finance:[snapshot(project,'shopify_data','order_locations','synced_at'),snapshot(project,'shopify_data','order_financials','synced_at'),snapshot(project,'shopify_data','order_refunds','synced_at')],
  shopify_geography:[snapshot(project,'shopify_data','order_shipping_geography','synced_at')],
  shopify_conversion:['session_conversion_by_device','session_conversion_by_device_source'].map(t=>daily(project,'shopify_data',t,'date')),
  shopify_catalogue:['products','collections','product_collections'].map(t=>snapshot(project,'shopify_catalogue',t,'catalogue_synced_at')),
  product_classifications:['product_classifications','collection_classifications'].map(t=>snapshot(project,'commerce',t)),
  klaviyo:[snapshot(project,'klaviyo','message_performance','retrieved_at'),{table:'window_coverage',kind:'window',query:`WITH w AS (SELECT report_start,report_end,reporting_timezone,status,row_count,retrieved_at FROM \`${project}.klaviyo.window_coverage\`) SELECT CAST(MIN(report_start) AS STRING) coverage_start,CAST(MAX(report_end) AS STRING) coverage_end,COUNTIF(status='collected') row_count,MAX(retrieved_at) actual_retrieved_at,ARRAY_AGG(STRUCT(CAST(report_start AS STRING) report_start,CAST(report_end AS STRING) report_end,reporting_timezone,status,row_count,CAST(retrieved_at AS STRING) retrieved_at) ORDER BY report_start) windows FROM w`},snapshot(project,'klaviyo','sync_status','retrieved_at')]
};return q[source]||[];}
export function coverageSql(project,source){const inspection=sourceInspections(project,source)[0];if(!inspection)throw new Error(`No coverage contract for ${source}`);return inspection.query;}
export async function ensureControl(bigquery,project){await bigquery.query({query:`CREATE SCHEMA IF NOT EXISTS \`${project}.${CONTROL_DATASET}\`; CREATE TABLE IF NOT EXISTS \`${project}.${CONTROL_DATASET}.collector_runs\` (run_id STRING, source STRING, status STRING, window_start DATE, window_end DATE, row_counts_json STRING, error STRING, started_at TIMESTAMP, finished_at TIMESTAMP); CREATE TABLE IF NOT EXISTS \`${project}.${CONTROL_DATASET}.collector_state\` (source STRING, successful_coverage_start DATE, successful_watermark DATE, last_success_at TIMESTAMP, last_run_id STRING, last_status STRING, row_counts_json STRING)`})}
export async function acquire(bigquery,project,source,runId){const [rows]=await bigquery.query({query:`BEGIN TRANSACTION; ASSERT NOT EXISTS(SELECT 1 FROM \`${project}.${CONTROL_DATASET}.collector_runs\` WHERE source=@source AND status='running' AND started_at>TIMESTAMP_SUB(CURRENT_TIMESTAMP(),INTERVAL 6 HOUR)) AS 'collector already running'; INSERT INTO \`${project}.${CONTROL_DATASET}.collector_runs\` VALUES(@runId,@source,'running',NULL,NULL,NULL,NULL,CURRENT_TIMESTAMP(),NULL); COMMIT TRANSACTION; SELECT @runId run_id`,params:{source,runId}});return rows[0]}
export function execute(command,args,{env=process.env}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{env,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('error',reject);child.on('close',code=>code===0?resolve({stdout,stderr}):reject(new Error(`${command} exited ${code}: ${stderr.slice(-2000)}`)))});}
export async function runCollector({source,bigquery,project,now=new Date(),executeCommand=execute}){if(!ORACLE_SOURCE_CONTRACTS[source]||ORACLE_SOURCE_CONTRACTS[source].retired)throw new Error(`${source} has no scheduled collector`);await ensureControl(bigquery,project);const runId=randomUUID();await acquire(bigquery,project,source,runId);try{const [coverage]=await bigquery.query({query:coverageSql(project,source)});const before=coverage[0]?.coverage_end||null;const [command,args]=plannedCommand(source,{now,coverageEnd:before});const output=await executeCommand(command,args);const [afterRows]=await bigquery.query({query:coverageSql(project,source)});const after=afterRows[0]?.coverage_end||before;await bigquery.query({query:`BEGIN TRANSACTION; UPDATE \`${project}.${CONTROL_DATASET}.collector_runs\` SET status='succeeded',window_start=SAFE_CAST(@before AS DATE),window_end=SAFE_CAST(@after AS DATE),row_counts_json=@counts,finished_at=CURRENT_TIMESTAMP() WHERE run_id=@runId; MERGE \`${project}.${CONTROL_DATASET}.collector_state\` t USING (SELECT @source source) s ON t.source=s.source WHEN MATCHED THEN UPDATE SET successful_coverage_start=COALESCE(t.successful_coverage_start,SAFE_CAST(@before AS DATE)),successful_watermark=SAFE_CAST(@after AS DATE),last_success_at=CURRENT_TIMESTAMP(),last_run_id=@runId,last_status='succeeded',row_counts_json=@counts WHEN NOT MATCHED THEN INSERT VALUES(@source,SAFE_CAST(@before AS DATE),SAFE_CAST(@after AS DATE),CURRENT_TIMESTAMP(),@runId,'succeeded',@counts); COMMIT TRANSACTION;`,params:{source,runId,before,after,counts:JSON.stringify({stdout_bytes:output.stdout.length})}});return {source,run_id:runId,status:'succeeded',coverage_before:before,successful_watermark:after,command:[command,...args]};}catch(error){await bigquery.query({query:`UPDATE \`${project}.${CONTROL_DATASET}.collector_runs\` SET status='failed',error=@error,finished_at=CURRENT_TIMESTAMP() WHERE run_id=@runId`,params:{runId,error:String(error.message).slice(0,1000)}}).catch(()=>{});throw error}}
async function main(){const source=process.argv[2];if(!source)throw new Error('Usage: node ops/collector-runner.js <source>');const credentials=JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON);const project=process.env.GOOGLE_PROJECT_ID||credentials.project_id;console.log(JSON.stringify(await runCollector({source,project,bigquery:new BigQuery({projectId:project,credentials})}),null,2))}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(error=>{console.error(error.message);process.exitCode=1});
