import { pathToFileURL } from 'node:url';
import crypto from 'node:crypto';
import { createBigQueryClient } from '../bigquery/client.js';
import { createShopifyGraphql, getShopifyAccessToken, loadShopifyConfig, missingShopifyConfig } from './admin-client.js';

export const DATASET = 'shopify_data';
export const TABLES = Object.freeze({ orders: 'order_locations', financials: 'order_financials', refunds: 'order_refunds' });
export const MATRIXIFY_APP_ID = 'gid://shopify/App/1758145';
const STATE = 'finance_refresh_state';
const RUNS = 'finance_refresh_runs';

const QUERY = `query FinanceRefresh($cursor:String,$query:String!){orders(first:50,after:$cursor,sortKey:UPDATED_AT,query:$query){pageInfo{hasNextPage endCursor}nodes{id name createdAt updatedAt processedAt cancelledAt currencyCode presentmentCurrencyCode paymentGatewayNames app{id name} retailLocation{id name} totalPriceSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} subtotalPriceSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} totalTaxSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} totalDiscountsSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} totalShippingPriceSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} totalRefundedSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} totalReceivedSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} transactions{ id kind status gateway createdAt processedAt amountSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}} refunds{id createdAt processedAt updatedAt note totalRefundedSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}} refundLineItems(first:100){nodes{id quantity restocked restockType lineItem{id name title sku}subtotalSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}totalTaxSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}}} refundShippingLines(first:25){nodes{id subtotalAmountSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}taxAmountSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}}} orderAdjustments(first:25){nodes{id reason amountSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}taxAmountSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}}} transactions(first:50){nodes{id kind status gateway createdAt processedAt amountSet{shopMoney{amount currencyCode}presentmentMoney{amount currencyCode}}}}}}}}`;

const iso = (value, name) => { const d = new Date(value); if (!value || Number.isNaN(d.valueOf())) throw new Error(`${name} must be an ISO timestamp`); return d.toISOString(); };
export function parseArgs(argv) {
  const out={mode:'collect',dataset:DATASET,project:process.env.GOOGLE_PROJECT_ID||'gf-full-data',overlapMinutes:120,maxPages:1000};
  for(let i=0;i<argv.length;i++){const [key,inline]=argv[i].split('=',2);const take=()=>inline??argv[++i];if(key==='--mode')out.mode=take();else if(key==='--start')out.start=take();else if(key==='--end')out.end=take();else if(key==='--project')out.project=take();else if(key==='--dataset')out.dataset=take();else if(key==='--overlap-minutes')out.overlapMinutes=Number(take());else if(key==='--max-pages')out.maxPages=Number(take());else throw new Error(`Unknown argument: ${key}`)}
  if(!['preflight','collect','scheduled','reconcile'].includes(out.mode))throw new Error('mode must be preflight, collect, scheduled, or reconcile');
  if(out.mode==='collect'||out.mode==='reconcile'){out.start=iso(out.start,'--start');out.end=iso(out.end,'--end');}
  if(out.end)out.end=iso(out.end,'--end');
  if(out.start&&out.end&&out.start>=out.end)throw new Error('--start must precede --end');
  if(!Number.isInteger(out.maxPages)||out.maxPages<1)throw new Error('--max-pages must be a positive integer');
  return out;
}

export async function fetchUpdatedOrders({graphql,start,end,maxPages=1000}){
  const orders=[], seen=new Set(); let cursor=null;
  // Quoted instants keep Shopify's search parser on the same UTC half-open
  // window that is validated below and later recorded in BigQuery.
  const search=`updated_at:>='${start}' updated_at:<'${end}'`;
  for(let page=1;page<=maxPages;page++){
    const data=await graphql(QUERY,{cursor,query:search}); const c=data?.orders;
    if(!c||!Array.isArray(c.nodes)||typeof c.pageInfo?.hasNextPage!=='boolean')throw new Error('Shopify returned an invalid orders connection');
    for(const order of c.nodes){if(!order.id||seen.has(order.id))throw new Error(`Duplicate or missing Shopify order identity: ${order.id||'missing'}`);seen.add(order.id);const updated=iso(order.updatedAt,'order.updatedAt');if(updated<start||updated>=end)throw new Error(`Shopify returned order ${order.id} outside the selected update window`);for(const refund of order.refunds||[]){if(refund.refundLineItems?.nodes?.length===100||refund.refundShippingLines?.nodes?.length===25||refund.orderAdjustments?.nodes?.length===25||refund.transactions?.nodes?.length===50)throw new Error(`Nested refund pagination may be incomplete for ${refund.id}`)}orders.push(order)}
    if(!c.pageInfo.hasNextPage)return {orders,pages:page,complete:true,search};
    if(!c.pageInfo.endCursor||c.pageInfo.endCursor===cursor)throw new Error('Shopify pagination is incomplete: missing or repeated cursor');cursor=c.pageInfo.endCursor;
  }
  throw new Error(`Shopify pagination is incomplete after ${maxPages} pages`);
}

const amount=(set,side)=>{const v=set?.[side]?.amount;return v==null?0:Number(v)};
export function transform(orders,syncedAt=new Date().toISOString()){
  const locations=[],financials=[],refunds=[];
  for(const o of orders){
    locations.push({order_id:o.id,order_name:o.name||null,created_at:o.createdAt||null,updated_at:o.updatedAt||null,order_source:o.app?.name||null,source_app_id:o.app?.id||null,retail_location_id:o.retailLocation?.id||null,retail_location_name:o.retailLocation?.name||null,synced_at:syncedAt});
    financials.push({order_id:o.id,order_name:o.name||null,created_at:o.createdAt||null,processed_at:o.processedAt||null,updated_at:o.updatedAt||null,cancelled_at:o.cancelledAt||null,order_source:o.app?.name||null,shop_currency:o.totalPriceSet?.shopMoney?.currencyCode||o.currencyCode||null,presentment_currency:o.totalPriceSet?.presentmentMoney?.currencyCode||o.presentmentCurrencyCode||null,original_total_shop:amount(o.totalPriceSet,'shopMoney'),original_total_presentment:amount(o.totalPriceSet,'presentmentMoney'),original_subtotal_shop:amount(o.subtotalPriceSet,'shopMoney'),original_subtotal_presentment:amount(o.subtotalPriceSet,'presentmentMoney'),original_tax_shop:amount(o.totalTaxSet,'shopMoney'),original_tax_presentment:amount(o.totalTaxSet,'presentmentMoney'),original_discounts_shop:amount(o.totalDiscountsSet,'shopMoney'),original_discounts_presentment:amount(o.totalDiscountsSet,'presentmentMoney'),original_shipping_shop:amount(o.totalShippingPriceSet,'shopMoney'),original_shipping_presentment:amount(o.totalShippingPriceSet,'presentmentMoney'),total_refunded_shop:amount(o.totalRefundedSet,'shopMoney'),total_refunded_presentment:amount(o.totalRefundedSet,'presentmentMoney'),total_received_shop:amount(o.totalReceivedSet,'shopMoney'),total_received_presentment:amount(o.totalReceivedSet,'presentmentMoney'),payment_gateway_names_json:JSON.stringify(o.paymentGatewayNames||[]),transactions_json:JSON.stringify(o.transactions||[]),synced_at:syncedAt});
    for(const r of o.refunds||[]){const li=r.refundLineItems?.nodes||[],sl=r.refundShippingLines?.nodes||[],ad=r.orderAdjustments?.nodes||[],tx=r.transactions?.nodes||[];const sum=(xs,k,s)=>xs.reduce((n,x)=>n+amount(x[k],s),0);const ok=tx.filter(x=>x.kind==='REFUND'&&x.status==='SUCCESS');refunds.push({refund_id:r.id,order_id:o.id,order_name:o.name||null,refund_created_at:r.createdAt||null,refund_processed_at:r.processedAt||null,refund_updated_at:r.updatedAt||null,shop_currency:r.totalRefundedSet?.shopMoney?.currencyCode||o.currencyCode||null,presentment_currency:r.totalRefundedSet?.presentmentMoney?.currencyCode||o.presentmentCurrencyCode||null,refund_total_shop:amount(r.totalRefundedSet,'shopMoney'),refund_total_presentment:amount(r.totalRefundedSet,'presentmentMoney'),refund_line_subtotal_shop:sum(li,'subtotalSet','shopMoney'),refund_line_subtotal_presentment:sum(li,'subtotalSet','presentmentMoney'),refund_shipping_subtotal_shop:sum(sl,'subtotalAmountSet','shopMoney'),refund_shipping_subtotal_presentment:sum(sl,'subtotalAmountSet','presentmentMoney'),refund_line_tax_shop:sum(li,'totalTaxSet','shopMoney'),refund_line_tax_presentment:sum(li,'totalTaxSet','presentmentMoney'),refund_shipping_tax_shop:sum(sl,'taxAmountSet','shopMoney'),refund_shipping_tax_presentment:sum(sl,'taxAmountSet','presentmentMoney'),refund_adjustment_tax_shop:sum(ad,'taxAmountSet','shopMoney'),refund_adjustment_tax_presentment:sum(ad,'taxAmountSet','presentmentMoney'),refund_tax_shop:sum(li,'totalTaxSet','shopMoney')+sum(sl,'taxAmountSet','shopMoney')+sum(ad,'taxAmountSet','shopMoney'),refund_tax_presentment:sum(li,'totalTaxSet','presentmentMoney')+sum(sl,'taxAmountSet','presentmentMoney')+sum(ad,'taxAmountSet','presentmentMoney'),successful_transaction_shop:sum(ok,'amountSet','shopMoney'),successful_transaction_presentment:sum(ok,'amountSet','presentmentMoney'),has_successful_refund_transaction:ok.length>0,note:r.note||null,refund_line_items_json:JSON.stringify(li),refund_shipping_lines_json:JSON.stringify(sl),order_adjustments_json:JSON.stringify(ad),transactions_json:JSON.stringify(tx),synced_at:syncedAt})}
  } return {orders:locations,financials,refunds};
}

const fq=(p,d,t)=>`\`${p}.${d}.${t}\``;
async function rows(bigquery,query,options={}){const [r]=await bigquery.query({query,useLegacySql:false,...options});return r}
export async function ensureControlTables(bigquery,project,dataset){await rows(bigquery,`CREATE TABLE IF NOT EXISTS ${fq(project,dataset,RUNS)} (run_id STRING, mode STRING, window_start TIMESTAMP, window_end TIMESTAMP, status STRING, order_count INT64, refund_count INT64, page_count INT64, error STRING, started_at TIMESTAMP, finished_at TIMESTAMP); CREATE TABLE IF NOT EXISTS ${fq(project,dataset,STATE)} (collector STRING, successful_watermark TIMESTAMP, run_id STRING, updated_at TIMESTAMP)`)}
export async function preflight({bigquery,project,dataset=DATASET}){const tableRows=await rows(bigquery,`SELECT table_name,row_count FROM ${fq(project,dataset,'INFORMATION_SCHEMA.TABLE_STORAGE')} WHERE table_name IN UNNEST(@tables)`,{params:{tables:Object.values(TABLES)}});const dependencies=await rows(bigquery,`SELECT table_name,table_type,ddl FROM ${fq(project,'finance','INFORMATION_SCHEMA.TABLES')} WHERE REGEXP_CONTAINS(LOWER(COALESCE(ddl,'')),r'shopify_data|order_financials|order_refunds|order_locations')`);return {read_only:true,destination_tables:tableRows,finance_dependencies:dependencies,decision:'Finance views/materialized views are dependencies only; no rebuild is issued. BigQuery views reflect promoted source rows and materialized views refresh under their existing policy.',square_warning:'The unresolved historical Square component issue remains visible. This collector does not read or change Square tax and does not reactivate Square collection.'}}

async function insertBatches(table,data){for(let i=0;i<data.length;i+=500)await table.insert(data.slice(i,i+500))}
export function promotionSql(project,dataset,stages){const replace=(dest,stage)=>`DELETE FROM ${fq(project,dataset,dest)} WHERE order_id IN (SELECT order_id FROM ${fq(project,dataset,stages.orders)}); INSERT INTO ${fq(project,dataset,dest)} SELECT * FROM ${fq(project,dataset,stage)}`;
return `BEGIN TRANSACTION; ${replace(TABLES.orders,stages.orders)}; ${replace(TABLES.financials,stages.financials)}; ${replace(TABLES.refunds,stages.refunds)}; UPDATE ${fq(project,dataset,RUNS)} SET status='succeeded',finished_at=CURRENT_TIMESTAMP() WHERE run_id=@runId; MERGE ${fq(project,dataset,STATE)} D USING (SELECT 'shopify_finance' collector,@end successful_watermark,@runId run_id,CURRENT_TIMESTAMP() updated_at) S ON D.collector=S.collector WHEN MATCHED THEN UPDATE SET successful_watermark=S.successful_watermark,run_id=S.run_id,updated_at=S.updated_at WHEN NOT MATCHED THEN INSERT ROW; COMMIT TRANSACTION;`}
export async function promote({bigquery,project,dataset=DATASET,runId,start,end,data,pages,mode,runRecorded=false}){await ensureControlTables(bigquery,project,dataset);if(!runRecorded)await rows(bigquery,`INSERT INTO ${fq(project,dataset,RUNS)} VALUES(@runId,@mode,@start,@end,'running',@orders,@refunds,@pages,NULL,CURRENT_TIMESTAMP(),NULL)`,{params:{runId,mode,start,end,orders:data.orders.length,refunds:data.refunds.length,pages}});else await rows(bigquery,`UPDATE ${fq(project,dataset,RUNS)} SET order_count=@orders,refund_count=@refunds,page_count=@pages WHERE run_id=@runId`,{params:{runId,orders:data.orders.length,refunds:data.refunds.length,pages}});const suffix=runId.replaceAll('-','_'),stages=Object.fromEntries(Object.entries(TABLES).map(([k,v])=>[k,`_${v}_${suffix}`]));try{for(const [k,dest]of Object.entries(TABLES)){await rows(bigquery,`CREATE TABLE ${fq(project,dataset,stages[k])} LIKE ${fq(project,dataset,dest)}`);await insertBatches(bigquery.dataset(dataset).table(stages[k]),data[k])}await rows(bigquery,promotionSql(project,dataset,stages),{params:{runId,end}})}catch(error){await rows(bigquery,`UPDATE ${fq(project,dataset,RUNS)} SET status='failed',error=@error,finished_at=CURRENT_TIMESTAMP() WHERE run_id=@runId`,{params:{runId,error:String(error.message).slice(0,1000)}}).catch(()=>{});throw error}finally{await Promise.all(Object.values(stages).map(t=>bigquery.dataset(dataset).table(t).delete({ignoreNotFound:true}).catch(()=>{})))}return {run_id:runId,status:'succeeded',window:{start,end},counts:{orders:data.orders.length,refunds:data.refunds.length},pages,successful_watermark:end}}
export async function reconcile({bigquery,project,dataset=DATASET,start,end}){const r=await rows(bigquery,`SELECT (SELECT COUNT(*) FROM ${fq(project,dataset,TABLES.financials)} WHERE updated_at>=@start AND updated_at<@end) source_orders,(SELECT COUNT(*) FROM ${fq(project,dataset,TABLES.refunds)} WHERE refund_created_at>=@start AND refund_created_at<@end) source_refunds,(SELECT COUNT(*) FROM ${fq(project,'finance','accountant_transactions')} WHERE date>=DATE(@start) AND date<=DATE(@end) AND REGEXP_CONTAINS(LOWER(COALESCE(source,'')),r'shopify')) finance_rows,(SELECT SUM(original_total_presentment) FROM ${fq(project,dataset,TABLES.financials)} WHERE created_at>=@start AND created_at<@end) source_order_total,(SELECT SUM(gross) FROM ${fq(project,'finance','accountant_transactions')} WHERE date>=DATE(@start) AND date<DATE(@end) AND REGEXP_CONTAINS(LOWER(COALESCE(source,'')),r'shopify')) finance_total`,{params:{start,end}});return {read_only:true,window:{start,end},...r[0],square_warning:'Square is excluded; its historical component issue remains unresolved.'}}

export async function run({options,bigquery,graphql,now=()=>new Date().toISOString()}){if(options.mode==='preflight')return preflight({...options,bigquery});if(options.mode==='reconcile')return reconcile({...options,bigquery});await ensureControlTables(bigquery,options.project,options.dataset);let end=options.end?iso(options.end,'--end'):iso(now(),'now'),start=options.start;if(options.mode==='scheduled'){const state=await rows(bigquery,`SELECT successful_watermark FROM ${fq(options.project,options.dataset,STATE)} WHERE collector='shopify_finance' LIMIT 1`);if(!state[0]?.successful_watermark)throw new Error('No successful watermark exists; run an explicit bounded collection first');start=new Date(new Date(state[0].successful_watermark).valueOf()-options.overlapMinutes*60000).toISOString()}start=iso(start,'window start');const runId=crypto.randomUUID();await rows(bigquery,`INSERT INTO ${fq(options.project,options.dataset,RUNS)} VALUES(@runId,@mode,@start,@end,'running',0,0,0,NULL,CURRENT_TIMESTAMP(),NULL)`,{params:{runId,mode:options.mode,start,end}});try{const fetched=await fetchUpdatedOrders({graphql,start,end,maxPages:options.maxPages});const data=transform(fetched.orders,now());return await promote({...options,bigquery,runId,start,end,data,pages:fetched.pages,runRecorded:true})}catch(error){await rows(bigquery,`UPDATE ${fq(options.project,options.dataset,RUNS)} SET status='failed',error=@error,finished_at=CURRENT_TIMESTAMP() WHERE run_id=@runId AND status='running'`,{params:{runId,error:String(error.message).slice(0,1000)}}).catch(()=>{});throw error}}

export async function main({argv=process.argv.slice(2),env=process.env,write=s=>process.stdout.write(s)}={}){const options=parseArgs(argv);const {bigquery}=createBigQueryClient({...env,GOOGLE_PROJECT_ID:options.project});let graphql;if(options.mode==='collect'||options.mode==='scheduled'){const missing=missingShopifyConfig(env);if(missing.length)throw new Error(`Missing configuration: ${missing.join(', ')}`);const config=loadShopifyConfig(env),token=await getShopifyAccessToken(config);graphql=createShopifyGraphql({...config,token})}write(`${JSON.stringify(await run({options,bigquery,graphql}),null,2)}\n`)}
if(import.meta.url===pathToFileURL(process.argv[1]||'').href)main().catch(e=>{console.error(e.message);process.exitCode=1});
